Rule S5689 Recovering fingerprints from web application technologies should not be possible
SonarSource/SonarJS pull request #2065
Opened 2020-08-14 06:51 UTC by andrey-tyukin-sonarsource

Fixes #1836

2020-08-14 14:06 UTC, vilchik-elena commented on eslint-bridge/tests/rules/express-header-hide-x-powered-by.test.ts
> +  parser: require.resolve('@typescript-eslint/parser'),
why not using default parser?

2020-08-14 14:06 UTC, vilchik-elena commented on eslint-bridge/tests/rules/express-header-hide-x-powered-by.test.ts
> +import { rule } from '../../src/rules/express-header-hide-x-powered-by';
remove `../../src/`

2020-08-14 14:07 UTC, vilchik-elena commented on eslint-bridge/tests/rules/express-header-hide-x-powered-by.test.ts
> +ruleTester.run('X-Powered-By should be hidden', rule, {
we usually put rule title here

2020-08-14 14:08 UTC, vilchik-elena commented on eslint-bridge/tests/rules/express-header-hide-x-powered-by.test.ts
> +        var express = require('express')
I think we should prefer `let`/`const` declaration in tests (as it is more common in new js code) and putting `;` after each statement

2020-08-14 14:13 UTC, vilchik-elena commented on eslint-bridge/tests/rules/express-header-hide-x-powered-by.test.ts
> +        var coverage = true, only = true;
what are we testing here?

2020-08-14 14:15 UTC, vilchik-elena commented on eslint-bridge/tests/rules/express-header-hide-x-powered-by.test.ts
> +        app.use(require('helmet')()) // Compliant
let's add test where middleware is instantiated but not passed in `app.use`

2020-08-14 14:15 UTC, vilchik-elena commented on eslint-bridge/tests/rules/express-header-hide-x-powered-by.test.ts
> +  invalid: [
let's add test with 2 apps (one safe and one unsafe) to show this limitation

2020-08-14 14:17 UTC, vilchik-elena commented on eslint-bridge/tests/rules/express-header-hide-x-powered-by.test.ts
> +        app.set("x-powered-by", false) // Compliant
did you discuss with @eric-therond-sonarsource if we should mention this patten and pattern with `helmet` in the rule description?

2020-08-14 14:19 UTC, vilchik-elena commented on eslint-bridge/src/rules/express-header-hide-x-powered-by.ts
> +  middleware: string[],
why we need this parameter if it's always the same value?

2020-08-14 14:21 UTC, vilchik-elena commented on eslint-bridge/src/rules/express-header-hide-x-powered-by.ts
> +// Limitations:
add tests to show these limitations (and I would drop these comments then)

2020-08-14 14:30 UTC, vilchik-elena commented on eslint-bridge/src/rules/express-header-hide-x-powered-by.ts
> +function checkUseMiddleware(
rename these boolean-returning functions to start with `is`

2020-08-14 14:31 UTC, vilchik-elena commented on eslint-bridge/src/rules/express-header-hide-x-powered-by.ts
> +            checkUseMiddleware(callExpr, context, appInstantiation, PROTECTING_MIDDLEWARE) ||
we discussed with Tibor that we want `context` to be first parameter in such functions

2020-08-14 14:32 UTC, vilchik-elena commented on eslint-bridge/src/rules/express-header-hide-x-powered-by.ts
> +function checkDisable(callExpression: estree.CallExpression, app: estree.Identifier): boolean {
tbh the name is not very helpful, can we say what is disabled?

2020-08-14 14:32 UTC, vilchik-elena commented on eslint-bridge/src/rules/express-header-hide-x-powered-by.ts
> +function checkSetFalse(callExpression: estree.CallExpression, app: estree.Identifier): boolean {
again about name, change it so that it's clear what is set to false

2020-08-14 14:37 UTC, vilchik-elena commented on eslint-bridge/src/rules/express-header-hide-x-powered-by.ts
> +        if (!isSafe && appInstantiation == null) {
use `!appInstantiation` to be consistent

2020-08-14 14:39 UTC, vilchik-elena commented on eslint-bridge/src/rules/express-header-hide-x-powered-by.ts
> +  if (varDecl.declarations.length === 1) {
I don't get why are we forcing this condition? what's wrong with `let app = express(), zoo = 42`?
I think we should support it as well. And I would subscribe to `VariableDeclarator` instead to ease the logic

2020-08-14 14:40 UTC, vilchik-elena commented on eslint-bridge/src/rules/express-header-hide-x-powered-by.ts
> +      const rhsCall = rhs as estree.CallExpression;
can be inlined

2020-08-14 14:40 UTC, vilchik-elena commented on eslint-bridge/src/rules/express-header-hide-x-powered-by.ts
> +      const callee = rhsCall.callee;
destructuring can be used: `const { callee } = rhsCall`

2020-08-14 14:42 UTC, vilchik-elena commented on eslint-bridge/src/rules/express-header-hide-x-powered-by.ts
> +      if (getModuleNameOfNode(callee, context)?.value === 'express') {
how about creating constant for `express`?

2020-08-14 14:50 UTC, vilchik-elena commented on eslint-bridge/src/rules/express-header-hide-x-powered-by.ts
> +function checkUseMiddleware(
I think with this implementation we don't support following pattern
```
const helmet = require('helmet');
const helmet1 = helmet();
app.use(helmet1);
```

2020-08-17 06:31 UTC, andrey-tyukin-sonarsource commented on eslint-bridge/src/rules/express-header-hide-x-powered-by.ts
> +const HEADER_X_POWERED_BY = 'X-Powered-By'.toLowerCase();
HTTP Headers are case insensitive: [question on SO](https://stackoverflow.com/questions/5258977/are-http-headers-case-sensitive), i.e. it doesn't matter whether the user invokes `app.disable('X-Powered-By')` or `app.disable('x-powered-by')`. I've seen the lowercase version multiple times.

2020-08-17 06:34 UTC, andrey-tyukin-sonarsource commented on javascript-checks/src/main/java/org/sonar/javascript/checks/HidePoweredByCheck.java
> +public class HidePoweredByCheck extends EslintBasedCheck {
Since the entire check is concerned with X-Powered-By header, I've renamed it to XPoweredByCheck, that seems the least unexpected variant.

2020-08-17 08:15 UTC, andrey-tyukin-sonarsource commented on eslint-bridge/tests/rules/express-header-hide-x-powered-by.test.ts
> +        app.set("x-powered-by", false) // Compliant
Regarding the improvements that were implemented, I got the response ["nice improvements"](https://github.com/SonarSource/SonarJS/issues/1836#issuecomment-674155003).

2020-08-17 08:18 UTC, andrey-tyukin-sonarsource commented on eslint-bridge/src/rules/express-header-hide-x-powered-by.ts
> +  middleware: string[],
Because the method body does not depend in any way on a particular choice of middlewares, so this is reflected in the signature. It also makes the method reusable: as soon as I encounter a similar case again, I'll consider reusing it.

2020-08-17 08:22 UTC, andrey-tyukin-sonarsource commented on eslint-bridge/src/rules/express-header-hide-x-powered-by.ts
> +// Limitations:
The second one is actually not a problem for this particular header: "This middleware takes no options.". Added test for first one.

2020-08-17 13:51 UTC, andrey-tyukin-sonarsource commented
Checking whether `app` escapes into some method (4b43123) was discussed with Eric Therond.

2020-08-18 06:04 UTC, vilchik-elena commented on eslint-bridge/tests/rules/express-header-hide-x-powered-by.test.ts
> +  invalid: [
I don't find such test

2020-08-18 06:06 UTC, vilchik-elena commented on eslint-bridge/tests/rules/express-header-hide-x-powered-by.test.ts
> +        app.set("x-powered-by", false) // Compliant
I don't question your improvements, I've asked if rule description should be updated. Eric added `helmet` to it, please update

2020-08-18 06:15 UTC, vilchik-elena commented on eslint-bridge/src/rules/express-header-hide-x-powered-by.ts
> +function checkUseMiddleware(
I was implying that we should update implementation to support it :)

2020-08-18 12:26 UTC, andrey-tyukin-sonarsource commented on eslint-bridge/src/rules/express-header-hide-x-powered-by.ts
> +
Renamed all `x-powered-by`-related things to `x-powered-by` and `XPoweredBy`.

2020-08-18 12:27 UTC, andrey-tyukin-sonarsource commented on eslint-bridge/src/rules/express-header-hide-x-powered-by.ts
> +const NUM_ARGS_SET = 2;
Done.

2020-08-18 12:27 UTC, andrey-tyukin-sonarsource commented on eslint-bridge/tests/rules/express-header-hide-x-powered-by.test.ts
> +  parser: require.resolve('@typescript-eslint/parser'),
Copy-paste artifact. Removed.

2020-08-18 12:28 UTC, andrey-tyukin-sonarsource commented on eslint-bridge/tests/rules/express-header-hide-x-powered-by.test.ts
> +ruleTester.run('X-Powered-By should be hidden', rule, {
Copied title from ticket description.

2020-08-18 12:28 UTC, andrey-tyukin-sonarsource commented on eslint-bridge/tests/rules/express-header-hide-x-powered-by.test.ts
> +        var express = require('express')
replaced everything by consts

2020-08-18 12:28 UTC, andrey-tyukin-sonarsource commented on eslint-bridge/tests/rules/express-header-hide-x-powered-by.test.ts
> +        var coverage = true, only = true;
Code coverage corner case. No longer needed.

2020-08-18 12:30 UTC, andrey-tyukin-sonarsource commented on eslint-bridge/tests/rules/express-header-hide-x-powered-by.test.ts
> +        app.use(require('helmet')()) // Compliant
This is the test with comment `// imported, but forgot to use helmet`.

2020-08-18 12:31 UTC, andrey-tyukin-sonarsource commented on eslint-bridge/tests/rules/express-header-hide-x-powered-by.test.ts
> +  invalid: [
I don't understand what this comment is referring to. If it's referring to previous comment: there is an invalid test where `helmet` is instantiated but left unused.

2020-08-18 12:38 UTC, andrey-tyukin-sonarsource commented on eslint-bridge/tests/rules/express-header-hide-x-powered-by.test.ts
> +        app.set("x-powered-by", false) // Compliant
Oh, he's also added `helmet.hidePoweredBy()`. This will have to be added, after all.

2020-08-18 13:19 UTC, andrey-tyukin-sonarsource commented on eslint-bridge/src/rules/express-header-hide-x-powered-by.ts
> +function checkUseMiddleware(
`isUsingMiddleware` now.

2020-08-18 13:19 UTC, andrey-tyukin-sonarsource commented on eslint-bridge/src/rules/express-header-hide-x-powered-by.ts
> +            checkUseMiddleware(callExpr, context, appInstantiation, PROTECTING_MIDDLEWARE) ||
moved.

2020-08-18 13:20 UTC, andrey-tyukin-sonarsource commented on eslint-bridge/src/rules/express-header-hide-x-powered-by.ts
> +function checkDisable(callExpression: estree.CallExpression, app: estree.Identifier): boolean {
`isDisabledXPoweredBy` + `isSetFalseXPoweredBy` now.

2020-08-18 13:20 UTC, andrey-tyukin-sonarsource commented on eslint-bridge/src/rules/express-header-hide-x-powered-by.ts
> +function checkSetFalse(callExpression: estree.CallExpression, app: estree.Identifier): boolean {
It's `isSetFalseXPoweredBy` now.

2020-08-18 13:21 UTC, andrey-tyukin-sonarsource commented on eslint-bridge/src/rules/express-header-hide-x-powered-by.ts
> +        if (!isSafe && appInstantiation == null) {
ok: `if (!isSafe && !appInstantiation)`

2020-08-18 13:21 UTC, andrey-tyukin-sonarsource commented on eslint-bridge/src/rules/express-header-hide-x-powered-by.ts
> +  if (varDecl.declarations.length === 1) {
Changed to VariableDeclarator, that was a really good idea. Also, it removed some strange corner cases that were unreachable by coverage.

2020-08-18 13:22 UTC, andrey-tyukin-sonarsource commented on eslint-bridge/src/rules/express-header-hide-x-powered-by.ts
> +      const rhsCall = rhs as estree.CallExpression;
`const { callee } = rhs as estree.CallExpression;`

2020-08-18 13:23 UTC, andrey-tyukin-sonarsource commented on eslint-bridge/src/rules/express-header-hide-x-powered-by.ts
> +      const callee = rhsCall.callee;
`const { callee } = rhs as estree.CallExpression;`

2020-08-18 13:23 UTC, andrey-tyukin-sonarsource commented on eslint-bridge/src/rules/express-header-hide-x-powered-by.ts
> +      if (getModuleNameOfNode(callee, context)?.value === 'express') {
Done.

2020-08-18 13:25 UTC, andrey-tyukin-sonarsource commented on eslint-bridge/src/rules/express-header-hide-x-powered-by.ts
> +function checkUseMiddleware(
```
{
        code: `
        const express = require('express');
        const helmet = require('helmet');
        const helmetInst = helmet();
        const app = express();
        app.use(helmetInst); // compliant
      `,
      },
```
It's now supported. Here is the test, with `helmetInst` instead of `helmet1`.

2020-08-19 08:09 UTC, andrey-tyukin-sonarsource commented on eslint-bridge/tests/rules/express-header-hide-x-powered-by.test.ts
> +        app.set("x-powered-by", false) // Compliant
Updated metadata, implemented `helmet.hidePoweredBy()`-case.

2020-08-19 10:14 UTC, saberduck requested changes
looks mostly good, just few minor comments!

2020-08-19 10:14 UTC, saberduck commented on eslint-bridge/src/rules/x-powered-by.ts
> +function flatMap<A, B>(xs: A[], f: (e: A) => B[]): B[] {
I was really surprised this is not available on Node, but indeed it looks like we will need to wait until next year. 
You can write it also just by using reduce as `xs.reduce((acc: B[], val) => acc.concat(f(val)), []);`

2020-08-19 10:14 UTC, saberduck commented on eslint-bridge/src/rules/x-powered-by.ts
> +    callExpression.callee.object.type === 'Identifier' &&
you can use `isIdentifier` function from `utils`, ie `isIdentifier(callExpression.callee.object, objectIdentifierName)`

2020-08-19 10:14 UTC, saberduck commented on eslint-bridge/src/rules/x-powered-by.ts
> +    callExpression.callee.property.type === 'Identifier' &&
same as above, use `isIdentifier`

2020-08-19 10:28 UTC, andrey-tyukin-sonarsource commented on eslint-bridge/src/rules/x-powered-by.ts
> +  function flattenHelper(noDerefNode: estree.Node): estree.Node[] {
It does behave in exactly the same way as the inlined version. The only reason why it exists is that it cannot accidentally recurse on `nodePossiblyIdentifier`, because the variable is not in scope of this helper method. 

Anyway, as it's not clearer, I'll inline it.

2020-08-19 10:32 UTC, andrey-tyukin-sonarsource commented on eslint-bridge/src/rules/x-powered-by.ts
> +function flatMap<A, B>(xs: A[], f: (e: A) => B[]): B[] {
Indeed, it saves couple of lines, but `acc.concat(...)` keeps reallocating a new list every time, whereas `.push(...)` doesn't.

2020-08-20 07:36 UTC, saberduck approved these changes

2020-08-20 07:38 UTC, merged