Fix FP on S1128 for "jsx" import used in "Emotion" pragma
SonarSource/SonarJS pull request #2163
Opened 2020-09-22 10:46 UTC by yassin-kammoun-sonarsource

Fixes #1273

2020-09-22 15:34 UTC, guillaume-dequenne-sonarsource requested changes
Looks good but please have a look at my comment: I think we can either make the condition a bit more strict or be more explicit about the pattern we exclude.

2020-09-22 15:34 UTC, guillaume-dequenne-sonarsource commented on eslint-bridge/src/rules/unused-import.ts
> +            !isJsxPragmaSet
To me it's a bit unclear what we are trying to exclude.
Do we really want to exclude all import of `jsx` names and all imports from `@emotion/core` specifically?

From my understanding of the [documentation](https://emotion.sh/docs/css-prop#jsx-pragma), it's really the pragma comment that makes us want to ignore this pattern (and it seems like it being absent would cause problems with the Emotion library). 

If I'm mistaken and there are other patterns (maybe in another version of this framework or something) that we actually want to exclude (maybe just to be safe...), I think it'd be worth it to have explicit tests for them.

2020-09-23 07:14 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/rules/unused-import.ts
> +            !isJsxPragmaSet
> To me it's a bit unclear what we are trying to exclude.
> Do we really want to exclude all import of `jsx` names and all imports from `@emotion/core` specifically?

You are right! It's not specific to `@emotion/core`. I just relaxed that condition.

> If I'm mistaken and there are other patterns (maybe in another version of this framework or something) that we actually want to exclude (maybe just to be safe...), I think it'd be worth it to have explicit tests for them.

I added a test case for "any" imported source.

2020-09-23 08:20 UTC, guillaume-dequenne-sonarsource approved these changes
lgtm

2020-09-23 08:20 UTC, merged