Migrate S3403 to eslint frontend for JS
SonarSource/SonarJS pull request #2230
Opened 2020-10-08 06:26 UTC by yassin-kammoun-sonarsource

Fixes #2203

2020-10-13 14:54 UTC, guillaume-dequenne-sonarsource requested changes
Implementation looks good, although you forgot to add the `sonar-runtime` for secondary locations to render correctly.

Ruling issues are a bit disappointing. I left comments on the issues which looked fishy to me, although I don't expect all of them to be actionable, but some might... We can discuss it if you want.

2020-10-13 14:54 UTC, guillaume-dequenne-sonarsource commented on its/ruling/src/test/expected/js/ocanvas/javascript-S3403.json
> +{
I understand why we raise this and it makes sense, but to me it feels like this is where the type inference of TS falls a bit short for JS code as those variables are clearly used as unions of `string` and `number` and the operations make sense (still I believe they deserve an issue for that, just not this one 😄 )

2020-10-13 14:54 UTC, guillaume-dequenne-sonarsource commented on its/ruling/src/test/expected/js/jquery/javascript-S3403.json
> +5,
I think this one is a FP as both objects are `Window`, although using `getTypeAsString`, I get types `Window` and `Window and typeof globalThis` (and no common flags between the two). Maybe it's just a special case that we have to exclude manually, or maybe there is something else we can do? Not sure...

2020-10-13 14:54 UTC, guillaume-dequenne-sonarsource commented on its/ruling/src/test/expected/js/p5.js/javascript-S3403.json
> +'p5.js:src/webgl/p5.Matrix.js':[
In this file I think we also have a problem with `this` keyword. Maybe we should ignore it for this rule?

2020-10-14 06:39 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/tests/rules/different-types-comparison.test.ts
> +          message: `{\"message\":\"Remove this \\\"===\\\" check; it will always be false. Did you mean to use \\\"==\\\"?\",\"secondaryLocations\":[{\"column\":8,\"line\":3,\"endColumn\":11,\"endLin
That's a great idea! Thank you.

2020-10-14 08:20 UTC, yassin-kammoun-sonarsource commented on its/ruling/src/test/expected/js/underscore/javascript-S3403.json
> +246,
This case is interesting; the returned type of `keyFinder` is the union `string | number`, which the current implementation does not take into account. I think we need to consider both intersection and union.

2020-10-14 08:55 UTC, yassin-kammoun-sonarsource commented on its/ruling/src/test/expected/js/jquery/javascript-S3403.json
> +5,
Same as above. It is definitely a false positive because we don't consider intersections.

2020-10-14 08:57 UTC, yassin-kammoun-sonarsource commented on its/ruling/src/test/expected/js/p5.js/javascript-S3403.json
>  'p5.js:lib/addons/p5.sound.js':[
Same as above, i.e., missing handling of unions (and intersections). Type inference based on JSDoc is correct here, and actually helps.

2020-10-14 09:45 UTC, yassin-kammoun-sonarsource commented on its/ruling/src/test/expected/js/angular.js/javascript-S3403.json
> +274,
That's right, and I know why those were raised; it's because the implementation didn't consider the underlying symbol of the types, here `Scope`. This can be generalized to functions and classes.

2020-10-14 12:20 UTC, yassin-kammoun-sonarsource commented on its/ruling/src/test/expected/js/p5.js/javascript-S3403.json
> +'p5.js:src/webgl/p5.Matrix.js':[
I added an exception for `this` that can't be resolved.

2020-10-14 15:11 UTC, guillaume-dequenne-sonarsource approved these changes
Nice improvement of the rule!
There are a couple tests that don't work as intended, not sure if you can replicate the behavior from JSDoc type inference to have something that works correctly though.

2020-10-14 15:11 UTC, guillaume-dequenne-sonarsource commented on eslint-bridge/tests/rules/different-types-comparison.test.ts
> +      code: `
I think those don't actually test what you intend to test, as types of `union` and `str` are inferred to be `any`. I believe the `TS` parser used for tests doesn't use JSDoc comments to infer types.

2020-10-15 08:04 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/tests/rules/different-types-comparison.test.ts
> +      code: `
Didn't manage to understand why JSDoc were not taken into account. As a consequence, those were replaced with TypeScript annotations.

2020-10-15 08:46 UTC, merged