Migrate S2819 to eslint frontend for JS/TS (new rule for TS)
SonarSource/SonarJS pull request #2243
Opened 2020-10-12 15:10 UTC by guillaume-dequenne-sonarsource

Fixes #2202

2020-10-13 14:19 UTC, yassin-kammoun-sonarsource requested changes
Looking at the [RSPEC](https://jira.sonarsource.com/browse/RSPEC-2819), I notice the following regarding the Java-based implementation of the rule:
- It does not totally cover the description of the rule since handling the case for receiving messages and checking the origin is not implemented.
- It does not check the target origin when posting a message, i.e., whether the origin is the wilcard `*` keyword or not as the second argument of the call.

With regard to handling message receiving, I let you decide whether you want to implement the missing parts now or create a ticket. On the other hand, for the message posting case, I think we can already do some improvements here.

2020-10-14 09:57 UTC, guillaume-dequenne-sonarsource commented on eslint-bridge/src/rules/post-message.ts
> +        if (type.match(/window/i) || type.match(/globalThis/i) || hasWindowName) {
I kept something similar to the previous implementation which allowed to report on anything that had `window` in its name but might be an unknown function such as `getWindow().postMessage("message", "*")`. Not sure we actually want to keep reporting on those though...Wdyt?

2020-10-14 11:01 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/rules/post-message.ts
> +        if (type.match(/window/i) || type.match(/globalThis/i) || hasWindowName) {
I think it makes sense to keep this heuristic (i.e., hasWindowName) in case TypeScript compiler fails to infer the target object as being a `Window`. However, I would still replace `type.match(/window/i) || type.match(/globalThis/i)` with my suggestion `isWindowLike`. I feel unease about testing this `globalThis` thing. From what I saw, it's related to intersection types and might not be specific to `Window`.

2020-10-14 13:18 UTC, guillaume-dequenne-sonarsource commented on eslint-bridge/src/rules/post-message.ts
> +        }
As discussed, I'll keep the heuristic as it is for now, as I don't expect we'll raise FPs in practical cases.

2020-10-14 13:23 UTC, yassin-kammoun-sonarsource approved these changes
Looks good to me.

2020-10-14 13:23 UTC, merged