Migrate S3800 to eslint frontend for JS
SonarSource/SonarJS pull request #2253
Opened 2020-10-15 13:59 UTC by yassin-kammoun-sonarsource

Fixes #2207

--
Here are some remarks about the rule implementation:
- The rule ignores functions having multiple return types (i.e. unions) if the function documentation includes the `@return` JSDoc, and considers that the developer is aware of that.
- `ts.Type#isUnion` is not enough to determine whether a type is really a union. There are cases where TypeScript compiler types an expression as being a union while it's not, e.g. the return type of a function including `if (condition) return true; else return false;` is `false | true`.
- Because TypeScript has a dedicated type for object literals, e.g., `{ foo: 'hello' }` has type `{ foo: string }`, the rule disregards the underlying structure of the object types and considers those as `object`. This relaxation in the rule allows, for example, return types of the form `{ foo: string } | {}`.

2020-10-16 12:53 UTC, guillaume-dequenne-sonarsource requested changes
Implementation looks good to me.
As discussed, there are just some minor changes to issue reporting that I believe would make the readability a bit better.

2020-10-16 12:53 UTC, guillaume-dequenne-sonarsource commented on its/ruling/src/test/expected/js/p5.js/javascript-S3800.json
> +184,
In this file we highlight the `return null`. I believe we should not as it's not the reason we raise an issue.

2020-10-16 12:53 UTC, guillaume-dequenne-sonarsource commented on its/ruling/src/test/expected/js/p5.js/javascript-S3800.json
> +626,
I think secondary location is a bit hard to read as it enumerates all the properties of the object. I think a simple `return object` would be enough in this kind of cases.

2020-10-19 13:11 UTC, guillaume-dequenne-sonarsource requested changes
A couple additional comments on reporting for some edge cases.

2020-10-19 13:11 UTC, guillaume-dequenne-sonarsource commented on its/ruling/src/test/expected/js/p5.js/javascript-S3800.json
> +487,
Here we still have some reporting problems for arrays of objects, I think it would be nice if we could display `object[]` instead.

2020-10-19 13:11 UTC, guillaume-dequenne-sonarsource commented on its/ruling/src/test/expected/js/javascript-test-sources/javascript-S3800.json
> +252,
Sorry I missed this previously, but I believe we should not report if the returned elements are always functions that differ only by signature.
Also, when we report on function, I believe we can simply display `function` instead of its signature, as it could get hard to read.

2020-10-19 13:48 UTC, yassin-kammoun-sonarsource commented on its/ruling/src/test/expected/js/p5.js/javascript-S3800.json
> +487,
As I feared, something goes wrong on TypeScript side when resolving the element type of arrays. As a consequence, I resolved their string representation manually for a few cases.

2020-10-19 17:12 UTC, guillaume-dequenne-sonarsource reviewed
There are still 2 cases on ruling that appear a bit weird to me. Let's discuss them tomorrow.

2020-10-19 17:12 UTC, guillaume-dequenne-sonarsource commented on its/ruling/src/test/expected/js/knockout/javascript-S3800.json
> +67,
Here we now report with secondary only on of of the returns statement with type `any[]`. Is skipping some highlighting on return statements with unresolvable types intended?

2020-10-19 17:12 UTC, guillaume-dequenne-sonarsource commented on its/ruling/src/test/expected/js/angular.js/javascript-S3800.json
> +54,
Here we now only report on 1 return statement that returns `object`. Is this intended?

2020-10-20 06:57 UTC, yassin-kammoun-sonarsource commented on its/ruling/src/test/expected/js/knockout/javascript-S3800.json
> +67,
This is a corner case with return type of the form `void | something` which is not handled correctly. Will fix that.

2020-10-20 06:57 UTC, yassin-kammoun-sonarsource commented on its/ruling/src/test/expected/js/angular.js/javascript-S3800.json
> +54,
Nope. Same problem as above.

2020-10-20 07:58 UTC, yassin-kammoun-sonarsource commented on its/ruling/src/test/expected/js/knockout/javascript-S3800.json
> +67,
Even though [dd4b5d9](https://github.com/SonarSource/SonarJS/pull/2253/commits/dd4b5d908c49ebb3d2c12e6d13c8ea61be04d836) fixes some cases, it didn't get rid of this wrongly raised issue. After having another look, it turned out to by TypeScript's fault, which incorrectly infer the return type of the function.

Not sure we can do anything about that.

2020-10-20 11:30 UTC, guillaume-dequenne-sonarsource approved these changes
LGTM

2020-10-20 11:31 UTC, merged