Rule S5604 Using intrusive permissions is security-sensitive
SonarSource/SonarJS pull request #2301
Opened 2020-11-03 13:51 UTC by andrea-guarino-sonarsource

Fixes #1769

2020-11-03 16:57 UTC, guillaume-dequenne-sonarsource requested changes
I left a few minor comments and there's probably an issue message that should be updated, but looks good otherwise.

2020-11-03 16:57 UTC, guillaume-dequenne-sonarsource commented on eslint-bridge/src/rules/no-intrusive-permissions.ts
> +  const firstArg = getUniqueWriteUsageOrNode(context, call.arguments[0]);
I think you can use `getValueOfExpression(context, call.arguments[0], 'ObjectExpression)` instead.

2020-11-03 16:57 UTC, guillaume-dequenne-sonarsource commented on eslint-bridge/src/rules/no-intrusive-permissions.ts
> +    const value = getUniqueWriteUsageOrNode(context, prop.value);
Same here, you can use `getValueOfExpression(context, prop.value, 'Literal')`

2020-11-04 10:56 UTC, andrea-guarino-sonarsource commented on eslint-bridge/src/rules/no-intrusive-permissions.ts
> +        message: 'Make sure the use of the geolocation is necessary.',
Indeed, I forgot to parametrize the message. thank you!

2020-11-04 10:59 UTC, andrea-guarino-sonarsource commented on eslint-bridge/src/rules/no-intrusive-permissions.ts
> +          context.options.includes('microphone') &&
In the ticket description, there is the following:
> Camera and microphone are requested both at the same time when getUserMedia() method is called so in this case the message should be Make sure the use of the camera and microphone is necessary.

I'm not sure we should report only when they are both included or one is enough.
@eric-therond-sonarsource wdyt?

2020-11-04 11:00 UTC, andrea-guarino-sonarsource commented on eslint-bridge/src/rules/no-intrusive-permissions.ts
> +          context.options.includes('microphone') &&
> Also I see on the examples that there might be a constraints argument on the navigator.mediaDevices.getUserMedia call, with audio and video properties. Can this be relevant to when we should decide to report? (I assume it's not worth tracking though - just took the opportunity to address it explicitly).

As far as I've understood it's not relevant to raise the issue. @eric-therond-sonarsource can you please clarify?

2020-11-04 14:12 UTC, eric-therond-sonarsource commented on eslint-bridge/src/rules/no-intrusive-permissions.ts
> +          context.options.includes('microphone') &&
About `constraints` argument you are right, good catch, 
the constraints object is mandatory, if not passed to the `getUserMedia` method, both audio and video will not be requested and when `audio` property or `video` property different from `false` then the corresponding media will be requested:
```
navigator.mediaDevices.getUserMedia({ audio: true, video: true }) // Sensitive for camera and microphone (if both permissions have been defined by the user in the parameter of this custom rule)
```

2020-11-04 14:17 UTC, eric-therond-sonarsource commented on eslint-bridge/src/rules/no-intrusive-permissions.ts
> +          context.options.includes('microphone') &&
And so the message suggested on  he ticket is wrong:
> Camera and microphone are requested both at the same time when getUserMedia() method is called so in this case the message should be Make sure the use of the camera and microphone is necessary.

we should have this message "_Make sure the use of the [camera (or|and) microphone] is/are necessary_." depending on values of the audio and video properties on the constraints object.

2020-11-04 14:21 UTC, eric-therond-sonarsource commented on eslint-bridge/src/rules/no-intrusive-permissions.ts
> +          context.options.includes('microphone') &&
I did an additional test if `constraints` object is passed to `getUserMedia` but `audio` property or `video` property is missing then the corresponding media will not be requested by the browser:

```
navigator.mediaDevices.getUserMedia({ video: true }) // Sensitive for camera only (if camera permission has been defined by the user in the parameter of this custom rule)
```

2020-11-04 16:28 UTC, andrea-guarino-sonarsource commented on eslint-bridge/src/rules/no-intrusive-permissions.ts
> +          context.options.includes('microphone') &&
ok thanks! I will apply those changes!

2020-11-05 14:39 UTC, guillaume-dequenne-sonarsource approved these changes
LGTM

2020-11-06 10:37 UTC, merged