RSPEC-5734 Allowing browsers to sniff MIME types is security-sensitive
SonarSource/SonarJS pull request #2303
Opened 2020-11-04 12:13 UTC by yassin-kammoun-sonarsource

Fixes #1953

2020-11-04 23:20 UTC, andrey-tyukin-sonarsource requested changes
Looks very good!

I think it might be advantageous that both the `findPropertyWithNameXValueY` as well as the batch of tests can be parametrized and kept in one place. The unit-tests in particular seem somewhat repetitive.

Also, it was not entirely clear to me why the expected issues for an example of S57**4**3 were updated, whereas there is no mention of S57**3**4; I'd appreciate a comment here.

2020-11-04 23:20 UTC, andrey-tyukin-sonarsource commented on its/ruling/src/test/expected/js/javascript-test-sources/javascript-S105.json
> +'javascript-test-sources:src/file-for-rules/S5743.js':[
I'm probably confusing something.

Could you please briefly comment why there are so many `S5743` mentions in the updated expected issues?

Please double-check that it's not some kind of confusion between

```
S5743
S5734
```

It seems that it suddenly found something about allowing DNS prefetching, but I somehow don't quite understand why it did that now.

2020-11-04 23:20 UTC, andrey-tyukin-sonarsource commented on javascript-checks/src/main/java/org/sonar/javascript/checks/NoSniffCheck.java
> +@Rule(key = "S5734")
This one is the mime-sniff, ending with 34. This looks fine (no questions here).

2020-11-05 08:36 UTC, yassin-kammoun-sonarsource commented on its/ruling/src/test/expected/js/javascript-test-sources/javascript-S105.json
> +'javascript-test-sources:src/file-for-rules/S5743.js':[
Yes, this was particularly annoying to deal with. It is actually related to people working MMF-1974. They are actually adding files in [javascript-test-sources](https://github.com/SonarSource/javascript-test-sources) that are used in integration tests. As long as the updated expected issues from their respective PRs are not merged to the master branch, other PRs can never be green at the same time.

It was probably a bad idea to take ahead and include those changes in this PR.

2020-11-05 08:45 UTC, yassin-kammoun-sonarsource commented on its/ruling/src/test/expected/js/javascript-test-sources/javascript-S105.json
> +'javascript-test-sources:src/file-for-rules/S5743.js':[
I will drop b0b62c7.

2020-11-05 09:56 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/tests/rules/no-sniff.test.ts
> +        module.exports = function (foo) { // Not app
Sorry, it's not different. I guess I duplicated the test by accident.

2020-11-05 10:01 UTC, yassin-kammoun-sonarsource commented on javascript-checks/src/main/java/org/sonar/javascript/checks/NoSniffCheck.java
> +@Rule(key = "S5734")
I should probably rename the rule to `no-mime-sniff` to emphasise that it's about MIME sniffing.

2020-11-05 10:22 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/rules/no-sniff.ts
> +function findFalseNoSniffPropertyFromHelmet(
Indeed, there are several rules that basically check some property's value when invoking a middleware constructor, like `helmet` in that particular case. However, sensible settings can be passed not only on constructor invocations but also on method calls with the very same middleware, i.e., either `helmet(settings)` or `helmet.method(settings)`. And these settings may not necessarily be a pair of property and value, but a more elaborate object expression. Therefore, I think we should avoid extracting anything here.

2020-11-05 10:22 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/tests/rules/no-sniff.test.ts
> +        module.exports = function (foo) {
The situation is somehow similar to the one above. One could definitely abstract further and provide parameterizable test suites for this MMF. But again, this is possible only if all rules assert a pair of property and value, which is not always the case. There are indeed rules that require the assertion of object expressions.

2020-11-05 10:42 UTC, andrey-tyukin-sonarsource approved these changes
LGTM

2020-11-05 10:51 UTC, merged