Migrate S3798 to eslint frontend
SonarSource/SonarJS pull request #2357
Opened 2020-11-17 13:21 UTC by guillaume-dequenne-sonarsource

Fixes #1871

2020-11-19 15:12 UTC, andrea-guarino-sonarsource reviewed
on implementation side, LGTM. However I would like to hear the opinion from someone of JS bubble (cc @saberduck) regarding the introduction of those new properties to setup environment and globals.

2020-11-19 15:12 UTC, andrea-guarino-sonarsource commented on its/ruling/src/test/expected/js/angular.js/javascript-S3798.json
> +6,
just an idea: maybe we can avoid raising on assignments having `require('foo')` as rhs. wdyt?
It could be treated in a separate tickets in any way

2020-11-20 13:14 UTC, guillaume-dequenne-sonarsource commented on its/ruling/src/test/expected/js/angular.js/javascript-S3798.json
> +6,
I created https://github.com/SonarSource/SonarJS/issues/2366 to fix it (and maybe we can identify some other cases that we can improve on Peach in the meantime), I guess it's indeed not urgent as the previous implementation was already raising issues in such cases.

2020-11-20 14:30 UTC, saberduck requested changes
overall approach looks good, but I made some comments to improve implementation

2020-11-20 14:30 UTC, saberduck commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBridgeServer.java
>    void initLinter(Rule[] rules) throws IOException;
it seems that there is only single usage of this method in tests. Instead of overload we can drop it and have only one signature with environments.

2020-11-20 14:30 UTC, saberduck commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBridgeServer.java
> +  void initLinter(Rule[] rules, String[] environments, String[] globals) throws IOException;
I would use `List` instead of array. Collections should be preferred before arrays when possible. (I know that rules used array before, but I think it's a mistake, so this is a chance to fix it).

2020-11-20 14:30 UTC, saberduck commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImpl.java
> +    Rule[] rules;
you can also use `List` here, GSON will handle it

2020-11-20 14:30 UTC, saberduck commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/TypeScriptSensor.java
> +    String[] environments = context.config().getStringArray(ENVIRONMENTS_PROPERTY_KEY);
it seems that this initialization could be pulled up to the superclass and shared between sensors

2020-11-20 16:55 UTC, saberduck approved these changes

2020-11-20 16:55 UTC, merged