Migrate S4165 (Redundant Assignments) to eslint implementation
SonarSource/SonarJS pull request #2365
Opened 2020-11-20 08:40 UTC by andrea-guarino-sonarsource

Fixes #2332

2020-11-23 16:43 UTC, guillaume-dequenne-sonarsource requested changes
There seems to be a potentially problematic FP which I'm not sure to understand the exact root cause of. 
As I'm still trying to understand the overall implementation, I let you have a look at it as well as the other minor comments I had so far.

2020-11-24 10:32 UTC, andrea-guarino-sonarsource commented on its/ruling/src/test/expected/js/p5.js/javascript-S4165.json
> +719,
Indeed, I forgot to update `assignedValuesMap` inside `checkSegment` function. 
Thanks!

2020-11-24 10:32 UTC, andrea-guarino-sonarsource commented on its/ruling/src/test/expected/js/jshint/javascript-S4165.json
> +17,
I decided to exclude those kind of issues, thanks!

2020-11-24 10:35 UTC, andrea-guarino-sonarsource commented on eslint-bridge/src/rules/no-redundant-assignments.ts
> +  `Review this useless assignment: "${name}" already holds the assigned value along all execution paths.`;
good point! I think we use `redundant`

2020-11-24 10:36 UTC, andrea-guarino-sonarsource commented on javascript-checks/src/main/java/org/sonar/javascript/checks/RedundantAssignmentCheck.java
>  @JavaScriptRule
Indeed, I forgot to activate it for TS!

2020-11-26 12:20 UTC, guillaume-dequenne-sonarsource approved these changes
I think there is a small bug in `getVariableFromIdentifier` that somehow doesn't impact tests. Other than that, LGTM.

2020-11-26 13:05 UTC, andrea-guarino-sonarsource commented on eslint-bridge/src/rules/reachingDefinitions.ts
> +    variable = scope.variables.find(value => value.name === identifier.name);
indeed, it wouldn't resolve variables defined in an outer scope. I will add a UT for it! Thanks!

2020-11-26 15:42 UTC, merged