Cherry-pick S1848 from Sonar Way Recommended into Sonar Way
SonarSource/SonarJS pull request #2540
Opened 2021-04-01 13:08 UTC by yassin-kammoun-sonarsource

Fixes #2524

2021-04-07 10:41 UTC, saberduck requested changes
condition about test code should come from Java API. If you don't want to implement that, I would prefer that we remove the condition for the time being.

2021-04-07 10:41 UTC, saberduck commented on eslint-bridge/src/rules/constructor-for-side-effects.ts
> +function isTestCode(context: Rule.RuleContext) {
I don't like to have this logic in the rule itself. There is `org.sonar.api.batch.fs.InputFile#type` which should determine whether the file is test file or not. We would need a new mechanism to have this information available in the context.

2021-04-07 10:41 UTC, saberduck commented on javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S1848.html
> +<p>Immediately dropped new objects inside <code>try</code>-statements are ignored.</p>
doesn't mention the test code part, is it somewhere else?

2021-04-07 14:24 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/rules/constructor-for-side-effects.ts
> +function isTestCode(context: Rule.RuleContext) {
As discussed, I will revert the workaround to detect test code. I created a ticket for making available file type information in the rule context. Also, I created another ticket to properly ignore issues raised by this rule on test code while using the aforementioned mechanism.

2021-04-07 14:24 UTC, yassin-kammoun-sonarsource commented on javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S1848.html
> +<p>Immediately dropped new objects inside <code>try</code>-statements are ignored.</p>
Irrelevant for now.

2021-04-08 09:22 UTC, saberduck approved these changes

2021-04-08 09:22 UTC, merged