Support syntax highlighting for Vue.js Single File Components templates
SonarSource/SonarJS pull request #2669
Opened 2021-06-14 14:47 UTC by yassin-kammoun-sonarsource

Fixes #2668

2021-06-15 11:48 UTC, yassin-kammoun-sonarsource commented
I forgot to mention that SonarQube Web API doesn't expose any endpoints from which one could fetch data about highlighting. As a consequence, it turned out to be impossible to write an integration test for that feature. Still, I ran locally an analysis on the [directus](https://github.com/directus/directus) project and the highlighting of `.vue` files was nice.

2021-06-16 10:02 UTC, vilchik-elena requested changes

2021-06-16 10:02 UTC, vilchik-elena commented on eslint-bridge/src/runner/symbol-highlighter.ts
> +              declaration: location(openHtmlTagsStack.pop()!.loc),
it will fail if input is not consistent (which we can't guarantee):
```
<template>
</p>
</template>

```

2021-06-16 10:02 UTC, vilchik-elena commented on eslint-bridge/tests/runner/symbol-highlighter.test.ts
> +  <template>
I would say just 2 levels of nested pairs would be enough

2021-06-16 13:23 UTC, vilchik-elena approved these changes

2021-06-16 13:23 UTC, merged