S5860: Names of regular expressions named groups should be used
SonarSource/SonarJS pull request #2722
Opened 2021-07-29 15:45 UTC by yassin-kammoun-sonarsource

Fixes #2693

2021-07-30 13:46 UTC, vilchik-elena requested changes

2021-07-30 13:46 UTC, vilchik-elena commented on eslint-bridge/src/rules/unused-named-groups.ts
> +      'Literal[regex]:exit': (literal: estree.Literal) => {
we should update `regex-rule-template` with this `[regex]` flag

2021-07-30 13:46 UTC, vilchik-elena commented on eslint-bridge/src/rules/unused-named-groups.ts
> +        intellisense.collectKnowledge(callExpr);
we are not considering when string is used in `str.match`, `str.search`. I think you should somehow duplicate here the logic from `checkCallExpression` in `regex-rule-template`. That way you will support something like `str.match("(?<name>John)")`

If doing this I would also drop condition on line 316

2021-07-30 13:46 UTC, vilchik-elena commented on eslint-bridge/src/rules/unused-named-groups.ts
> +      for (const def of variable.defs) {
I was doing similar thing, and using `getUniqueWriteUsage` from utils for it

2021-07-30 13:46 UTC, vilchik-elena commented on eslint-bridge/src/rules/unused-named-groups.ts
> +        group.used ||= names.has(group.name) || indexes.has(group.index);
more readable if split into 2 `||=` statements

2021-07-30 13:46 UTC, vilchik-elena commented on eslint-bridge/src/rules/unused-named-groups.ts
> +  const pattern = intellisense.resolve(matcher);
call it `regex` to be consistent with the rest of code

2021-07-30 13:46 UTC, vilchik-elena commented on eslint-bridge/src/rules/unused-named-groups.ts
> +  if (pattern && property.type === 'Identifier' && !computed) {
you already checked `computed` in visitor method

2021-07-30 13:46 UTC, vilchik-elena commented on eslint-bridge/src/rules/unused-named-groups.ts
> +    if (
these lines are duplicated with `extractGroupNameFromMatchMatcher`

2021-07-30 13:46 UTC, vilchik-elena commented on eslint-bridge/src/rules/unused-named-groups.ts
> +    switch (property.name) {
I would move this switch into one function `extractGroupName` and avoid having those 2 other `extract...` functions

2021-07-30 13:46 UTC, vilchik-elena commented on eslint-bridge/src/rules/unused-named-groups.ts
> +            `There is no group named '${name}' in the regular expression.`,
message should be action-oriented. E.g. `Make sure group named '${name}' exists in the regular expression.`

2021-07-30 13:53 UTC, vilchik-elena commented on eslint-bridge/tests/rules/unused-named-groups.test.ts
> +        const pattern = /(?<foo>\\w)/;
How about reporting here? There is name but index is used

2021-07-30 14:03 UTC, vilchik-elena requested changes

2021-08-02 07:49 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/tests/rules/unused-named-groups.test.ts
> +      code: `/(?<foo>\\w)/`,
It's not weird since the regular expression includes a named capturing group that is never used. Regular expressions that are never matched are still considered by the rule. For example, we would also raise an issue for:

```typescript
const pattern = /(?<foo>\w)/; // Noncompliant: unused 'foo'
if ('str'.test(pattern)) {
  // ...
}
```

The named group is useless regardless of the pattern being tested. In a sense, the pattern-matcher logic with `RegExp.prototype.match()` just helps to kill the noise if a group is used. The same applies with `String.prototype.replace()`.

2021-08-02 07:57 UTC, vilchik-elena commented on eslint-bridge/tests/rules/unused-named-groups.test.ts
> +      code: `/(?<foo>\\w)/`,
what is pattern is exported and used in another file?

2021-08-02 08:34 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/rules/unused-named-groups.ts
> +            `There is no group named '${name}' in the regular expression.`,
Are you sure you what to change the message to that ? The current one comes from the Java implementation, and the one you are suggesting sounds like a hotspot message, i.e. `Make sure that something is XXX`.

2021-08-02 08:40 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/tests/rules/unused-named-groups.test.ts
> +        const pattern = /(?<foo>\\w)/;
Nice catch! I did felt I forgot to implement something, and you found it for me.

2021-08-02 08:48 UTC, vilchik-elena commented on eslint-bridge/src/rules/unused-named-groups.ts
> +            `There is no group named '${name}' in the regular expression.`,
ok then, let's be consistent with Java :)

2021-08-02 10:22 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/tests/rules/unused-named-groups.test.ts
> +      code: `/(?<foo>\\w)/`,
Indeed, this leaves the door open for many false-positives, which is a problem. To kill the noise, and as agreed, we will change the strategy: unused group issues will be only reported for patterns that are actually matched.

A matched pattern here refers to a pattern that is used with the following APIs:

- `RegExp.prototype.match()`
- `RegExp.prototype.matchAll()`
- `RegExp.prototype.exec()`
- `String.prototype.replace()`
- `String.prototype.replaceAll()`

2021-08-02 11:54 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/rules/unused-named-groups.ts
> +        intellisense.collectKnowledge(callExpr);
@vilchik-elena  Do you know why we need the if-statement at line 105 ?

https://github.com/SonarSource/SonarJS/blob/8c13aaf2d0d4769a888e18f44713bdf464ff6d18/eslint-bridge/src/rules/regex-rule-template.ts#L101-L111

I am asking because `isStringRegexMethodCall` checks whether the first argument is a string at line 130

https://github.com/SonarSource/SonarJS/blob/8c13aaf2d0d4769a888e18f44713bdf464ff6d18/eslint-bridge/src/rules/regex-rule-template.ts#L122-L132

If `isStringRegexMethodCall` returns true, then we know for a fact that the argument can't possibly be a regular expression literal or a regular expression object, right ?

And it seems, that we never take the then-branch at line 106 according to https://next.sonarqube.com/sonarqube/code?id=org.sonarsource.javascript%3Ajavascript&selected=org.sonarsource.javascript%3Ajavascript%3Aeslint-bridge%2Fsrc%2Frules%2Fregex-rule-template.ts&line=106

2021-08-03 10:28 UTC, vilchik-elena requested changes

2021-08-03 10:28 UTC, vilchik-elena commented on eslint-bridge/src/rules/unused-named-groups.ts
> +      const value = getUniqueWriteUsage(this.context, variable.name);
there will be SOF for 
```
        let pattern;
        pattern = pattern;
        const matched = 'str'.matchAll(pattern);
```

I am not sure how to fix it though :(

2021-08-03 10:49 UTC, vilchik-elena requested changes

2021-08-03 10:49 UTC, vilchik-elena commented on eslint-bridge/src/rules/unused-named-groups.ts
> +            `Directly use the names instead of their group number.`,
`Directly use the group names instead of their numbers.`

2021-08-03 11:43 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/rules/unused-named-groups.ts
> +      const value = getUniqueWriteUsage(this.context, variable.name);
Nice catch !

2021-08-03 12:57 UTC, vilchik-elena approved these changes

2021-08-03 12:58 UTC, merged