FP S1128: ignore unused imported symbols denoting JSX factories
SonarSource/SonarJS pull request #2741
Opened 2021-08-05 11:21 UTC by yassin-kammoun-sonarsource

Fixes #2701

2021-08-06 11:17 UTC, vilchik-elena requested changes

2021-08-06 11:17 UTC, vilchik-elena commented on eslint-bridge/tests/rules/unused-import.test.ts
> +        import { h } from 'jsxlib';
it does not matter from which lib it's imported, right? (in the docs it's `preact`)

2021-08-06 11:17 UTC, vilchik-elena commented on eslint-bridge/tests/rules/unused-import.test.ts
> +        import { h } from 'jsxlib';
let's add test to show that we report on `h` when jsxFactory is not defined (or we can use simply js project)

2021-08-06 11:17 UTC, vilchik-elena commented on eslint-bridge/tests/rules/unused-import.test.ts
> +            return <div>Hello, world!</div>
I am not sure about JSX in the code here, on one side we imitate real code but then it's not clear from the test that we don't care about jsx presence. How about having both?)

2021-08-06 11:17 UTC, vilchik-elena commented on eslint-bridge/src/rules/unused-import.ts
> +        return compilerOptions.jsxFactory;
let's also support this property https://www.typescriptlang.org/tsconfig#jsxFragmentFactory (ticket and PR title to be updated then)

2021-08-06 12:35 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/tests/rules/unused-import.test.ts
> +        import { h } from 'jsxlib';
Indeed, it doesn't matter. I will rename the lib to avoid the confusion.

2021-08-09 06:58 UTC, vilchik-elena approved these changes

2021-08-09 06:59 UTC, merged