Support wildcards for coverage report paths
SonarSource/SonarJS pull request #2742
Opened 2021-08-05 14:19 UTC by yassin-kammoun-sonarsource

Fixes #578

2021-08-06 10:51 UTC, vilchik-elena requested changes

2021-08-06 10:51 UTC, vilchik-elena commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/lcov/DirectoryScanner.java
> +// Taken from https://github.com/SonarSource/sonar-python/blob/7a683a8da47ed8db51378fbc6c50a76d98b45097/sonar-python-plugin/src/main/java/org/sonar/plugins/python/DirectoryScanner.java
yeah, we should definitely move it into commons

2021-08-06 10:51 UTC, vilchik-elena commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/lcov/CoverageSensor.java
> +      DirectoryScanner scanner = new DirectoryScanner(baseDir, WildcardPattern.create(reportPath));
how about passing `reportPath` directly to constructor to hide this `WildcardPattern` usage?

2021-08-06 10:51 UTC, vilchik-elena commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/lcov/DirectoryScanner.java
> +public class DirectoryScanner {
I would call this class `PatternDirectoryScanner`

2021-08-06 10:51 UTC, vilchik-elena commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/lcov/DirectoryScanner.java
> +  public List<File> getIncludedFiles() {
`getMatchingFiles`

2021-08-06 10:51 UTC, vilchik-elena commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/lcov/CoverageSensor.java
> +          LOG.debug("No LCOV files were found using pattern {}", reportPath);
I think it should be `INFO`

2021-08-06 10:51 UTC, vilchik-elena commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/lcov/CoverageSensor.java
> +      LOG.debug("Using pattern '{}' to resolve LCOV files", reportPath);
how about drop `pattern` from this message to not confuse users not using patterns?

2021-08-06 10:51 UTC, vilchik-elena commented on sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/lcov/CoverageSensorTest.java
> +    settings.setProperty(JavaScriptPlugin.LCOV_REPORT_PATHS, "**/reports/*.lcov");
it's not clear which reports should match

2021-08-06 11:35 UTC, yassin-kammoun-sonarsource commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/lcov/DirectoryScanner.java
> +public class DirectoryScanner {
Agreed

2021-08-06 11:35 UTC, yassin-kammoun-sonarsource commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/lcov/DirectoryScanner.java
> +  public List<File> getIncludedFiles() {
Agreed

2021-08-06 11:40 UTC, yassin-kammoun-sonarsource commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/lcov/CoverageSensor.java
> +      DirectoryScanner scanner = new DirectoryScanner(baseDir, WildcardPattern.create(reportPath));
Agreed

2021-08-09 10:10 UTC, vilchik-elena requested changes

2021-08-09 10:10 UTC, vilchik-elena commented on sonar-javascript-plugin/src/test/resources/coverage/wildcard/nested/report.lcov
> +SF:tests/file1.js
let's simplify these 2 reports as much as possible (I think `DA:2,1` is enough)

2021-08-09 10:10 UTC, vilchik-elena commented on sonar-javascript-plugin/src/test/resources/coverage/wildcard/report.lcov
> +SF:deep/nested/dir/js/file1.js
why having this long path?

2021-08-09 10:10 UTC, vilchik-elena commented on sonar-javascript-plugin/src/test/resources/coverage/wildcard/report.lcov
> +SF:file1.js
why having another file in the report to prove that it's imported?

2021-08-09 11:34 UTC, vilchik-elena approved these changes

2021-08-09 12:03 UTC, merged