Preserve string literals inside JSX constructs on CPD computation
SonarSource/SonarJS pull request #2747
Opened 2021-08-10 08:55 UTC by yassin-kammoun-sonarsource

Fixes #2515

2021-08-10 10:17 UTC, vilchik-elena requested changes

2021-08-10 10:17 UTC, vilchik-elena commented on eslint-bridge/tests/runner/cpd.test.ts
> +      <baz {..."jkl"} />
how about `{...getAttributes("jkl")}` to test nested literal and make example more realistic

2021-08-10 10:17 UTC, vilchik-elena commented on eslint-bridge/src/runner/cpd.ts
> +  visit(sourceCode, (node: estree.Node) => {
I would extract this `visit` call into another function

2021-08-10 10:17 UTC, vilchik-elena commented on eslint-bridge/tests/runner/cpd.test.ts
> +    <foo bar="abc">
tbh I would keep only this literal, and replace others in this example with the placeholder as it's a plain JS in fact and could refactored. WDYT?

2021-08-10 11:00 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/tests/runner/cpd.test.ts
> +    <foo bar="abc">
Not sure it's worth the effort. KISS.

2021-08-10 11:12 UTC, vilchik-elena commented on eslint-bridge/tests/runner/cpd.test.ts
> +    <foo bar="abc">
but it will be simplier IMO, you will need to exclude only JSXAttribute literal

2021-08-10 11:27 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/tests/runner/cpd.test.ts
> +    <foo bar="abc">
Ah, I misunderstood you. I thought you were talking about refactoring the snippet of the unit test since you were highlighting it.

I think it makes sense. I will change that.

2021-08-10 14:57 UTC, vilchik-elena requested changes

2021-08-10 14:57 UTC, vilchik-elena commented on eslint-bridge/src/runner/cpd.ts
> +      tokens.push(...sourceCode.getTokens(node));
we should only push tokens of `node.value` if it has `Literal` type, otherwise this will be processed incorrectly: `<foo attr={'str'}/>`

2021-08-10 14:57 UTC, vilchik-elena commented on eslint-bridge/tests/runner/cpd.test.ts
> +    <foo bar="abc">
not done

2021-08-11 10:11 UTC, vilchik-elena approved these changes

2021-08-11 10:12 UTC, merged