WhiteSource scan for LTS branch
SonarSource/SonarJS pull request #2906
Opened 2021-12-03 21:25 UTC by saberduck

2022-02-11 16:00 UTC, vilchik-elena commented
@saberduck can we close this PR?

2022-03-30 20:48 UTC, saberduck commented
@vilchik-elena yes, we do. let's discuss tomorrow how to fix this :)

2022-03-31 12:46 UTC, vilchik-elena requested changes
Will this CI run daily?

2022-03-31 12:46 UTC, vilchik-elena commented on .cirrus.yml
> +  NPMRC: ENCRYPTED[!ef57edd224eb5867d50bdaa3c8570f8efb944aea8f4edbdab6be2a14355bf8257718da0a84e8f6fa3aa028a67de9d921!]
why we need authorization to read from repox?

2022-03-31 14:04 UTC, saberduck commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/EslintBridgeIntegrationTest.java
> +    assertThat(metrics.get("nosonarLines").getAsJsonArray()).containsExactly(new JsonPrimitive(3));
no sonar is needed in sonarlint

2022-03-31 14:06 UTC, saberduck commented on eslint-bridge/yarn.lock
> +eslint-plugin-sonarjs@0.7.1-102:
not sure, I will try revert

2022-03-31 14:06 UTC, saberduck commented on .cirrus.yml
> -    - yarn config set registry "${ARTIFACTORY_URL}/api/npm/npm"
no idea, but it works?

2022-03-31 14:07 UTC, saberduck commented on .cirrus.yml
> +  NPMRC: ENCRYPTED[!ef57edd224eb5867d50bdaa3c8570f8efb944aea8f4edbdab6be2a14355bf8257718da0a84e8f6fa3aa028a67de9d921!]
I believe this is just standard setup they apply to everything

2022-03-31 14:28 UTC, vilchik-elena approved these changes

2022-03-31 14:35 UTC, saberduck commented on eslint-bridge/yarn.lock
> +eslint-plugin-sonarjs@0.7.1-102:
this is to match what's in package.json

2022-03-31 14:35 UTC, merged