Add quickfix support - wip
SonarSource/SonarJS pull request #2943
Opened 2022-01-31 22:49 UTC by saberduck

Fixes #

2022-02-03 09:31 UTC, yassin-kammoun-sonarsource requested changes
Nice work overall! I left minor suggestions here and there as well as a couple of questions. Also, we are not handling the extraction and translation of ESLint suggestions to quick fixes.

2022-02-03 09:31 UTC, yassin-kammoun-sonarsource commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/AnalysisProcessor.java
> +      LOG.debug("Adding quickfix for issue line: {} rule: {}", issue.line, issue.ruleId);
```suggestion
      LOG.debug("Adding quick fix for issue {} at line {}", issue.ruleId, issue.line);
```

2022-02-03 09:31 UTC, yassin-kammoun-sonarsource commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/SonarLintTest.java
> +
Not sure we need to, but still asking just in case: should we have another unit test for a SonarLint version which doesn't support quick fixes ?

2022-02-03 09:31 UTC, yassin-kammoun-sonarsource commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/AnalysisProcessor.java
> +        .message(qf.message != null ? qf.message : "Fix this");
Is this ternary expression here because an ESLint suggestion has an optional message id ?

2022-02-03 09:31 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/analyzer.ts
> +  text: string;
We can move `QuickFix` and `QuickFixEdit` definitions into `quickfix.ts`, and maybe document why a quick fix's message could be undefined.

2022-02-03 09:31 UTC, yassin-kammoun-sonarsource commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBridgeServer.java
> +
```suggestion
```

2022-02-03 09:42 UTC, saberduck commented on eslint-bridge/src/quickfix.ts
> +const rulesWithQuickFix = new Set(['no-extra-semi']);
yes, I want to have control which rules we enable

2022-02-03 09:43 UTC, saberduck commented on eslint-bridge/src/linter.ts
> +  if (eslintIssue.fix) {
I think it will be better to do that in another PR with the rule which uses suggestions

2022-02-03 16:41 UTC, saberduck commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/SonarLintTest.java
> +
it was added as unit test in `QuickFixSupport`

2022-02-03 16:42 UTC, saberduck commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/AnalysisProcessor.java
> +        .message(qf.message != null ? qf.message : "Fix this");
yes, suggestions come with messages while fix doesn't. You can consider this to be temporary, perhaps we will adjust the message per rule key.

2022-02-03 16:49 UTC, saberduck commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/AnalysisProcessor.java
> +        .message(qf.message != null ? qf.message : "Fix this");
in fact, I decided that it's going to be better to provide the message on JS side and remove the ternary

2022-02-03 16:50 UTC, saberduck commented on eslint-bridge/src/analyzer.ts
> +  text: string;
I moved the types to `quickfix.ts` . I made the `message` not optional and removed the ternary on Java side. The message is now hardcoded on the JS side.

2022-02-04 07:56 UTC, yassin-kammoun-sonarsource approved these changes
LGTM. Just a minor thing to change, and we are good to merge.

2022-02-04 07:56 UTC, yassin-kammoun-sonarsource commented on sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/QuickFixSupportTest.java
> +  EslintBridgeServer.Issue issueWithQuickFix() {
We can make this method `static`.

2022-02-04 08:46 UTC, merged