Introduce sonar.typescript.lcov.reportPaths as alias for sonar.javascript.lcov.reportPaths
SonarSource/SonarJS pull request #2958
Opened 2022-02-14 13:44 UTC by yassin-kammoun-sonarsource

Fixes #2938

2022-02-15 14:22 UTC, vilchik-elena requested changes

2022-02-15 14:22 UTC, vilchik-elena commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/lcov/CoverageSensor.java
> +      LOG.warn(String.format("Merging coverage reports from %s and %s.", JavaScriptPlugin.LCOV_REPORT_PATHS, JavaScriptPlugin.LCOV_REPORT_PATHS_ALIAS));
why warning? I would put `info`

2022-02-15 14:22 UTC, vilchik-elena commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/lcov/CoverageSensor.java
> +    if (context.config().hasKey(JavaScriptPlugin.LCOV_REPORT_PATHS) && context.config().hasKey(JavaScriptPlugin.LCOV_REPORT_PATHS_ALIAS)) {
I feel now it will not be redundant to log the used property even if only one is used. It might ease the debugging in future

2022-02-15 14:53 UTC, yassin-kammoun-sonarsource commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/lcov/CoverageSensor.java
> +    if (context.config().hasKey(JavaScriptPlugin.LCOV_REPORT_PATHS) && context.config().hasKey(JavaScriptPlugin.LCOV_REPORT_PATHS_ALIAS)) {
I am not convinced about logging which property is used. I mean, if we want to debug, all we need is the project configuration to know which property was set by the user. If we start logging that one particular property is used, why shouldn't we do the same for others ?

2022-02-15 14:56 UTC, vilchik-elena commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/lcov/CoverageSensor.java
> +    if (context.config().hasKey(JavaScriptPlugin.LCOV_REPORT_PATHS) && context.config().hasKey(JavaScriptPlugin.LCOV_REPORT_PATHS_ALIAS)) {
there are many sources of property values (UI, sonar-project.properties, CI config), so it might be not so easy to get actual config. As for other properties, we don't have aliases there :)
@saberduch WDYT?

2022-02-16 10:01 UTC, saberduck commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/lcov/CoverageSensor.java
> +    if (context.config().hasKey(JavaScriptPlugin.LCOV_REPORT_PATHS) && context.config().hasKey(JavaScriptPlugin.LCOV_REPORT_PATHS_ALIAS)) {
I think it's ok to log in `DEBUG` when property is used, it's really easier when someone posts the logs on community

2022-02-17 08:31 UTC, vilchik-elena approved these changes

2022-02-17 08:31 UTC, merged