Fix FP S3317 ('file-name-differ-from-class'): consider dot notation in filenames
SonarSource/SonarJS pull request #2963
Opened 2022-02-15 15:13 UTC by yassin-kammoun-sonarsource

Fixes #2855

2022-02-15 15:15 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/tests/rules/file-name-differ-from-class.test.ts
> +      filename: `${__dirname}${path.sep}MyClass.js`,
This test case was rewritten because `path.parse` is environment-dependant since it relies on `path.sep`.

2022-02-17 10:56 UTC, vilchik-elena requested changes
As discussed we should avoid reporting on cases like `MyClass.dev.js`

2022-02-17 14:54 UTC, vilchik-elena commented on eslint-bridge/tests/rules/file-name-differ-from-class.test.ts
> -    },
btw it was still worthy to keep this test case in invalid section

2022-02-17 14:58 UTC, vilchik-elena approved these changes

2022-02-17 15:27 UTC, merged