Improve S1172: Match the behaviour of TypeScript compiler for JS and enable S1172 for TS
SonarSource/SonarJS pull request #2964
Opened 2022-02-16 11:00 UTC by yassin-kammoun-sonarsource

Fixes #1832

Be careful not to squash commits.

2022-02-16 11:12 UTC, yassin-kammoun-sonarsource commented
Rule description's update: https://github.com/SonarSource/rspec/pull/827.

2022-02-17 08:45 UTC, vilchik-elena requested changes
I think we should migrate the rule to messageId or to comment based test :)

2022-02-17 08:45 UTC, vilchik-elena commented on eslint-bridge/src/rules/no-unused-function-argument.ts
> +        message: `Remove the unused function parameter "${param.name}".`,
I think we should change the message to `Remove the unused function parameter "${param.name}" or rename it to "_${param.name}" to make intention explicit.`

2022-02-17 08:45 UTC, vilchik-elena commented on eslint-bridge/tests/rules/no-unused-function-argument.test.ts
> +      errors: 2,
how about asserting messages to be sure we report the right variables?

2022-02-17 10:28 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/rules/no-unused-function-argument.ts
> +        message: `Remove the unused function parameter "${param.name}".`,
It's quite long, but I am fine with that change :)

2022-02-17 12:58 UTC, vilchik-elena approved these changes

2022-02-17 12:58 UTC, merged