Call setQuickFixAvailable for SQ
SonarSource/SonarJS pull request #2969
Opened 2022-02-18 15:07 UTC by saberduck

It seems this can't be easily tested, because SonarLint doesn't implement the API

2022-02-18 15:32 UTC, vilchik-elena commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/AnalysisProcessor.java
> +      newIssue.setQuickFixAvailable(true);
this API is available with SQ only, it's not the same condition as in `isQuickFixCompatible`

2022-02-18 15:35 UTC, vilchik-elena requested changes
Build is failing

2022-02-18 15:41 UTC, saberduck commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/AnalysisProcessor.java
> +      newIssue.setQuickFixAvailable(true);
that's just stupid 🤦  fixing it

2022-02-21 08:25 UTC, vilchik-elena approved these changes

2022-02-21 08:35 UTC, vilchik-elena commented
@saberduck I think we should add integration test for SQ with quick fix and run ITs on SQ[9.0] to make SC support more robust. WDYT?

2022-02-21 08:42 UTC, saberduck commented
> @saberduck I think we should add integration test for SQ with quick fix and run ITs on SQ[9.0] to make SC support more robust. WDYT?

OK, good idea. But maybe we should test LTS and not 9.0?

2022-02-21 09:23 UTC, vilchik-elena requested changes
As discussed we need ITs for QF on SQ LTS

2022-02-21 14:19 UTC, vilchik-elena approved these changes

2022-02-21 14:19 UTC, merged