Migrate S2681, S128, S3782, S3796, S1528, S1529, S3524 to messageId
SonarSource/SonarJS pull request #2985
Opened 2022-02-23 14:13 UTC by yassin-kammoun-sonarsource

2022-02-24 09:35 UTC, vilchik-elena requested changes

2022-02-24 09:35 UTC, vilchik-elena commented on eslint-bridge/src/rules/bitwise-operators.ts
> +        'Review this use of bitwise "{operator}" operator; conditional "{{intended}}" might have been intended.',
why only one set of curly braces?

2022-02-24 09:35 UTC, vilchik-elena commented on eslint-bridge/src/rules/no-unenclosed-multiline-block.ts
> +    messageId: 'onlyFirstStatement',
should be `onlyFirstLine`?

2022-02-25 07:58 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/rules/no-unenclosed-multiline-block.ts
> +    messageId: 'onlyFirstStatement',
I don't think so. It raises issues on the following pattern:

```javascript

if (condition) action1();
  action2();
```

2022-02-28 09:43 UTC, vilchik-elena commented
Closing PR as we realized that we don't have to migrate to message IDs

2022-02-28 09:43 UTC, closed without merging