Add quick fix for S1172: Unused function parameters should be removed
SonarSource/SonarJS pull request #3038
Opened 2022-03-14 11:10 UTC by yassin-kammoun-sonarsource

Fixes #3033

2022-03-14 14:13 UTC, vilchik-elena commented on eslint-bridge/src/rules/no-unused-function-argument.ts
> +  const funct = paramVariable.defs[0].node as TSESTree.FunctionLike;
why such name for variable?

2022-03-14 14:28 UTC, vilchik-elena requested changes

2022-03-14 14:28 UTC, vilchik-elena commented on eslint-bridge/src/rules/no-unused-function-argument.ts
> +      fix: fixer => fixer.replaceText(paramIdentifier, `_${paramVariable.name}`),
may be using `insertTextBefore` will be more efficient?

2022-03-14 14:28 UTC, vilchik-elena commented on eslint-bridge/src/rules/no-unused-function-argument.ts
> +  const funct = paramVariable.defs[0].node as TSESTree.FunctionLike;
why such name for variable?

2022-03-14 14:28 UTC, vilchik-elena commented on eslint-bridge/tests/rules/no-unused-function-argument.test.ts
> +    {
can we add unit test with parameter type to verify that type is also removed?

2022-03-14 14:28 UTC, vilchik-elena commented on eslint-bridge/src/rules/no-unused-function-argument.ts
> +          return fixer.remove(funct.params[paramIndex] as estree.Node);
what will happen with trailing comma?

2022-03-14 14:28 UTC, vilchik-elena commented on eslint-bridge/src/rules/no-unused-function-argument.ts
> +          return fixer.removeRange([start, end]);
this should be fine for trailing comma but can we add a test for it?

2022-03-14 15:01 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/rules/no-unused-function-argument.ts
> +  const funct = paramVariable.defs[0].node as TSESTree.FunctionLike;
`funct` for `function`, but the latter is a keyword.

2022-03-14 15:02 UTC, vilchik-elena commented on eslint-bridge/src/rules/no-unused-function-argument.ts
> +  const funct = paramVariable.defs[0].node as TSESTree.FunctionLike;
ah, indeed:)) it's just usually we use `fun` or `func`. I have never seen `funct`

2022-03-15 09:48 UTC, vilchik-elena requested changes
And same thing as with another PR, I think we should keep the trailing comma style

2022-03-15 09:48 UTC, vilchik-elena commented on eslint-bridge/src/rules/no-unused-function-argument.ts
> +          case 'FunctionDeclaration': {
this case and next one are very similar, can't we generalize the logic?

2022-03-15 09:48 UTC, vilchik-elena commented on eslint-bridge/src/rules/no-unused-function-argument.ts
> +      suggestRemoveParameter: 'Remove {{param}} (beware of call sites)',
I think we should wrap parameter names into quotes.

2022-03-15 09:48 UTC, vilchik-elena commented on eslint-bridge/src/rules/no-unused-function-argument.ts
> +            const token = context.getSourceCode().getTokenAfter(param);
theoretically there could be comma (`(a,) => foo()`)

2022-03-15 09:48 UTC, vilchik-elena commented on eslint-bridge/tests/rules/no-unused-function-argument.test.ts
> +          suggestions: [
I think you don't have to assert all suggestions and their messages. Assert only what matters for the case, otherwise it's hard to follow

2022-03-15 14:56 UTC, vilchik-elena requested changes

2022-03-15 14:56 UTC, vilchik-elena commented on eslint-bridge/src/rules/no-unused-function-argument.ts
> +        const closingParenthesis = context
this will not work for `a => foo()` :(

2022-03-15 14:56 UTC, vilchik-elena commented on eslint-bridge/src/rules/no-unused-function-argument.ts
> +        }
```suggestion
        const openingParenthesis = context
          .getSourceCode()
          .getTokenBefore(param);
        const closingParenthesis = context
          .getSourceCode()
          .getTokenAfter(param, token => token.value === ')');
        let [start, end] = param.range!;
        if (openingParenthesis && openingParenthesis.value === '(') {
          start = openingParenthesis.range[0];
          end = closingParenthesis!.range[1];
        }
```

2022-03-15 14:57 UTC, vilchik-elena commented on eslint-bridge/tests/rules/no-unused-function-argument.test.ts
> +              output: '( _a, ) => {}',
I see we can't remove this suggestion from assertion, but let's at least remove the messages to reduce some readablility noise

2022-03-17 10:06 UTC, vilchik-elena approved these changes

2022-03-17 10:36 UTC, merged