Add quick fix for S3415 ('inverted-assertion-arguments')
SonarSource/SonarJS pull request #3046
Opened 2022-03-16 10:45 UTC by yassin-kammoun-sonarsource

Fixes #3015

2022-03-16 10:47 UTC, yassin-kammoun-sonarsource commented
The newly added testing file should be dropped once #3047 is done, and the quick fix assertions should be moved to the comment-based test file.

2022-03-17 10:14 UTC, vilchik-elena requested changes

2022-03-17 10:14 UTC, vilchik-elena commented on eslint-bridge/tests/rules/inverted-assertion-arguments.test.ts
> +const ruleTester = new RuleTester({ parserOptions: { ecmaVersion: 2018, sourceType: 'module' } });
let's add comment that this rule is tested in another file and that here we just testing fixes.

2022-03-17 10:14 UTC, vilchik-elena commented on eslint-bridge/tests/rules/inverted-assertion-arguments.test.ts
> +    should.fail(42, aNumber);
tbh instead of testing different APIs, I would focus on more complex expressions (multiline, spaces)

2022-03-17 14:35 UTC, vilchik-elena approved these changes

2022-03-17 14:36 UTC, merged