Add quick fix for S4621 ('no-duplicate-in-composite')
SonarSource/SonarJS pull request #3061
Opened 2022-03-22 09:45 UTC by yassin-kammoun-sonarsource

Fixes #3027

2022-03-24 14:40 UTC, vilchik-elena requested changes
TBH I am not big fan of such solution based on full text replacement (and not on removal of duplicates), but indeed it's pretty straight-forward.

2022-03-24 14:40 UTC, vilchik-elena commented on eslint-bridge/src/rules/no-duplicate-in-composite.ts
> +            const suggest = getSuggestions(compositeType, duplicates.slice(1), context);
minor but I would move slicing logic inside of the function

2022-03-24 14:40 UTC, vilchik-elena commented on eslint-bridge/src/rules/no-duplicate-in-composite.ts
> +  if (firstToken?.value === '(' && lastToken?.value === ')') {
I don't see test for this

2022-03-24 15:10 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/rules/no-duplicate-in-composite.ts
> +  if (firstToken?.value === '(' && lastToken?.value === ')') {
https://github.com/SonarSource/SonarJS/blob/777bc114e0fca7a251be1fcafe01d1dc20a5e5d3/eslint-bridge/tests/rules/no-duplicate-in-composite.test.ts#L164-L198

2022-03-24 20:24 UTC, vilchik-elena requested changes

2022-03-24 20:24 UTC, vilchik-elena commented on eslint-bridge/src/rules/no-duplicate-in-composite.ts
> +  if (firstToken?.value === '(' && lastToken?.value === ')') {
hm... here first and last parentheses are not a pair, that's why I didn't get that it covers the condition
Then for `(number | string) & (number | string) & Foo` we gonna get `number | string & Foo` which is wrong.

2022-03-25 12:57 UTC, vilchik-elena approved these changes

2022-03-25 13:26 UTC, merged