Add quick fix for S4138 ('prefer-for-of')
SonarSource/SonarJS pull request #3062
Opened 2022-03-22 12:49 UTC by yassin-kammoun-sonarsource

Fixes #3023

2022-03-22 13:42 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/linter.ts
> +
Moved rule decorating after defining TypeScript ESLint rules.

2022-03-22 16:41 UTC, yassin-kammoun-sonarsource commented on its/ruling/src/test/expected/ts/console/typescript-S2814.json
> -}
The disappearance of this issue highlights an interesting bug that we missed when first introducing a decorator for S2814 ('no-redeclare'). The decorated rule was actually never triggered, only the undecorated one was. Here is what happened:

1. ESLint 'no-redeclare' was first enabled
2. ESLint 'no-redeclare' was then decorated
3. TypeScript ESLint  'no-redeclare' overwrote everything

This remained unnoticed because the test suite was not using the analysis pipeline of eslint-bridge. Postponing when decoration occurs is a consequence of why this issue is no longer reported as the decorated rule is now triggered.

2022-03-24 14:22 UTC, vilchik-elena requested changes

2022-03-24 14:22 UTC, vilchik-elena commented on eslint-bridge/tests/rules/decorators/prefer-for-of-decorator.test.ts
> +              output: `for (const element of arr) console.log(element);`,
what if variable with name `element` already exists?

2022-03-24 14:25 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/tests/rules/decorators/prefer-for-of-decorator.test.ts
> +              output: `for (const element of arr) console.log(element);`,
Indeed, I wasn't sure what to do to prevent this problem: generating a random name, inserting a syntactically invalid placeholder, ...

Do you have any suggestions ?

2022-03-24 14:34 UTC, vilchik-elena commented on eslint-bridge/tests/rules/decorators/prefer-for-of-decorator.test.ts
> +              output: `for (const element of arr) console.log(element);`,
we can simply not provide the fix if name is occupied :)

2022-03-24 14:34 UTC, yassin-kammoun-sonarsource commented on its/ruling/src/test/expected/ts/console/typescript-S2814.json
> -}
What does "this problem" refer to here ?

2022-03-24 20:37 UTC, vilchik-elena requested changes

2022-03-24 20:38 UTC, vilchik-elena commented on eslint-bridge/src/linter.ts
> +
And how did you discover this bug?

2022-03-24 20:40 UTC, vilchik-elena commented on eslint-bridge/src/rules/decorators/prefer-for-of-decorator.ts
> +  return context.getScope().references.every(reference => reference.identifier.name !== element);
https://eslint.org/docs/developer-guide/scope-manager-interface#references

> The array of all references on this scope. This does not include references in child scopes.

2022-03-25 10:17 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/linter.ts
> +
Some tests were failing because the linter was trying to decorate a (TypeScript ESLint) rule that wasn't defined yet.

2022-03-25 10:54 UTC, vilchik-elena approved these changes

2022-03-25 10:54 UTC, merged