Update Stylelint to 14.6.1
SonarSource/SonarJS pull request #3089
Opened 2022-04-05 08:48 UTC by yassin-kammoun-sonarsource

Fixes #3088

2022-04-08 08:17 UTC, yassin-kammoun-sonarsource commented
Reminder: We will probably need to update the rule description depending on how the rule implementation evolves before merge.

2022-04-11 09:22 UTC, vilchik-elena requested changes

2022-04-11 09:22 UTC, vilchik-elena commented on eslint-bridge/src/rules/stylelint/function-calc-no-invalid.ts
> +      /* flag to report an invalid expression iff the calc argument has no other issues */
`iff`

2022-04-11 09:22 UTC, vilchik-elena commented on eslint-bridge/src/rules/stylelint/function-calc-no-invalid.ts
> +export const rule = stylelint.createPlugin(ruleName, function (_primaryOption, _secondaryOptions) {
what are these options parameters? can we drop them?

2022-04-11 09:22 UTC, vilchik-elena commented on eslint-bridge/src/rules/stylelint/function-calc-no-invalid.ts
> +      function complain(message: string) {
-> `report`?

2022-04-11 09:22 UTC, vilchik-elena commented on eslint-bridge/src/rules/stylelint/function-calc-no-invalid.ts
> +  return (root, result) => {
what is `result`?

2022-04-11 09:22 UTC, vilchik-elena commented on eslint-bridge/tests/rules/stylint/function-calc-no-invalid.test.ts
> +  invalid: [
add tests with multiple calc-s, nested and not

2022-04-11 09:22 UTC, vilchik-elena commented on eslint-bridge/src/rules/stylelint/function-calc-no-invalid.ts
> +        for (let index = 1; index < nodes.length; index += 2) {
wow, that looks dangerous, can we have more unit tests with various kind of expressions proving that this approach is reliable?

2022-04-11 10:13 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/tests/rules/stylint/function-calc-no-invalid.test.ts
> +      description: 'single expression',
Nope, written from scratch.

2022-04-11 10:15 UTC, yassin-kammoun-sonarsource commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/CssIssuesTest.java
> +      tuple("css:S4650", "css-issues-project:src/file1.css"),
I guess you missed the extended commit message: https://github.com/SonarSource/SonarJS/pull/3089/commits/cca7c782cc6a0853ede76a361d2c5b3c0b4a7fdc. Long story short, there has been a substantial amount of changes in the rule implementation.

2022-04-11 10:16 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/tests/StylelintRuleTester.ts
> +class StylelintRuleTester {
Nope, written from scratch.

2022-04-11 10:17 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/rules/stylelint/function-calc-no-invalid.ts
> +      /* flag to report an invalid expression iff the calc argument has no other issues */
https://en.wikipedia.org/wiki/If_and_only_if

2022-04-11 10:59 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/tests/StylelintRuleTester.ts
> +        expect(warnings[index].text).toBe(assertion.errors[index].message);
It kinda is, but that's actually what ESLint does if I am not wrong, and I can live with that :)

2022-04-11 11:00 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/tests/rules/stylint/function-calc-no-invalid.test.ts
> +      code: '.foo {width: calc(100%-80px);}',
No longer relevant since we decided to narrow the scope of the rule.

2022-04-11 11:03 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/rules/stylelint/function-calc-no-invalid.ts
> +export const rule = stylelint.createPlugin(ruleName, function (_primaryOption, _secondaryOptions) {
Forgot to drop them. They are relevant when a rule is configurable.

2022-04-11 11:11 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/rules/stylelint/function-calc-no-invalid.ts
> +  return (root, result) => {
It's not entirely clear from the documentation, but from what I understand, it's a lazy object that is passed along and used to store found issues.

2022-04-11 11:27 UTC, yassin-kammoun-sonarsource commented on its/plugin/projects/css-issues-project/src/file1.css
> +//color: pink;                                               /* S4668 | no-invalid-double-slash-comments */
I was not able to identify which commit caused that change.

2022-04-11 13:13 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/rules/stylelint/function-calc-no-invalid.ts
> +        for (let index = 1; index < nodes.length; index += 2) {
Added a more advanced test case which required partially rewriting the rule as it helped identify two major flaws.

2022-04-11 14:59 UTC, vilchik-elena requested changes

2022-04-11 14:59 UTC, vilchik-elena commented on eslint-bridge/src/rules/stylelint/function-calc-no-invalid.ts
> +          } else if (node.type === 'function' && !isCalcFunction(node)) {
when we need this condition?

2022-04-11 14:59 UTC, vilchik-elena commented on eslint-bridge/tests/StylelintRuleTester.ts
> +          text: expectedMessage,
these are actual, not expected

2022-04-11 14:59 UTC, vilchik-elena commented on eslint-bridge/tests/StylelintRuleTester.ts
> +          text: actualMessage,
and these are expected

2022-04-11 14:59 UTC, vilchik-elena commented on eslint-bridge/tests/StylelintRuleTester.ts
> +          expect(expectedMessage).toBe(actualMessage);
why our rule didn't report :D

2022-04-11 15:02 UTC, vilchik-elena commented on eslint-bridge/src/rules/stylelint/function-calc-no-invalid.ts
> +          } else if (node.type === 'function' && !isCalcFunction(node)) {
I see now from the commit comment, probably it deserves some mention in the code

2022-04-12 07:24 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/tests/StylelintRuleTester.ts
> +          expect(expectedMessage).toBe(actualMessage);
Because we are not using/importing chai.js -_-

2022-04-12 07:41 UTC, vilchik-elena commented on eslint-bridge/tests/rules/stylint/function-calc-no-invalid.test.ts
> +      errors: [{ text: `Fix this 'calc' expression` }, { text: 'Unexpected division by zero' }],
so let's be explicit about it and add this assertion:)

2022-04-12 08:48 UTC, vilchik-elena requested changes

2022-04-12 08:48 UTC, vilchik-elena commented on eslint-bridge/src/rules/stylelint/function-calc-no-invalid.ts
> +  missingOperator: 'Unexpected missing operator'
this one is not sonar-friendly

2022-04-12 08:48 UTC, vilchik-elena commented on eslint-bridge/src/rules/stylelint/function-calc-no-invalid.ts
>    divByZero: 'Unexpected division by zero',
this one is not sonar-friendly

2022-04-12 08:48 UTC, vilchik-elena commented on eslint-bridge/src/rules/stylelint/function-calc-no-invalid.ts
> +          } else if (isNotCalcFunction(node)) {
which other function it could be? I though it's about parenthesized expression

2022-04-12 09:04 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/rules/stylelint/function-calc-no-invalid.ts
> +  missingOperator: 'Unexpected missing operator'
`Fix this malformed 'calc' expression` ?

2022-04-12 09:23 UTC, vilchik-elena commented on eslint-bridge/src/rules/stylelint/function-calc-no-invalid.ts
>    divByZero: 'Unexpected division by zero',
LGTM

2022-04-12 09:23 UTC, vilchik-elena commented on eslint-bridge/src/rules/stylelint/function-calc-no-invalid.ts
> +  missingOperator: 'Unexpected missing operator'
LGTM

2022-04-12 10:19 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/package.json
> +    "postcss-html": "0.36.0",
postcss-syntax only works with postcss-html <= 0.36.0. The author of both libraries used to be the same person. postcss-html was then taken over by another contributor which introduced breaking changes that postcss-syntax can't deal with.

2022-04-12 11:32 UTC, vilchik-elena approved these changes

2022-04-12 11:33 UTC, merged