Improve S4653 ('unit-no-unknown'): Support ignoring any kind of unit
SonarSource/SonarJS pull request #3097
Opened 2022-04-08 07:35 UTC by yassin-kammoun-sonarsource

Fixes https://github.com/SonarSource/sonar-css/pull/367

2022-04-11 09:54 UTC, vilchik-elena requested changes
I didn't find any place describing why we need this parameter. Also why default should be `x`

2022-04-11 10:08 UTC, vilchik-elena commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/css/rules/UnitNoUnknown.java
> +    description = "Comma-separated list of \"units\" to consider as valid.",
should we mention that regex are supported?

2022-04-11 13:35 UTC, vilchik-elena commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/css/rules/UnitNoUnknown.java
>      // Used by GSON serialization
Ok, I see now that we use GSON when sending the request

2022-04-11 13:48 UTC, yassin-kammoun-sonarsource commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/css/rules/UnitNoUnknown.java
> +    description = "Comma-separated list of \"units\" to consider as valid.",
We should, similarly to what you suggested in the other PR.

2022-04-11 14:43 UTC, vilchik-elena commented
> Which parameter are you referring to?

The parameter you have added in this PR :)

2022-04-12 07:21 UTC, yassin-kammoun-sonarsource commented
Closing this PR as discussed.

2022-04-12 07:21 UTC, closed without merging