Create rule S4036: Searching OS commands in PATH is security-sensitive
SonarSource/SonarJS pull request #3148
Opened 2022-05-25 07:43 UTC by ilia-kebets-sonarsource

Fixes #2036

2022-05-27 08:56 UTC, ilia-kebets-sonarsource commented on its/sources/file-for-rules/tests/S4036.js
> +const cp = require('child_process');
This did not flag anything in the rulings. Also, the rule was flagged by other rulings, making this pointless. Should we remove it?

2022-05-27 09:43 UTC, yassin-kammoun-sonarsource requested changes

2022-05-27 09:43 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/rules/no-os-command-from-path.ts
> +          const sensitiveArg = findSensitiveArgument(node.arguments as Array<estree.Literal>);
```suggestion
          const sensitiveArg = findSensitiveArgument(node.arguments as estree.Literal[]);
```

2022-05-27 09:43 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/rules/no-os-command-from-path.ts
> +function findSensitiveArgument(functionArgs: Array<estree.Literal>) {
```suggestion
function findSensitiveArgument(functionArgs: estree.Literal[]) {
```

2022-05-27 09:43 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/rules/no-os-command-from-path.ts
> +  const pathArg = functionArgs[0]; // we know this for the SENSITIVE_METHODS
We could use `getValueOfExpression` from `utils-ast` on `functionArgs[0]` to support cases like:

```javascript
const { exec } = require('child_process');
const cmd = 'make';
exec(cmd);
```

The idea is to detect patterns when the argument of the sensitive function is an identifier rather than a literal.

2022-05-27 09:43 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/rules/no-os-command-from-path.ts
> +  });
```suggestion
  const startsWithRequiredPrefix = REQUIRED_PATH_PREFIXES.some(prefix => pathArg.value.startsWith(prefix));
```

2022-05-27 09:43 UTC, yassin-kammoun-sonarsource commented on its/sources/file-for-rules/tests/S4036.js
> +cp.exec('/usr/bin/file.exe'); // Compliant
Since we are raising issues on some local projects, there is no longer a need for this file.

2022-05-27 09:43 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/README.md
> +
Not sure if you wanted to further document the testing section.

2022-05-27 09:43 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/rules/no-os-command-from-path.ts
> +  const pathArg = functionArgs[0]; // we know this for the SENSITIVE_METHODS
And you could add a test case for that as well :)

2022-05-27 09:45 UTC, yassin-kammoun-sonarsource commented on its/sources/file-for-rules/tests/S4036.js
> +const cp = require('child_process');
Not sure why it wasn't flagged, but yes, let's just drop the file.

2022-05-30 07:49 UTC, yassin-kammoun-sonarsource requested changes

2022-05-30 07:49 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/rules/no-os-command-from-path.ts
> +      issue: 'Searching OS commands in PATH is security-sensitive.',
```suggestion
      issue: 'Make sure the "PATH" used to find this command includes only what you intend.',
```

2022-05-30 07:49 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/rules/no-os-command-from-path.ts
> +      issue: 'Searching OS commands in PATH is security-sensitive.',
For your information, the RSPEC describes somewhere the expected message for this hotspot (see S4036).

2022-05-30 07:49 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/rules/no-os-command-from-path.ts
> +          if (sensitiveArg != null) {
```suggestion
          if (sensitiveArg !== null) {
```

2022-05-30 07:49 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/tests/rules/fixtures/no-os-command-from-path.js
> +cp.exec('file.exe');  // Noncompliant {{Searching OS commands in PATH is security-sensitive.}}
```suggestion
cp.exec('file.exe');  // Noncompliant {{Make sure the "PATH" used to find this command includes only what you intend.}}
```

2022-05-30 08:29 UTC, yassin-kammoun-sonarsource approved these changes

2022-05-30 08:29 UTC, merged