Support filtering for comment-based unit tests
SonarSource/SonarJS pull request #3164
Opened 2022-06-07 12:01 UTC by ilia-kebets-sonarsource

Fixes #3162

2022-06-07 15:13 UTC, vilchik-elena requested changes
It does not seem to work for me, all rules are executed.

2022-06-07 15:13 UTC, vilchik-elena commented on eslint-bridge/README.md
> +- You can launch them using: `npm run ntest`
I don't think we should document this one. Why someone would want to run all comment-based tests?

2022-06-07 15:13 UTC, vilchik-elena commented on eslint-bridge/package.json
> +    "ntest": "npm test tests/rules/rule-test-launcher.test.ts",
I don't get reasoning behind this name `ntest`. It stands for `new test` but what is new about it? How about `rule-test`?

2022-06-07 15:31 UTC, ilia-kebets-sonarsource commented on eslint-bridge/package.json
> +    "ntest": "npm test tests/rules/rule-test-launcher.test.ts",
Yeah, I'm not so confident with this alias `ntest`. 
It filters out the comments-based tests from all unit tests. I'll ask Victor if he feels creative.

2022-06-07 15:46 UTC, ilia-kebets-sonarsource commented on eslint-bridge/package.json
> +    "ntest": "npm test tests/rules/rule-test-launcher.test.ts",
I propose `ctest` for "comment-based tests"

2022-06-07 20:01 UTC, vilchik-elena requested changes

2022-06-10 07:07 UTC, vilchik-elena approved these changes

2022-06-10 07:08 UTC, merged