fix tests on Windows
SonarSource/SonarJS pull request #3165
Opened 2022-06-07 13:35 UTC by victor-diez-sonarsource

basePath contained tilde path (C:\Users\VICTOR~1.DIE\AppData\...) instead of full path (C:/Users/victor.diez/AppData/...)

Using `baseDir.toRealPath()` fixes the issue, but to seems it actually checks FS

2022-06-07 14:19 UTC, vilchik-elena requested changes

2022-06-07 14:19 UTC, vilchik-elena commented on sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/TypeScriptSensorTest.java
> +    SensorContextTester ctx = SensorContextTester.create(baseDir.toRealPath());
Could you comment this line explaining why we need `toRealPath`?

2022-06-08 12:24 UTC, victor-diez-sonarsource commented on sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/TypeScriptSensorTest.java
> +    SensorContextTester ctx = SensorContextTester.create(baseDir.toRealPath());
done!

2022-06-10 06:49 UTC, vilchik-elena approved these changes

2022-06-10 06:50 UTC, merged