Add rule S4125: "typeof" expressions should only be compared to valid values
SonarSource/SonarJS pull request #3166
Opened 2022-06-07 14:47 UTC by ilia-kebets-sonarsource

Fixes #625

2022-06-08 10:02 UTC, ilia-kebets-sonarsource commented
Based on the [implementation](https://github.com/eslint/eslint/blob/f31216a90a6204ed1fd56547772376a10f5d3ebb/lib/rules/valid-typeof.js#L105), the fix covers the case when:
```javascript
typeof foo === undefined
```
is changed to
```javascript
typeof foo === 'undefined'
```

We can update the S4125 rspec quickfix parameter to [`partial`](https://github.com/SonarSource/rspec/blob/master/docs/metadata.adoc#quickfix-field). Although, I have not been able to trigger this quickfix on a debug repo with eslint. The rule was flagged, but the quickfix not proposed.

2022-06-10 06:56 UTC, vilchik-elena requested changes

2022-06-10 06:56 UTC, vilchik-elena commented on javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S4125.html
> +function someFunc(x: any): boolean {
I am not sure where this is coming from, but I don't think we should use type annotations as rule is enabled for JS

2022-06-10 06:56 UTC, vilchik-elena commented on javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S4125.json
> +  "quickfix": "unknown",
ESLint rule provides quick fixes for some cases (https://github.com/eslint/eslint/blob/21d647904dc30f9484b22acdd9243a6d0ecfba38/lib/rules/valid-typeof.js#L101), we should enable them. Let me know if you need help with that.

don't forget to update this metadata accordingly (here and in RSPEC repo)

2022-06-10 07:01 UTC, vilchik-elena commented on javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S4125.html
> +  <li> "undefined" </li>
There is a new [`BigInt`](https://developer.mozilla.org/en-US/docs/Glossary/BigInt) value

2022-06-10 07:06 UTC, vilchik-elena commented on javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S4125.json
> +  "quickfix": "unknown",
Ah, I see now that you checked that already.  On my side I didn't even manage to have that issue triggered at all (on `if (typeof bar !== undefined) {}`), which is weird as it's in unit test of this rule. I suggest we don't waste time here as anyway quick fix application is very limited.

2022-06-13 11:54 UTC, ilia-kebets-sonarsource commented on javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S4125.json
> +  "quickfix": "unknown",
ACK, leaving this to `unknown`.

2022-06-13 11:58 UTC, ilia-kebets-sonarsource commented
@vilchik-elena I have applied the changes in RSPEC: https://github.com/SonarSource/rspec/pull/1044

2022-06-13 12:14 UTC, vilchik-elena commented on javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S4125.html
> +function someFunc(x: any): boolean {
why did you resolve it? there is still old description here. You should merge the change on RSPEC and regenerate here.

2022-06-13 12:14 UTC, vilchik-elena requested changes
We need up to date description in this PR

2022-06-13 14:15 UTC, merged