Add rule S6443: React state setter function should not be called with its matching state variable
SonarSource/SonarJS pull request #3227
Opened 2022-07-13 13:23 UTC by victor-diez-sonarsource

Fixes #3218

2022-07-14 08:24 UTC, vilchik-elena requested changes
When requesting review check following:
* go through files in github PR to make sure nothing wrong is committed (like ruling projects change)
* make sure coverage is close to 100%
* make sure there are 0 issues on Next

2022-07-14 14:30 UTC, vilchik-elena requested changes

2022-07-14 14:30 UTC, vilchik-elena commented on eslint-bridge/src/rules/no-useless-react-setstate.ts
> +    const module = getModuleNameOfIdentifier(context, callExpr.callee.object as estree.Identifier);
it's not guaranteed that object has identifier type

2022-07-14 14:30 UTC, vilchik-elena commented on eslint-bridge/src/rules/no-useless-react-setstate.ts
> +    usesReactState = module?.value === 'react';
I would directly return here

2022-07-14 14:30 UTC, vilchik-elena commented on eslint-bridge/src/rules/no-useless-react-setstate.ts
> +          const ids = node.id as estree.ArrayPattern;
you only use `elements` from it

2022-07-14 14:30 UTC, vilchik-elena commented on eslint-bridge/src/rules/no-useless-react-setstate.ts
> +          scope.references.forEach(ref => {
why didn't you use `getVariableFromName` here as well?

2022-07-14 14:30 UTC, vilchik-elena commented on eslint-bridge/src/rules/no-useless-react-setstate.ts
> +          referencesBySetterName[key].value === value
what if value variable is not resolved and both of them will be `null`? Strictly speaking one will be `null` and another `undefined` so they will never be equal but still a dirty state to improve.

2022-07-14 14:30 UTC, vilchik-elena commented on eslint-bridge/src/rules/no-useless-react-setstate.ts
> +    const declaratorSelector = [
I would move it to the very top, no point in computing it for every file

2022-07-14 14:30 UTC, vilchik-elena commented on eslint-bridge/src/rules/no-useless-react-setstate.ts
> +    const declaratorSelector = [
-> `declarationSelector`

2022-07-14 16:44 UTC, victor-diez-sonarsource commented on eslint-bridge/src/rules/no-useless-react-setstate.ts
> +          scope.references.forEach(ref => {
:man_facepalming:

2022-07-15 07:52 UTC, vilchik-elena approved these changes

2022-07-15 07:53 UTC, merged