Improve S6439 (sonar-jsx-no-leaked-render): report on a string only for react-native
SonarSource/SonarJS pull request #3229
Opened 2022-07-14 13:05 UTC by victor-diez-sonarsource

Fixes #3228

2022-07-15 13:22 UTC, vilchik-elena requested changes
What about rule description?

2022-07-15 13:22 UTC, vilchik-elena commented on eslint-bridge/src/rules/sonar-jsx-no-leaked-render.ts
>    const type = getTypeFromTreeNode(node, context.parserServices);
we are computing this type twice, here and on line 106

2022-07-15 13:22 UTC, vilchik-elena commented on eslint-bridge/src/rules/sonar-jsx-no-leaked-render.ts
> +            typeof node.range !== 'undefined' &&
can't we just check the value? why `typeof`?

2022-07-15 13:22 UTC, vilchik-elena commented on its/sources/file-for-rules/S6439.js
> +const Component1 = collection => {
add comments to show where you expect issues here

2022-07-18 09:29 UTC, victor-diez-sonarsource commented on eslint-bridge/src/rules/sonar-jsx-no-leaked-render.ts
> +            typeof node.range !== 'undefined' &&
what do you mean? I would say typeof is necessary here to check before comparing the values

2022-07-18 14:07 UTC, saberduck commented on eslint-bridge/src/rules/sonar-jsx-no-leaked-render.ts
> +            typeof node.range !== 'undefined' &&
why not checking just `node.range !== 'undefined' , what's the reason for using `typeof`? you can be sure that 'range' property exists

2022-07-18 14:40 UTC, victor-diez-sonarsource commented on eslint-bridge/src/rules/sonar-jsx-no-leaked-render.ts
> +            typeof node.range !== 'undefined' &&
oh, you mean:

node.range !== undefined

instead of:

typeof node.range !== 'undefined'

I can change that, in javascript I would say typeof is the preferred solution, but the second is more ts-like

2022-07-19 08:50 UTC, vilchik-elena approved these changes

2022-07-19 08:51 UTC, merged