Add rule S6441: Unused methods of React components should be removed
SonarSource/SonarJS pull request #3253
Opened 2022-07-19 14:03 UTC by victor-diez-sonarsource

Fixes #3214

2022-07-19 17:21 UTC, vilchik-elena requested changes

2022-07-19 17:21 UTC, vilchik-elena commented on eslint-bridge/src/rules/sonar-no-unused-class-component-methods.ts
> +      unused: 'Method or property "{{name}}" is not used inside component body',
ha, in fact we can do whatever we want with the message, should we try to rephrase it then?
e.g. `Remove this property or method or refactor this component "{{className}}", as "{{name}}" is not used inside component body`

2022-07-19 17:21 UTC, vilchik-elena commented on javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S6441.html
> +scope of a component class, which means that issues will be raised on the methods that are only used outside of the class.</p>
We should add some phrase here that it's considered a bad practice to use component methods outside of it.

2022-07-19 17:50 UTC, victor-diez-sonarsource commented on javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S6441.html
> +scope of a component class, which means that issues will be raised on the methods that are only used outside of the class.</p>
but we add that to rspec repo, right?

2022-07-21 07:06 UTC, vilchik-elena requested changes

2022-07-21 07:06 UTC, vilchik-elena commented on javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S6441.html
> +<p>FIXME: A list of links</p>
oops :)

2022-07-21 07:06 UTC, vilchik-elena commented on javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S6441.html
> +scope of a component class, which means that issues will be raised on the methods that are only used outside of the class.</p>
regenerate the file to have your changes in the PR

2022-07-21 07:39 UTC, vilchik-elena approved these changes
LGTM. I would just change text for the link

2022-07-21 10:03 UTC, saberduck submitted a review, later dismissed

2022-07-21 10:08 UTC, vilchik-elena requested changes

2022-07-21 10:08 UTC, vilchik-elena commented on eslint-bridge/src/rules/sonar-no-unused-class-component-methods.ts
> +    function overrideContext(overrides: any) {
I would move it to the top of the file after the rule definition to keep the logic here cleaner

2022-07-21 10:08 UTC, vilchik-elena commented on eslint-bridge/src/rules/sonar-no-unused-class-component-methods.ts
> +    // We may need to add deprecated API that the react plugin still relies on if the rule is decorated by
I don't understand this comment

2022-07-21 10:08 UTC, vilchik-elena commented on eslint-bridge/tests/rules/decorators/sonar-no-unused-class-component-methods.test.ts
> +ruleTester.run(`Function parameters with default values should be last`, rule, {
this is copy paste from another rule

2022-07-21 10:08 UTC, vilchik-elena commented on eslint-bridge/tests/rules/decorators/sonar-no-unused-class-component-methods.test.ts
> +const ruleTester = new RuleTester({ parserOptions: { ecmaVersion: 2018, sourceType: 'module' } });
as we don't use decorator now, can we rely on comment-based tests?

2022-07-21 11:15 UTC, victor-diez-sonarsource commented on eslint-bridge/src/rules/sonar-no-unused-class-component-methods.ts
> +    // We may need to add deprecated API that the react plugin still relies on if the rule is decorated by
copy paste from Francois, I will remove

2022-07-21 11:49 UTC, merged