generate base files
SonarSource/SonarJS pull request #3276
Opened 2022-07-27 10:14 UTC by ilia-kebets-sonarsource

Fixes #3207

2022-07-27 12:55 UTC, ilia-kebets-sonarsource commented
- python test cases: python-checks/src/test/resources/checks/cdk/s3BucketVersioning.py
- python rule implementation: python-checks/src/main/java/org/sonar/python/checks/cdk/S3BucketVersioningCheck.java

2022-08-02 11:57 UTC, yassin-kammoun-sonarsource requested changes

2022-08-02 11:57 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/tests/rules/comment-based/aws-s3-bucket-versioning.js
> +const otherImport = new cdk.aws_s3.Bucket(this, 'id') // Noncompliant {{Omitting the "versioned" argument disables S3 bucket versioning. Make sure it is safe here.}}
I think it's okay if we assert the issue message only once. You could only keep the `// Noncompliant` part only for this type of issue.

2022-08-02 11:57 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/tests/rules/comment-based/aws-s3-bucket-versioning.js
> +const noOtionsParam = new s3.Bucket(this, 'id', { // Noncompliant {{Omitting the "versioned" argument disables S3 bucket versioning. Make sure it is safe here.}}
Typo `noOtionsParam `

2022-08-04 10:00 UTC, yassin-kammoun-sonarsource approved these changes
Looks good to me but we are missing a test file in the integration tests to validate the rule. 

Also, I am surprised that we are not raising issues on the following file:

https://github.com/SonarSource/SonarJS/blob/d65837cab786e6fbe19f8d4ac3fa9dbccdb19fc7/its/sources/file-for-rules/S6245.js#L1-L17

Maybe you need to pull again the main branch's recent changes.

2022-08-04 10:00 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/utils/utils-location.ts
> +  secondaryMessages: (string | undefined)[] = [],
Was there a need for that change? Is the semantics of the following line preserved?

https://github.com/SonarSource/SonarJS/blob/20a9f724a82ff2c1c87c0dd21dfcf40e1160ebdd/eslint-bridge/src/utils/utils-location.ts#L39

I haven't tested it so I am just asking to be sure.

2022-08-04 11:31 UTC, ilia-kebets-sonarsource commented on eslint-bridge/src/utils/utils-location.ts
> +  secondaryMessages: (string | undefined)[] = [],
The goal was to avoid having to specify default params here:

https://github.com/SonarSource/SonarJS/pull/3276/files#diff-d1eefdd61ea1ad1ed8f3f7e0660b7314741d37aa772654ef915735fac335d3b7R46

2022-08-04 11:35 UTC, ilia-kebets-sonarsource commented on eslint-bridge/src/utils/utils-location.ts
> +  secondaryMessages: (string | undefined)[] = [],
It does not break as long as we have the same number of elements in `secondaryLocationsHolder` and `secondaryMessages`. However, as they are consumed together, shouldn't they be in the same data struct like?:

```javascript
secondaries = {
 locationHolder: ...,
 message: ....
}
```

2022-08-04 11:46 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/utils/utils-location.ts
> +  secondaryMessages: (string | undefined)[] = [],
It's okay like this I guess.

2022-08-05 07:38 UTC, merged