Ignore React components defined with lambda expressions
SonarSource/SonarJS pull request #3296
Opened 2022-08-03 10:08 UTC by francoismora

Fixes #3215

2022-08-03 15:57 UTC, saberduck requested changes

2022-08-03 15:57 UTC, saberduck commented on eslint-bridge/src/rules/function-name.ts
> +  id: TSESTree.Node | null;
it seems to me that we do nothing if id is `null`,  we might as well forbid putting `null` in the type

2022-08-03 15:57 UTC, saberduck commented on eslint-bridge/src/rules/function-name.ts
> +  if (node.type === 'FunctionDeclaration') {
you can check for `node.id == null` here and remove `| null` whenever `id` is used

2022-08-04 07:37 UTC, francoismora commented on eslint-bridge/src/rules/function-name.ts
> +  id: TSESTree.Node | null;
Indeed you are right; the case where id is null can be propagated to the case where the knowledge base is null. Nice catch. Thanks for pointing this out.

2022-08-04 07:37 UTC, francoismora commented on eslint-bridge/src/rules/function-name.ts
> +  if (node.type === 'FunctionDeclaration') {
Done

2022-08-04 12:14 UTC, saberduck approved these changes

2022-08-04 12:14 UTC, merged