Ilia's review of eslint-bridge refactor 2
SonarSource/SonarJS pull request #3308
Opened 2022-08-09 08:40 UTC by ilia-kebets-sonarsource

2022-08-09 15:41 UTC, ilia-kebets-sonarsource commented
TODO:
- paths in DEV.md
- refactor toEncodedMessage - data struct

2022-08-10 10:46 UTC, yassin-kammoun-sonarsource requested changes
Thanks for the review and the many improvement suggestions :)

2022-08-10 10:46 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/errors/builder.ts
> +}
From what I understand, we are introducing another category of errors between the routing layer and the services layer in case of unexpected runtime errors (and also because we want to properly use Express.js error handling mechanism). I think we need to be more explicit about what kind of errors we are dealing with here and why because `SonarError` is too vague. I am not entirely satisfied with the name I came up with. Maybe `HandlerError` or `ServiceError` is better. Feel free to challenge the name as long as it's not `SonarError` :).

2022-08-10 10:46 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/errors/builder.ts
> +}
Regardless of what you decide, we still need to document this new category of errors.

2022-08-10 10:46 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/services/analysis/runner.ts
> +      next(buildError(error, 'Parsing'));
```suggestion
      next(routingError(error, 'Analysis'));
```

2022-08-10 10:46 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/services/analysis/runner.ts
> +import { buildError } from '../../errors';
```suggestion
import { routingError } from '../../errors';
```

2022-08-10 10:46 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/tests/services/analysis/runner.test.ts
> -
I think this test is still relevant and requires a bit of refinement like mocking the `next` function to validate that the runner does indeed invoke `next` on analysis failures.

2022-08-10 10:46 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/errors/middleware.ts
> +  }
Ideally, it would be nice if we could have a proper `middleware.test.ts` test suite with a unit test for each case.

2022-08-10 10:46 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/routing/on-tsconfig-files.ts
> +    next(error);
```suggestion
    next(routingError(error, 'TSConfig'));
```

2022-08-10 10:46 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/routing/on-create-program.ts
> +    next(error);
```suggestion
    next(routingError(error, 'Program'));
```

2022-08-10 10:46 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/tests/routing/routing.test.ts
> +    ]);
Let's get rid of that since it does not matter.

2022-08-10 10:46 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/tests/routing/routing.test.ts
> +    const response = (await request(server, host, '/analyze-yaml', 'POST', data)) as string;
This seems like copy-pasted: YAML analysis with a malformed JSON file used as a TSConfig, that's weird. If we want to validate that we do use the error middleware while analyzing a YAML file, let's define a YAML fixture file in that case :)

2022-08-11 08:56 UTC, ilia-kebets-sonarsource commented on eslint-bridge/src/errors/middleware.ts
> +export function errorMiddleware(
You're unfortunately right, the guy indeed calls it `errorHandler`, my argument for calling it `middleware` can be backed by this doc: https://expressjs.com/en/guide/writing-middleware.html
An express app is structured as a stack of middleware, so for me, `middleware` conveys more information as I associate it with express.
What do you think?

2022-08-11 09:16 UTC, ilia-kebets-sonarsource commented on eslint-bridge/src/routing/on-tsconfig-files.ts
> +    next(error);
Regarding error types, I believe that having a matching error type per API route brings nothing. Client-side, if you have called the `/ts-config-files` API route, you know that the error from your request comes from it.
The errors are either user/programmatic or system/operationnal: 
- user: unable to parse contents, missing extension, incomplete tsconfig
- system errors: unexpected error during rule execution, crash

2022-08-22 20:33 UTC, ilia-kebets-sonarsource commented on eslint-bridge/tests/services/analysis/runner.test.ts
> -
I really wish to remove runner

2022-08-22 20:34 UTC, ilia-kebets-sonarsource commented on eslint-bridge/src/routing/on-create-program.ts
> +    next(error);
same as https://github.com/SonarSource/SonarJS/pull/3308#discussion_r943270581

2022-08-22 20:34 UTC, ilia-kebets-sonarsource commented on eslint-bridge/tests/routing/routing.test.ts
> +    ]);
done.

2022-08-22 20:34 UTC, ilia-kebets-sonarsource commented on eslint-bridge/tests/routing/routing.test.ts
> +    const response = (await request(server, host, '/analyze-yaml', 'POST', data)) as string;
yes it was.

2022-08-22 21:29 UTC, ilia-kebets-sonarsource commented on eslint-bridge/tests/services/analysis/analyzers/js/analyzer.test.ts
> -  it('should return an empty analysis output on parsing errors', () => {
this was moved to routing.test

2022-08-23 05:09 UTC, ilia-kebets-sonarsource commented
The IT tests fail because of `ERROR: Error: Cannot find module 'routing'`, I'm investigating why:

```
"ERROR: Error: Cannot find module 'routing'",
    "ERROR: Require stack:",
    "ERROR: - /tmp/cirrus-ci-build/its/plugin/projects/eslint_based_rules/.scannerwork/.sonartmp/eslint-bridge-bundle/package/lib/server.js",
    "ERROR: - /tmp/cirrus-ci-build/its/plugin/projects/eslint_based_rules/.scannerwork/.sonartmp/eslint-bridge-bundle/package/bin/server",
    "ERROR:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)",
    "ERROR:     at Function.Module._load (internal/modules/cjs/loader.js:667:27)",
    "ERROR:     at Module.require (internal/modules/cjs/loader.js:887:19)",
    "ERROR:     at require (internal/modules/cjs/helpers.js:74:18)",
    "ERROR:     at Object.<anonymous> (/tmp/cirrus-ci-build/its/plugin/projects/eslint_based_rules/.scannerwork/.sonartmp/eslint-bridge-bundle/package/lib/server.js:27:35)",
    "ERROR:     at Module._compile (internal/modules/cjs/loader.js:999:30)",
    "ERROR:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)",
    "ERROR:     at Module.load (internal/modules/cjs/loader.js:863:32)",
    "ERROR:     at Function.Module._load (internal/modules/cjs/loader.js:708:14)",
    "ERROR:     at Module.require (internal/modules/cjs/loader.js:887:19) {",
    "ERROR:   code: 'MODULE_NOT_FOUND',",
    "ERROR:   requireStack: [",
    "ERROR:     '/tmp/cirrus-ci-build/its/plugin/projects/eslint_based_rules/.scannerwork/.sonartmp/eslint-bridge-bundle/package/lib/server.js',",
    "ERROR:     '/tmp/cirrus-ci-build/its/plugin/projects/eslint_based_rules/.scannerwork/.sonartmp/eslint-bridge-bundle/package/bin/server'",
    "ERROR:   ]",
    "ERROR: }",
```

2022-08-23 06:16 UTC, ilia-kebets-sonarsource commented
I think I have an issue with the params for server start, probably due to having removed `host`.

2022-08-23 14:08 UTC, ilia-kebets-sonarsource commented on eslint-bridge/src/errors/middleware.ts
> +  }
done

2022-08-23 14:38 UTC, yassin-kammoun-sonarsource approved these changes
LGTM! Good job introducing a cleaner error management!

2022-08-23 14:38 UTC, merged