Add integration test to support PR analysis.
SonarSource/SonarJS pull request #3343
Opened 2022-08-24 15:19 UTC by francoismora

Fixes #3339

2022-08-26 20:08 UTC, vilchik-elena requested changes

2022-08-26 20:08 UTC, vilchik-elena commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/PullRequestAnalysisDeveloperTest.java
> +    executor.execute(git -> git.checkout().setCreateBranch(true).setName(PR2.BRANCH));
tbh I don't yet see the point of having 2 PRs

2022-08-26 20:08 UTC, vilchik-elena commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/PullRequestAnalysisDeveloperTest.java
> +  private SonarScanner getMasterScanner() {
let's use `master` or `main` everywhere in the test

2022-08-26 20:08 UTC, vilchik-elena commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/PullRequestAnalysisDeveloperTest.java
> +    assertThat(getIssues(PROJECT_KEY + ":hello.js")).isEmpty();
we can extract file key I think

2022-08-27 16:32 UTC, francoismora commented on .cirrus.yml
> -    GITHUB_TOKEN: ENCRYPTED[!f458126aa9ed2ac526f220c5acb51dd9cc255726b34761a56fc78d4294c11089502a882888cef0ca7dd4085e72e611a5!]
The GitHub token is required for building and for QA (to download the developer sonarqube license). Moving it up makes it available for all the tasks and not just for building tasks.

2022-08-27 16:32 UTC, francoismora commented on its/plugin/tests/pom.xml
> +                <sonar.edition>developer</sonar.edition>
Done

2022-08-27 16:46 UTC, francoismora commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/PullRequestAnalysisDeveloperTest.java
> +    OrchestratorStarter.setProfile(PROJECT_KEY, "nosonar-profile", "js");
Some test files have an extra semicolon to trigger issues. This profile contains the needed S1116 rule.

2022-08-27 16:50 UTC, francoismora commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/PullRequestAnalysisDeveloperTest.java
> +    executor.execute(git -> git.checkout().setCreateBranch(true).setName(PR2.BRANCH));
One PR has only 1 file changed, so we should be able to validate that the other file has been skipped using logs for a PR but not for the other one.

2022-08-27 17:02 UTC, francoismora commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/PullRequestAnalysisDeveloperTest.java
> +  private SonarScanner getMasterScanner() {
Renamed everything to main.

2022-08-29 08:33 UTC, francoismora commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/PullRequestAnalysisDeveloperTest.java
> +class PullRequestAnalysisDeveloperTest {
Renamed.

2022-08-29 08:57 UTC, vilchik-elena requested changes

2022-08-29 08:57 UTC, vilchik-elena commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/PullRequestAnalysisTest.java
> +      "  handler('Starting...');;",
Add comment that we gonna have an issue on this line

2022-08-29 08:57 UTC, vilchik-elena commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/PullRequestAnalysisTest.java
> +  void should_analyse_pull_requests() {
let's have 2 analyses:
* Main branch: 1 issue on file A
* PR branch: 1 issue on file B

2022-08-29 08:57 UTC, vilchik-elena commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/PullRequestAnalysisTest.java
> +  private final StopWatch stopWatch = new StopWatch();
let's drop timers in this test as there is nothing to assert

2022-08-29 09:01 UTC, vilchik-elena commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/PullRequestAnalysisTest.java
> +  void should_analyse_pull_requests() {
let's have another test for TS (just replace the file extenstions)

2022-08-29 09:43 UTC, vilchik-elena commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/PullRequestAnalysisTest.java
> +    assertThat(getIssues(PROJECT_KEY + ":hello.js", PR1.BRANCH)).hasSize(1);
request issues for all files, at project level

2022-08-30 07:14 UTC, francoismora commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/PullRequestAnalysisDeveloperTest.java
> +    OrchestratorStarter.setProfile(PROJECT_KEY, "nosonar-profile", "js");
New profiles added.

2022-08-30 07:14 UTC, francoismora commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/PullRequestAnalysisDeveloperTest.java
> +    OrchestratorStarter.setProfile(PROJECT_KEY, "nosonar-profile", "js");
New typescript test case added.

2022-08-30 07:14 UTC, francoismora commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/PullRequestAnalysisDeveloperTest.java
> +    executor.execute(git -> git.checkout().setCreateBranch(true).setName(PR2.BRANCH));
Second PR removed.

2022-08-30 07:16 UTC, francoismora commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/PullRequestAnalysisTest.java
> +      "  handler('Starting...');;",
Comment added.

2022-08-30 07:16 UTC, francoismora commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/PullRequestAnalysisTest.java
> +  private final StopWatch stopWatch = new StopWatch();
Timers dropped.

2022-08-30 07:16 UTC, francoismora commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/PullRequestAnalysisTest.java
> +  void should_analyse_pull_requests() {
Test added.

2022-08-30 07:29 UTC, francoismora commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/PullRequestAnalysisTest.java
> +    assertThat(getIssues(PROJECT_KEY + ":hello.js", PR1.BRANCH)).hasSize(1);
Assertions done on all issues.

2022-08-30 07:32 UTC, francoismora commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/PullRequestAnalysisTest.java
> +  void should_analyse_pull_requests() {
Test case implemented that way.

2022-08-30 09:26 UTC, vilchik-elena commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/PRAnalysisTest.java
> +      scanner.setProperty("sonar.typescript.tsconfigPath", "tsconfig.json");
no need to do that, it should be autodiscoverable

2022-08-30 09:27 UTC, vilchik-elena commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/PRAnalysisTest.java
> +class PRAnalysisTest {
IMHO `PullRequest` was more readable

2022-08-30 09:28 UTC, vilchik-elena commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/PRAnalysisTest.java
> +      .setProperty("sonar.analysisCache.enabled", "true");
I prefer we don't put this property yet as it does not make any difference

2022-08-30 09:52 UTC, vilchik-elena commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/OrchestratorStarter.java
> +  static List<Issue> getIssues(String componentKey, String pullRequest) {
I think we should rename parameter to `branch`

2022-08-30 09:54 UTC, vilchik-elena commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/PRAnalysisTest.java
> +    public static final int RULE_EXECUTIONS = 2;
I would rename it to `ANALYZER_REPORTED_ISSUES`

2022-08-30 11:57 UTC, francoismora commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/PRAnalysisTest.java
> +class PRAnalysisTest {
I changed it to be more consistent with the profile files (pr-analysis-js-profile, pr-analysis-ts-profile), and the project keys (pr-analysis-js, pr-analysis-ts) as otherwise, names are getting a bit long, ex: `pull-request-analysis-js-profile`.

2022-08-30 12:16 UTC, francoismora commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/PRAnalysisTest.java
> +      .setProperty("sonar.analysisCache.enabled", "true");
Removed.

2022-08-30 12:16 UTC, francoismora commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/PRAnalysisTest.java
> +      scanner.setProperty("sonar.typescript.tsconfigPath", "tsconfig.json");
Removed.

2022-08-30 12:18 UTC, francoismora commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/OrchestratorStarter.java
> +  static List<Issue> getIssues(String componentKey, String pullRequest) {
Do you mean to replace `request.setPullRequest()` by `request.setBranch()` as well?

2022-08-30 12:19 UTC, vilchik-elena commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/PRAnalysisTest.java
> +class PRAnalysisTest {
ok, that's not that important

2022-08-30 12:20 UTC, vilchik-elena commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/OrchestratorStarter.java
> +  static List<Issue> getIssues(String componentKey, String pullRequest) {
no, just parameter name `pullRequest` -> `branch` as we use the same method to get issues for master branch

2022-08-30 12:45 UTC, vilchik-elena approved these changes

2022-08-30 12:57 UTC, merged