Fix 'RULE' metric type for performance monitoring
SonarSource/SonarJS pull request #3350
Opened 2022-08-29 11:45 UTC by vilchik-elena

Fixes #3341

2022-08-29 14:22 UTC, vilchik-elena commented
One condition is not covered but I think it's not worthy to make it covered

2022-08-30 13:05 UTC, saberduck requested changes
some minor comments

2022-08-30 13:05 UTC, saberduck commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/TypeScriptRuleTest.java
> +      .setProperty("sonar.javascript.monitoring.path", FileLocation.of(perfMonitoringDir).getFile().getAbsolutePath())
I prefer to use Java's API instead of orchestrator `FileLocation` , you can use `Path.of(...).toAbsolutePath` (I think the `FileLocation` usage was copy&pasted from other analyzers, and we should stop this bad habit :)

2022-08-30 13:05 UTC, saberduck commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/TypeScriptRuleTest.java
> +  private void assertPerfMonitoringAvailable(String perfMonitoringDir) throws IOException {
better to have `Path` as argument type

2022-08-30 13:05 UTC, saberduck commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImpl.java
> +      if (s.startsWith(HEADER_HEAD) && s.endsWith(HEADER_TAIL)) {
wdyt about using regex here? seems like we could just have `Rule .+Time (ms) | Relative`

2022-08-30 14:35 UTC, vilchik-elena commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImpl.java
> +      if (s.startsWith(HEADER_HEAD) && s.endsWith(HEADER_TAIL)) {
I try to avoid using regex when it's possible :) but let me try)

2022-08-30 15:32 UTC, saberduck approved these changes

2022-08-30 15:32 UTC, merged