Skip analysis for unchanged files when the analysis allows it
SonarSource/SonarJS pull request #3352
Opened 2022-08-29 15:37 UTC by francoismora

Fixes #3345

2022-09-01 12:42 UTC, vilchik-elena commented on eslint-bridge/src/services/analysis/analyzers/js/analyzer.ts
> +  debug(`analyzing file linterId=${input.linterId}`);
let's add path to the file as well

2022-09-01 12:42 UTC, vilchik-elena commented on eslint-bridge/src/services/analysis/analyzers/js/analyzer.ts
> +  const linter = getLinter(input.linterId || 'default');
we don't need `|| 'default'` as this parameter has a default value

2022-09-01 12:42 UTC, vilchik-elena commented on eslint-bridge/src/services/analysis/analyzers/yaml/analyzer.ts
> +  debug(`analyzing file linterId=${input.linterId}`);
same here, log file path

2022-09-01 12:42 UTC, vilchik-elena commented on eslint-bridge/src/services/analysis/analyzers/yaml/analyzer.ts
> +  const linter = getLinter(input.linterId || 'default');
same here, no need for default

2022-09-01 12:42 UTC, vilchik-elena commented on eslint-bridge/src/linting/eslint/index.ts
> +    throw APIError.linterError(`Linter ${linterId} does not exist. Did you call /init-linter?`);
let's add quotes around `${linterId}`

2022-09-01 12:59 UTC, vilchik-elena commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/PRAnalysisTest.java
> +      .addPlugin(MavenLocation.of("com.sonarsource.security", "sonar-security-php-frontend-plugin", "LATEST_RELEASE"))
don't use `getOrchestratorBuilder`, then you can drop php frontend

2022-09-01 12:59 UTC, vilchik-elena commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/PRAnalysisTest.java
> +        .hasLogs("DEBUG: Saving issue for rule no-extra-semi", Master.ANALYZER_REPORTED_ISSUES)
let's order logs in the order of appearence

2022-09-01 12:59 UTC, vilchik-elena commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/PRAnalysisTest.java
> +      assertThat(findUcfgFilesIn(projectPath)).isNotEmpty();
We should assert that there is at least one UCFG for each file

2022-09-01 13:28 UTC, vilchik-elena commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/PRAnalysisTest.java
> +    BuildResultAssert hasAtLeastLog(String log) {
`logsAtLeastOnce`

2022-09-01 13:28 UTC, vilchik-elena commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/PRAnalysisTest.java
> +    BuildResultAssert hasLogs(String log, int times) {
`logsTimes`

2022-09-01 13:28 UTC, vilchik-elena commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/PRAnalysisTest.java
> +    BuildResultAssert hasNotLog(String log) {
`doesNotLog`

2022-09-01 13:28 UTC, vilchik-elena commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/PRAnalysisTest.java
> +    BuildResultAssert hasLog(String log) {
`logsOnce`

2022-09-01 13:28 UTC, vilchik-elena commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/PRAnalysisTest.java
> +  static class BuildResultAssert extends AbstractAssert<BuildResultAssert, BuildResult> {
I suggest to extract this class into another file. This piece of logic is pretty big and independent, we could reuse it later

2022-09-01 13:28 UTC, vilchik-elena commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/PRAnalysisTest.java
> +        .hasLogs("analyzing file linterId=default", Master.SOURCE_FILES);
let's add log level to add logs here

2022-09-01 14:01 UTC, vilchik-elena commented on eslint-bridge/tests/services/analysis/analyzers/js/analyzer.test.ts
> +    initializeLinter([], [], [], 'empty');
I don't understand why you decided to add this test case

2022-09-01 14:27 UTC, vilchik-elena commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/AnalysisOptions.java
> +      LOG.info("Won't skip unchanged files as this is not activated in the sensor context");
this message should be in Debug and use more user-friendly terms

2022-09-01 14:27 UTC, vilchik-elena commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/AnalysisOptions.java
> +    if (!containsUcfgRule) {
add comment that this theoretically should never happen as PR analysis exists only on Developer edition where UCFG rule should be available

2022-09-01 14:27 UTC, vilchik-elena commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/AnalysisOptions.java
> +      LOG.info("Won't skip unchanged files as there's no rule with the ESLint key '{}'", EslintRule.UCFG_ESLINT_KEY);
in fact it's opposite, we will fully skip unchanged files in this case

2022-09-01 14:27 UTC, vilchik-elena commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/AnalysisOptions.java
> +
I suggest to add here an INFO log `Performing optimized analysis as we can skip files which didn't change`

2022-09-01 14:27 UTC, vilchik-elena commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/AnalysisOptions.java
> +      LOG.info("Won't skip unchanged files as there's no rule with the ESLint key '{}'", EslintRule.UCFG_ESLINT_KEY);
I suggest  `LOG.info("Files which didn't change are excluded from analysis")`

2022-09-01 14:27 UTC, vilchik-elena commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/AnalysisOptions.java
> +    LOG.info("Will skip unchanged files");
I suggest  `LOG.info("Files which didn't change will be part of UCFG generation only, other rules will not be executed")`

2022-09-01 14:27 UTC, vilchik-elena commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/AnalysisOptions.java
> +  List<InputFile> getFilesToAnalyzeIn(List<InputFile> inputFiles) {
I am not sure why name has `in` at the end. I suggest to drop it

2022-09-01 14:27 UTC, vilchik-elena commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/AnalysisOptions.java
> +    if (skipUnchangedFiles && unchangedFileRules.isEmpty()) {
let's use enum of the analysis mode to not compute it here again

2022-09-01 14:46 UTC, vilchik-elena requested changes

2022-09-01 14:46 UTC, vilchik-elena commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintRule.java
> +  static List<EslintRule> findFirstRuleWithKey(List<EslintRule> rules, String eslintKey) {
let's just return a rule, not the list

2022-09-01 14:46 UTC, vilchik-elena commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/YamlSensor.java
> +  protected void analyzeFiles(List<InputFile> allFiles) throws IOException {
let's add yaml to the integration test

2022-09-02 08:04 UTC, francoismora commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/PRAnalysisTest.java
> +      .addPlugin(MavenLocation.of("com.sonarsource.security", "sonar-security-php-frontend-plugin", "LATEST_RELEASE"))
Done.

2022-09-02 08:04 UTC, francoismora commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/PRAnalysisTest.java
> +        .hasLogs("DEBUG: Saving issue for rule no-extra-semi", Master.ANALYZER_REPORTED_ISSUES)
Done

2022-09-02 08:04 UTC, francoismora commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/PRAnalysisTest.java
> +      assertThat(findUcfgFilesIn(projectPath)).isNotEmpty();
Done

2022-09-02 08:05 UTC, francoismora commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/PRAnalysisTest.java
> +    BuildResultAssert hasAtLeastLog(String log) {
Done

2022-09-02 08:05 UTC, francoismora commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/PRAnalysisTest.java
> +    BuildResultAssert hasLogs(String log, int times) {
Done

2022-09-02 08:05 UTC, francoismora commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/PRAnalysisTest.java
> +    BuildResultAssert hasNotLog(String log) {
Done

2022-09-02 08:05 UTC, francoismora commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/PRAnalysisTest.java
> +    BuildResultAssert hasLog(String log) {
Done

2022-09-02 08:05 UTC, francoismora commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/PRAnalysisTest.java
> +  static class BuildResultAssert extends AbstractAssert<BuildResultAssert, BuildResult> {
Done

2022-09-02 08:06 UTC, francoismora commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/PRAnalysisTest.java
> +        .hasLogs("analyzing file linterId=default", Master.SOURCE_FILES);
Done

2022-09-02 08:06 UTC, francoismora commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/AnalysisOptions.java
> +  AnalysisOptions(SensorContext context, List<EslintRule> rules) {
Done

2022-09-02 08:11 UTC, francoismora commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/AnalysisOptions.java
> +      LOG.info("Won't skip unchanged files as this is not activated in the sensor context");
Done

2022-09-02 08:14 UTC, francoismora commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/AnalysisOptions.java
> +    if (!containsUcfgRule) {
Done

2022-09-02 08:14 UTC, francoismora commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/AnalysisOptions.java
> +      LOG.info("Won't skip unchanged files as there's no rule with the ESLint key '{}'", EslintRule.UCFG_ESLINT_KEY);
Done

2022-09-02 08:15 UTC, francoismora commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/AnalysisOptions.java
> +
As discussed this is not needed anymore.

2022-09-02 08:16 UTC, francoismora commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/AnalysisOptions.java
> +    LOG.info("Will skip unchanged files");
Done

2022-09-02 08:17 UTC, francoismora commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/AnalysisOptions.java
> +  List<InputFile> getFilesToAnalyzeIn(List<InputFile> inputFiles) {
As discussed this is not needed anymore.

2022-09-02 08:17 UTC, francoismora commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/AnalysisOptions.java
> +    if (skipUnchangedFiles && unchangedFileRules.isEmpty()) {
Done

2022-09-02 08:17 UTC, francoismora commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintRule.java
> +  static List<EslintRule> findFirstRuleWithKey(List<EslintRule> rules, String eslintKey) {
Done

2022-09-02 11:46 UTC, vilchik-elena requested changes

2022-09-02 11:46 UTC, vilchik-elena commented on sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/AnalysisModeTest.java
> +  private AutoCloseable mocks;
I don't understand why we need this one

2022-09-02 11:46 UTC, vilchik-elena commented on sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/AnalysisModeTest.java
> +    for (var file : files) {
can't you do same as on line 97?

2022-09-02 11:46 UTC, vilchik-elena commented on sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImplTest.java
> +    eslintBridgeServer.initLinter(rules, Collections.emptyList(), Collections.emptyList(), AnalysisMode.getModeFor(context, Collections.emptyList()));
I don't see the point to call for `getModeFor` here, can we hardcode the value?

2022-09-02 15:15 UTC, francoismora commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/AnalysisMode.java
> +  static final String DEFAULT_LINTER_ID = "default";
Done

2022-09-02 15:15 UTC, francoismora commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/AnalysisMode.java
> +    // IF we can skip unchanged files AND the file is unchanged THEN we can use the unchanged linter.
Removed

2022-09-02 15:15 UTC, francoismora commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/AnalysisMode.java
> +    if (this == SKIP_UNCHANGED) {
Dropped

2022-09-02 15:17 UTC, francoismora commented on sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/AnalysisModeTest.java
> +  private AutoCloseable mocks;
That's taken from Mockito annotations
<img width="659" alt="image" src="https://user-images.githubusercontent.com/108535395/188180998-ea22d601-bdc1-460d-aef0-9be3df74f6c3.png">

2022-09-02 15:21 UTC, francoismora commented on sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/AnalysisModeTest.java
> +    for (var file : files) {
Done

2022-09-02 15:22 UTC, francoismora commented on sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImplTest.java
> +    eslintBridgeServer.initLinter(rules, Collections.emptyList(), Collections.emptyList(), AnalysisMode.getModeFor(context, Collections.emptyList()));
Hard-coded

2022-09-05 09:46 UTC, vilchik-elena approved these changes

2022-09-09 08:20 UTC, merged