Update sonarqube and plugin API versions
SonarSource/SonarJS pull request #3353
Opened 2022-08-29 15:41 UTC by francoismora

2022-08-29 17:45 UTC, vilchik-elena approved these changes

2022-08-29 17:48 UTC, vilchik-elena requested changes
Plugin test for SonarLint failed, not sure why. May be there sonarlint API version we use is somehow not compatible

2022-08-30 09:56 UTC, vilchik-elena commented on its/plugin/tests/pom.xml
> +    <dependency>
@francoismora could you share why this fixes the problem?

2022-08-30 11:48 UTC, francoismora commented on its/plugin/tests/pom.xml
> +    <dependency>
A method has been removed in the latest version of the plugin API (`Loggers.setTarget()`) but was still available in the version included in sonarlint. Changing the classpath order fixed the issue, but we decided with @saberduck to upgrade sonarlint instead to have all components aligned to the latest version.

2022-08-30 12:25 UTC, vilchik-elena approved these changes
LGTM, just wonder if we can revert the change of order

2022-08-30 12:25 UTC, vilchik-elena commented on its/plugin/tests/pom.xml
> +    <dependency>
should we revert this change of order then?

2022-08-30 15:12 UTC, merged