First implementation of function name extraction by YAML parser
SonarSource/SonarJS pull request #3354
Opened 2022-08-30 07:52 UTC by ilia-kebets-sonarsource

Fixes #3349

2022-08-30 13:12 UTC, ilia-kebets-sonarsource commented on eslint-bridge/tests/parsing/yaml/parser/parse.test.ts
> +function voidPicker(_key: any, _node: any, _ancestors: any) {
noOpPicker

2022-08-31 09:29 UTC, ilia-kebets-sonarsource commented on eslint-bridge/src/parsing/yaml/aws/parser.ts
> +export const parseAwsFromYaml = parseYaml.bind(null, [lambdaCheck, serverlessCheck]);
The "..Check" could have a better name

2022-08-31 09:36 UTC, yassin-kammoun-sonarsource requested changes
Let's rename the ticket and the PR to `Provide a synthetic filename in the rule context for Inline AWS Lambdas`. I would like to avoid mentioning in the PR as well as the final merged commit the WHY. The ticket description already explains why we need this change :).

2022-08-31 09:36 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/parsing/yaml/parser/embedded-js.ts
> +    functionName?: string;
Maybe extras could just have type `any`.

2022-08-31 09:36 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/parsing/yaml/aws/function.ts
> +export function pickFunctionName(level: number, _key: any, _pair: any, ancestors: any) {
That's not accurate enough. We are picking the resource name to which a function belongs. A [function name](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-functionname) is something else.

2022-08-31 09:36 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/parsing/yaml/builder/build.ts
> +  return `${filePathWithoutExtension}-${functionName}${filePathExtension}`;
Let's rather use [Node.js path API](https://nodejs.org/api/path.html) to manipulate filepaths and extesions.

2022-08-31 09:36 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/parsing/yaml/parser/parse.ts
> +export type PredicateAndPicker = {
```suggestion
export type ParsingContext = {
```

2022-08-31 09:36 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/parsing/yaml/parser/parse.ts
> +  predicateAndPickerBundles: PredicateAndPicker[],
```suggestion
  contexts: ParsingContext[],
```

2022-08-31 09:36 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/tests/parsing/yaml/aws/parser.test.ts
> +    const embedded = parseAwsFromYaml(filePath);
👍

2022-08-31 09:36 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/tests/services/analysis/analyzers/yaml/analyzer.test.ts
> +  });
Let's keep the test simple by testing a single resource since it is already validated for two resources by another layer test. That would avoid us having to collect filenames during the rule execution and asserting their value afterwards. 

```suggestion
  it('should provide a synthetic filename to the rule context', async () => {
    expect.assertions(1);

    const resource = 'SomeLambdaFunction';
    const filePath = join(fixturesPath, 'synthetic-filename.yaml');
    const syntheticFilename = composeSourceCodeFilename(filePath, resource);

    const rule = {
      key: 'synthetic-filename',
      module: {
        create(context: Rule.RuleContext) {
          return {
            Program: () => {
              const filename = context.getFilename();
              expect(filename).toEqual(syntheticFilename);
            },
          };
        },
      }
    }

    initializeLinter([{ key: rule.key, configurations: [], fileTypeTarget: ['MAIN'] }]);
    linter.linter.defineRule(rule.key, rule.module);

    await analyzeYAML({ filePath, fileContent: undefined});
  });
```

2022-08-31 09:36 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/tests/parsing/yaml/parser/parse.test.ts
> +describe('parseAwsFromYaml()', () => {
Let's move this to `tests/parsing/yaml/aws/parser.test.ts`, which already exists.

2022-08-31 09:36 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/tests/parsing/yaml/parser/parse.test.ts
> +  it('should extract the functionName when one exists', () => {
```suggestion
  it('should extract the resource names', () => {
```

2022-08-31 09:36 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/tests/parsing/yaml/parser/parse.test.ts
> +  it('should extract the functionName when one exists', () => {
In fact, I wonder whether we should just rename the test to `it(should extract extra data`. I don't like updating existing tests, but that would make sense in this scenario whenever there is new data that we want to extract and test.

2022-08-31 09:36 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/tests/parsing/yaml/parser/parse.test.ts
> +  });
```suggestion
    const embedded = parseYaml([lambdaCheck, serverlessCheck], filePath);
    expect(embedded).toEqual(expect.arrayContaining([
      expect.objectContaining({
        extras: {
          functionName: 'SomeLambdaFunction',
        }
      }),
      expect.objectContaining({
        extras: {
          functionName: 'SomeServerlessFunction',
        }
      }),
    ]));
  });
```

2022-08-31 09:36 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/tests/parsing/yaml/builder/patch.test.ts
> +    const [patchedSourceCode] = buildSourceCodes(filePath);
👍

2022-08-31 09:36 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/tests/parsing/yaml/parser/fixtures/parse/functionNames.yaml
> +AWSTemplateFormatVersion: 2010-09-09
Let's rename the file to `resourceNames.yaml` or `resource-names.yaml`.

2022-08-31 09:39 UTC, ilia-kebets-sonarsource commented on eslint-bridge/src/parsing/yaml/builder/build.ts
> +};
Yeah, I was thinking about it when cleaning up, it's not a filepath.

2022-08-31 09:41 UTC, ilia-kebets-sonarsource commented on eslint-bridge/tests/services/analysis/analyzers/yaml/fixtures/functionNames.yaml
> +  OtherLambdaFunction:
done as well

2022-08-31 09:41 UTC, ilia-kebets-sonarsource commented on eslint-bridge/tests/services/analysis/analyzers/yaml/fixtures/functionNames.yaml
> +  SomeLambdaFunction:
that was done

2022-08-31 09:50 UTC, ilia-kebets-sonarsource commented on eslint-bridge/src/parsing/yaml/builder/build.ts
> +export function buildSourceCodesMap(filePath: string): FilePathToSourceCode {
ACK

2022-08-31 09:52 UTC, ilia-kebets-sonarsource commented on eslint-bridge/src/parsing/yaml/builder/build.ts
> +}
ACK

2022-08-31 09:53 UTC, ilia-kebets-sonarsource commented on eslint-bridge/src/parsing/yaml/parser/embedded-js.ts
> +    functionName?: string;
ACK

2022-08-31 09:54 UTC, ilia-kebets-sonarsource commented on eslint-bridge/tests/services/analysis/analyzers/yaml/fixtures/functionNames.yaml
> +AWSTemplateFormatVersion: 2010-09-09
ACK

2022-08-31 09:56 UTC, ilia-kebets-sonarsource commented on eslint-bridge/tests/services/analysis/analyzers/yaml/analyzer.test.ts
>  });
ACK

2022-08-31 09:56 UTC, ilia-kebets-sonarsource commented on eslint-bridge/tests/services/analysis/analyzers/yaml/fixtures/functionNames.yaml
> +      InlineCode: console.log("there")
ACK

2022-08-31 09:56 UTC, ilia-kebets-sonarsource commented on eslint-bridge/tests/services/analysis/analyzers/yaml/analyzer.test.ts
> +  });
ACK

2022-08-31 09:57 UTC, ilia-kebets-sonarsource commented on eslint-bridge/tests/parsing/yaml/builder/build.test.ts
> +  describe('buildSourceCodesMap', () => {
ACK

2022-08-31 09:57 UTC, ilia-kebets-sonarsource commented on eslint-bridge/src/parsing/yaml/builder/build.ts
> +}
ACK

2022-08-31 09:58 UTC, ilia-kebets-sonarsource commented on eslint-bridge/src/parsing/yaml/builder/build.ts
> + * @returns
the mystery stays intact

2022-08-31 09:58 UTC, ilia-kebets-sonarsource commented on eslint-bridge/src/parsing/yaml/builder/build.ts
> +export function composeSourceCodeFilename(filePath: string, functionName: string): string {
ACK

2022-08-31 09:58 UTC, ilia-kebets-sonarsource commented on eslint-bridge/tests/parsing/yaml/builder/build.test.ts
> +    it('should compose the filename based on itself and function name', async () => {
ACK

2022-08-31 10:02 UTC, ilia-kebets-sonarsource commented on eslint-bridge/src/parsing/yaml/aws/function.ts
> +};
All good except:
- the multitude of files: I would not create as many
- I don't get why you wish to change the extra picker signature this way. I don't like functions mutating their input parameters.

2022-08-31 10:02 UTC, ilia-kebets-sonarsource commented on eslint-bridge/src/parsing/yaml/aws/function.ts
> +export function pickFunctionName(level: number, _key: any, _pair: any, ancestors: any) {
So pickResourceName?

2022-08-31 10:03 UTC, ilia-kebets-sonarsource commented on eslint-bridge/src/parsing/yaml/builder/build.ts
> +  return `${filePathWithoutExtension}-${functionName}${filePathExtension}`;
ACK

2022-08-31 10:03 UTC, ilia-kebets-sonarsource commented on eslint-bridge/src/parsing/yaml/parser/parse.ts
> +export type PredicateAndPicker = {
ACK

2022-08-31 10:03 UTC, ilia-kebets-sonarsource commented on eslint-bridge/src/parsing/yaml/parser/parse.ts
> +  predicateAndPickerBundles: PredicateAndPicker[],
ACK

2022-08-31 10:04 UTC, ilia-kebets-sonarsource commented on eslint-bridge/tests/parsing/yaml/parser/parse.test.ts
> +describe('parseAwsFromYaml()', () => {
ACK

2022-08-31 10:04 UTC, ilia-kebets-sonarsource commented on eslint-bridge/tests/parsing/yaml/parser/parse.test.ts
> +  it('should extract the functionName when one exists', () => {
ACK

2022-08-31 10:05 UTC, ilia-kebets-sonarsource commented on eslint-bridge/tests/parsing/yaml/parser/parse.test.ts
> +  it('should extract the functionName when one exists', () => {
regarding the name, we're testing the extraction of the resource name, namely the pickResourceName function. So I prefer `should extract resource name` because it is more specific than `extra`

2022-08-31 10:07 UTC, ilia-kebets-sonarsource commented on eslint-bridge/tests/parsing/yaml/parser/parse.test.ts
> +  });
I would remove this layer of objectContaining:

```
expect.objectContaining({
          functionName: 'SomeServerlessFunction',
        })
```

But not add the layer of `arrayContaining`

2022-08-31 10:07 UTC, ilia-kebets-sonarsource commented on eslint-bridge/tests/parsing/yaml/parser/fixtures/parse/functionNames.yaml
> +AWSTemplateFormatVersion: 2010-09-09
ACK

2022-08-31 10:27 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/parsing/yaml/aws/function.ts
> +export function pickFunctionName(level: number, _key: any, _pair: any, ancestors: any) {
Yes

2022-08-31 10:28 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/tests/parsing/yaml/parser/parse.test.ts
> +  it('should extract the functionName when one exists', () => {
Makes sense.

2022-08-31 10:30 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/tests/parsing/yaml/parser/parse.test.ts
> +  });
Feel free to do so. I wanted to use `arrayContaining` so that the order of the array elements is irrelevant for the assertion.

2022-08-31 10:39 UTC, ilia-kebets-sonarsource commented on eslint-bridge/src/parsing/yaml/parser/embedded-js.ts
> +    functionName?: string;
why not mention the optional parameter `resource`, which would somehow indicate the possible fields.

2022-08-31 11:26 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/parsing/yaml/aws/function.ts
> +};
> the multitude of files: I would not create as many

True, but I find it very weird to mix serverless logic with lambda logic. If it's because they share function helpers, I could generalize this to parsing JS/TS and YAML, they are different logic, but it's still about parsing.

2022-08-31 11:26 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/parsing/yaml/aws/function.ts
> +};
> I don't get why you wish to change the extra picker signature this way. I don't like functions mutating their input parameters.

I had something in mind, but I forgot. Let's just ignore my suggestion about this extra parameter.

2022-08-31 11:44 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/parsing/yaml/builder/build.ts
> +};
Since the intersection is cumbersome to deal with, what about this then?

```typescript
export type ExtendedSourceCode = { sourceCode: SourceCode, syntheticFilePath: string };
```

The type name still makes sense as it extends the SourceCode with extra data, and it's extensible. Do you find it acceptable or do you prefer to go back to the Map solution?

2022-08-31 14:52 UTC, yassin-kammoun-sonarsource approved these changes
LGTM. There are a few minor things to address left, but once fixed, we can merge. Good job!

2022-08-31 14:52 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/parsing/yaml/parser/parse.ts
> +export function parseYaml(parsingContext: ParsingContext[], filePath: string): EmbeddedJS[] {
```suggestion
export function parseYaml(parsingContexts: ParsingContext[], filePath: string): EmbeddedJS[] {
```

2022-08-31 14:52 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/parsing/yaml/builder/build.ts
> +  });
👍

2022-08-31 14:52 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/package.json
> +    "@typescript-eslint/eslint-plugin",
To be removed.

2022-08-31 14:52 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/package.json
> +    "lodash.clone": "^4.5.0",
```suggestion
    "lodash.clone": "4.5.0",
```

2022-08-31 14:52 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/package.json
> +    "lodash.clone": "^4.5.0",
The lock file should be updated.

2022-08-31 14:52 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/package.json
> +    "lodash.clone": "^4.5.0",
We also need to add this dependency to the `bundledDependencies`.

2022-08-31 14:52 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/parsing/yaml/builder/build.ts
> + * {filepath-without-extention}-{functionName}{filepath-extension}
```suggestion
 * {filepath-without-extention}-{resourceName}{filepath-extension}
```

2022-08-31 14:52 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/parsing/yaml/builder/build.ts
> +export function composeSyntheticFilePath(filePath: string, functionName: string): string {
```suggestion
export function composeSyntheticFilePath(filePath: string, resourceName: string): string {
```

2022-08-31 14:52 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/parsing/yaml/builder/build.ts
> +    name: `${name}-${functionName}`,
```suggestion
    name: `${name}-${resourceName}`,
```

2022-08-31 14:52 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/parsing/yaml/builder/build.ts
> + * @param functionName
```suggestion
 * @param resourceName
```

2022-08-31 14:52 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/tests/parsing/yaml/parser/parse.test.ts
> +    expect(() => parseYaml([{ predicate, picker: noOpPicker }], filePath)).toThrow(
Same here.

2022-08-31 14:52 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/tests/parsing/yaml/parser/parse.test.ts
> +    const [embedded] = parseYaml([{ predicate, picker: noOpPicker }], filePath);
We could maybe extract `[{ predicate, picker: noOpPicker }]` into a `parsingContext` variable.

2022-09-01 09:05 UTC, merged