Add cloudformation test case to PR analysis integration tests
SonarSource/SonarJS pull request #3365
Opened 2022-09-06 14:59 UTC by francoismora

Fixes #3345

2022-09-09 15:41 UTC, vilchik-elena requested changes

2022-09-09 15:41 UTC, vilchik-elena commented on its/plugin/projects/pr-analysis-cloudformation-branch/file2.yaml
> +        console.log('Hello, World');;
let's add `// Noncompliant`

2022-09-09 15:41 UTC, vilchik-elena commented on its/plugin/projects/pr-analysis-cloudformation-main/file1.yaml
> +AWSTemplateFormatVersion: 2010-09-09
is it possible to add comment that this is same as in branch?

2022-09-09 15:41 UTC, vilchik-elena commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/PRAnalysisTest.java
> +        .logsTimes(String.format("INFO: %1$d/%1$d source files have been analyzed", Master.SOURCE_FILES), 2)
why is it logged twice?

2022-09-09 15:41 UTC, vilchik-elena commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/PRAnalysisTest.java
> +        .contains(projectKey + ":file1.yaml");
let's assert rule key

2022-09-12 09:20 UTC, francoismora commented on its/plugin/projects/pr-analysis-cloudformation-branch/file2.yaml
> +        console.log('Hello, World');;
Comment added

2022-09-12 09:21 UTC, francoismora commented on its/plugin/projects/pr-analysis-cloudformation-main/file1.yaml
> +AWSTemplateFormatVersion: 2010-09-09
Comment added

2022-09-12 09:25 UTC, francoismora commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/PRAnalysisTest.java
> +        .logsTimes(String.format("INFO: %1$d/%1$d source files have been analyzed", Master.SOURCE_FILES), 2)
Two sensors log the message. As this is no longer relevant to the test case, I removed this assertion from the class test cases.

2022-09-12 09:25 UTC, francoismora commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/PRAnalysisTest.java
> +        .contains(projectKey + ":file1.yaml");
Rule assertion added

2022-09-12 09:25 UTC, francoismora commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/PRAnalysisTest.java
> +        .contains(projectKey + ":file2.yaml");
Rule assertion added

2022-09-12 10:27 UTC, vilchik-elena approved these changes

2022-09-12 10:27 UTC, merged