Add cache strategy that uses the new caching API Francois Mora A minute ago
SonarSource/SonarJS pull request #3366
Opened 2022-09-06 15:50 UTC by francoismora

Fixes #3345

2022-09-12 15:03 UTC, saberduck requested changes

2022-09-13 11:15 UTC, francoismora commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/PRAnalysisTest.java
> +        .logsOnce("Cache strategy set to 'READ_AND_WRITE' for file 'file1.yaml'")
This change will be implemented in a separate PR

2022-09-13 11:15 UTC, francoismora commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBridgeServer.java
> +    String[] ucfgPaths = {};
This change will be implemented in a separate PR

2022-09-13 11:15 UTC, francoismora commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/CacheSerialization.java
> +class CacheSerialization {
This change will be implemented in a separate PR

2022-09-13 11:15 UTC, francoismora commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/CacheStrategy.java
> +      success = true;
This change will be implemented in a separate PR

2022-09-13 11:17 UTC, francoismora commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/CacheStrategy.java
> +      log(CacheStrategy.WRITE_ONLY, inputFile, "the current file is not cached");
Actually the message corresponds to the case where there's no cache entry for the file (`!isFileInCache`).

2022-09-13 11:17 UTC, francoismora commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/CacheStrategy.java
> +  void writeGeneratedFilesToCache(SensorContext context, InputFile inputFile, @Nullable String[] generatedFiles) throws IOException {
This change will be implemented in a separate PR

2022-09-13 11:17 UTC, francoismora commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/CacheStrategy.java
> +  private static final Logger LOG = Loggers.get(AnalysisMode.class);
Changed

2022-09-13 11:17 UTC, francoismora commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/CacheStrategy.java
> +enum CacheStrategy {
This change will be implemented in a separate PR

2022-09-13 11:18 UTC, francoismora commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/CacheStrategy.java
> +  private static String createCacheKey(SensorContext context, String category, InputFile inputFile) {
This change will be implemented in a separate PR

2022-09-13 12:00 UTC, saberduck approved these changes

2022-09-13 12:16 UTC, merged