Drop Node.js 12 support and deprecate Node.js 14
SonarSource/SonarJS pull request #3374
Opened 2022-09-13 08:51 UTC by yassin-kammoun-sonarsource

Fixes #3231 
Fixes #3357

2022-09-13 13:45 UTC, vilchik-elena requested changes
LGTM

2022-09-13 13:45 UTC, vilchik-elena commented on sonar-javascript-plugin/pom.xml
> +          <nodeJsMinVersion>14.20.0</nodeJsMinVersion>
change to 14.17

2022-09-13 13:45 UTC, vilchik-elena commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/NodeDeprecationWarning.java
> +  static final List<Integer> RECOMMENDED_NODE_VERSIONS = Arrays.asList(16);
should we create a ticket to add 18 to this list?

2022-09-13 13:45 UTC, vilchik-elena commented on sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/NodeDeprecationWarningTest.java
> +    assertWarnings("Node.js version 18 is not recommended, you might experience issues. Please use a recommended version of Node.js [16]");
it will conflict with another PR, be careful when merging

2022-09-13 13:45 UTC, vilchik-elena commented on sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/NodeDeprecationWarningTest.java
> +    var allRemovalDates = IntStream.range(MIN_SUPPORTED_NODE_VERSION.major(), MIN_RECOMMENDED_NODE_VERSION)
oops

2022-09-13 13:45 UTC, vilchik-elena commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/NodeDeprecationWarning.java
> +    entry(14, "April 1st, 2023"),
it should be may

2022-09-13 13:45 UTC, vilchik-elena commented on sonar-javascript-plugin/src/main/resources/static/documentation.md
> +machine running the scan. The recommended version is the latest LTS version - v16. We recommend using
`The recommended versions are v16 and v18. We recommend using the active LTS version of Node.js ....

2022-09-13 13:45 UTC, vilchik-elena commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/NodeDeprecationWarning.java
> +  static final Version MIN_SUPPORTED_NODE_VERSION = Version.create(14, 20, 0);
add comment why we have such a minor version as min (eslint requirement)

2022-09-13 14:35 UTC, yassin-kammoun-sonarsource commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/NodeDeprecationWarning.java
> +  static final List<Integer> RECOMMENDED_NODE_VERSIONS = Arrays.asList(16);
Created #3377

2022-09-13 15:30 UTC, vilchik-elena requested changes

2022-09-13 15:30 UTC, vilchik-elena commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/NodeDeprecationWarning.java
> +  static final List<Integer> RECOMMENDED_NODE_VERSIONS = Arrays.asList(16);
I expected to see `18` here as we put it in the doc already

2022-09-13 15:30 UTC, vilchik-elena commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/NodeDeprecationWarning.java
> + * 18 - nothing to warn, not recommended yet
`nothing to warn, recommended version`

2022-09-14 13:07 UTC, saberduck approved these changes

2022-09-14 13:09 UTC, merged