Extend comment-based testing framework with quick fix support
SonarSource/SonarJS pull request #3407
Opened 2022-09-23 15:06 UTC by victor-diez-sonarsource

Fixes #3047

2022-09-26 08:26 UTC, ilia-kebets-sonarsource commented
@victor-diez-sonarsource Could you update the DEV.md doc: https://github.com/SonarSource/SonarJS/blob/master/docs/DEV.md#testing-the-rule

2022-09-26 10:13 UTC, yassin-kammoun-sonarsource requested changes
Looks already nice, but we need further tests to validate the changes.`framework.test.ts` is the place to go to add further tests.

Also, we can entirely migrate `inverted-assertion-arguments.test.ts` and `no-exclusive-tests.test.ts`. That should be a good opportunity to validate the work on non-decorated rules.

Following @vilchik-elena's recent guidelines for commits and pull requests, please rename the PR title. I think you can just reuse the ticket's title.

Correct me if I am wrong, but I think we are currently not supporting multiple suggestions for a single issue like this: 

https://github.com/SonarSource/SonarJS/blob/b866d18e80746b6c4c93e1a6afa2bca4acf883ca/eslint-bridge/tests/linting/eslint/rules/decorators/use-isnan-decorator.test.ts#L33-L47

I think it's fine as a first step, but we should create a ticket to track this missing feature unless you really want to implement it now.

Finally, as @ilia-kebets-sonarsource mentioned, we need to document the quickfix support in the DEV documentation so that we know how to use it and what we are actually supporting.

2022-09-26 10:13 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/tests/tools/testers/comment-based/helpers/quickfixes.ts
> +    quickfix.fix = fix;
Should we add an assertion that checks that start is not greater than end? Not sure what's going to happen when we slice. In any case, we need a unit test for this corner case.

2022-09-28 09:36 UTC, yassin-kammoun-sonarsource approved these changes
Great work! That required much more work than expected, but we support plenty of cases. I think there are a few things that we can improve, but we can postpone them and create improvement tickets.

I left minor suggestions that you are free to ignore if you don't find them relevant.

2022-09-28 09:36 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/tests/tools/testers/comment-based/launcher.test.ts
> +const externalRules = decorateExternalRules({
Never thought of doing that. Great idea!

2022-09-28 09:36 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/tests/tools/testers/comment-based/launcher.test.ts
> +  if (['.ts', '.tsx'].includes(ext)) {
Ouch :(

2022-09-28 09:36 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/tests/tools/testers/comment-based/launcher.test.ts
> +    const rule = name.toLowerCase();
I don't think we have a rule that enforces lower-case. Did you encounter a case where this is needed?

2022-09-28 09:36 UTC, yassin-kammoun-sonarsource commented on docs/DEV.md
> +The issue primary location (`// ^^^^`), issue message, issue number (`N`) and quickfixes are optional.
```suggestion
The issue primary location (`// ^^^^`), issue message, issue number (`N`) and quick fixes are optional.
```

2022-09-28 09:36 UTC, yassin-kammoun-sonarsource commented on docs/DEV.md
> +`N` is an integer defining the amount of issues will be reported in the line.
```suggestion
`N` is an integer defining the number of issues that will be reported in the line.
```

2022-09-28 09:36 UTC, yassin-kammoun-sonarsource commented on docs/DEV.md
> +If no `N` nor messages are provided, the engine will expect one issue to be raised. Meaning, `//Noncompliant` is equivalent to `//Noncompliant 1`.
```suggestion
If neither `N` nor messages are provided, the engine will expect one issue to be raised. Meaning, `//Noncompliant` is equivalent to `//Noncompliant 1`.
```

2022-09-28 09:36 UTC, yassin-kammoun-sonarsource commented on docs/DEV.md
> +The `fix@` comment of a quickfix providing the suggestion description is optional. On the `edit@` comment the start column and end column are also optional, meaning this syntax can be used too:
```suggestion
The `fix@` comment of a quick fix providing the suggestion description is optional. On the `edit@` comment, the start column and end column are also optional, meaning this syntax can be used too:
```

2022-09-28 09:36 UTC, yassin-kammoun-sonarsource commented on docs/DEV.md
> +Please note the length of the list of quickfixes cannot surpass the amount of issues declared by `N` or the number of expected messages unless their matching issue is reassigned (see below).
```suggestion
Note that the length of the list of quick fixes cannot surpass the number of issues declared by `N` or the number of expected messages unless their matching issue is reassigned (see below). 
```

2022-09-28 09:36 UTC, yassin-kammoun-sonarsource commented on docs/DEV.md
> +* A *dummy* quickfix can be used as placeholder:
```suggestion
* A *dummy* quick fix can be used as placeholder:
```

2022-09-28 09:36 UTC, yassin-kammoun-sonarsource commented on docs/DEV.md
> +* Explicitly set the index (0-based) of the message to which the quickfix refers to with the grammar `=index` next to the quickfix ID:
```suggestion
* Explicitly set the index (0-based) of the message to which the quick fix refers to with the syntax `=index` next to the quick fix ID:
```

2022-09-28 09:36 UTC, yassin-kammoun-sonarsource commented on docs/DEV.md
> +// qf2 is declared but never used --> ignored by the engine
I think enforcing a convention for a quick fix identifier at some point would be nice. If the digit after `qf` is mandatory, we can identify to which issue it refers and avoid declaring a quick fix that is ignored. Maybe worth creating a ticket to improve that. WDYT?

2022-09-28 09:36 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/tests/tools/testers/comment-based/framework.ts
> + * Applies quickfix edits to a sourcecode line. The fixed line will be formed by a
```suggestion
 * Applies quick fix edits to a source code line. The fixed line will be formed by a
```

2022-09-28 09:36 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/tests/tools/testers/comment-based/framework.ts
> +              `End column cannot be in //Noncompliant comment ${end} > ${containsNC}`,
```suggestion
              `End column cannot be in // Noncompliant comment ${end} > ${containsNC}`,
```

2022-09-28 09:36 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/tests/tools/testers/comment-based/helpers/quickfixes.ts
> +  public fix: string | undefined = undefined;
I think those initializations are redundant.

2022-09-28 09:36 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/tests/tools/testers/comment-based/framework.test.ts
> +
Let's try to be consistent with the test above and define fixture files rather than inline code for both code and expected output.

2022-09-28 09:44 UTC, victor-diez-sonarsource commented on docs/DEV.md
> +// qf2 is declared but never used --> ignored by the engine
problem is that right now quick fix ids have to be unique file-wise. So a test cannot have multiple qf1 declared, if you want to have always the 1 pointing to the first issue of each issueLine.

2022-09-28 10:46 UTC, victor-diez-sonarsource commented on eslint-bridge/tests/tools/testers/comment-based/launcher.test.ts
> +    const rule = name.toLowerCase();
just in case we find a filename with any uppercase letter, to properly match against rule key

2022-09-28 11:10 UTC, merged