Filter out YAML files that are not AWS configurations for inline JavaScript
SonarSource/SonarJS pull request #3410
Opened 2022-09-26 13:48 UTC by ilia-kebets-sonarsource

Fixes #3388

2022-09-27 07:48 UTC, yassin-kammoun-sonarsource requested changes

2022-09-27 07:48 UTC, yassin-kammoun-sonarsource commented on sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/YamlSensorTest.java
> +    }
It's a good idea to pass the contents explicitly. However, using it as hack to inject the serverless header if the content is null is not so great. The tests are already convoluted enough, so let's try not to make it worse :)

2022-09-27 07:48 UTC, yassin-kammoun-sonarsource commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/YamlSensor.java
> +  }
This check is not enough to prevent the plugin from starting a Node.js process needlessly.

To give an example, let's assume that a project to analyze includes a YAML file denoting Inline AWS Lambda for Python. Provided that the configuration file includes the Serverless header, the file will therefore not be ignored, a Node.js process will be started, ESLint bridge will be deployed, and the latter will try to parse the YAML file and stops once it figures out that the runtime is different from Node.js. The problem here is that we are forcing the users to have Node.js runtime for every project including a YAML file with the expected header.

As explained in the GitHub issue, and in addition to the Serverless header, we need to look for any occurrence of Node.js runtime to accept the input file. A case-insensitive regular expression looking for `Runtime: nodejs` should do the trick. Furthermore, we need an integration test that checks that the plugin doesn't try to start a Node.js process and deploy ESLint bridge for the scenario I described above.

2022-09-27 12:05 UTC, ilia-kebets-sonarsource commented on sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/YamlSensorTest.java
> +    }
I've refactored it into this, WDYT? https://github.com/SonarSource/SonarJS/pull/3410/files#diff-b8698d58ef815e880646a3f6a4fac2af87ce96d67f50809e6c1684ba531908b6R235

2022-09-27 12:24 UTC, yassin-kammoun-sonarsource commented on sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/YamlSensorTest.java
> +    }
👍

2022-09-27 13:44 UTC, ilia-kebets-sonarsource commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/YamlSensor.java
> +  }
done

2022-09-27 14:51 UTC, yassin-kammoun-sonarsource commented
Reminder: we need to create a PR and update the integration tests on sonar-security to include the expected header, if not the case already. Also, we should merge both PRs on the same day, ideally at the same time to minimize a transient state where integration tests fail.

2022-09-28 07:56 UTC, yassin-kammoun-sonarsource commented
> Reminder: we need to create a PR and update the integration tests on sonar-security to include the expected header, if not the case already. Also, we should merge both PRs on the same day, ideally at the same time to minimize a transient state where integration tests fail.

Never mind this comment. The integration tests we introduced already include the header. No action should be required in the end.

2022-09-28 08:32 UTC, yassin-kammoun-sonarsource requested changes

2022-09-28 08:32 UTC, yassin-kammoun-sonarsource commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/YamlSensor.java
> +  public static final String NODEJS_RUNTIME_REGEX = "^\\s*Runtime:\\s*[\'\"]?nodejs\\S*[\'\"]?";
The regex doesn't work if there is any trailing whitespace or a comment.

2022-09-28 09:32 UTC, ilia-kebets-sonarsource commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/YamlSensor.java
> +  public static final String NODEJS_RUNTIME_REGEX = "^\\s*Runtime:\\s*[\'\"]?nodejs\\S*[\'\"]?";
I believe it will work, since I'm didn't include any end anchor. I checked on https://regex101.com/ using:
- choose `Java 8`
- `^\s*Runtime:\s*[\'\"]?nodejs\S*[\'\"]?` (I still don't know why it requires single escape)
- `      Runtime: nodejs12.x  #`

2022-09-28 09:40 UTC, yassin-kammoun-sonarsource commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/YamlSensor.java
> +  public static final String NODEJS_RUNTIME_REGEX = "^\\s*Runtime:\\s*[\'\"]?nodejs\\S*[\'\"]?";
I checked with jshell (Java REPL), and it didn't seem to work:

```
% jshell
|  Welcome to JShell -- Version 11.0.16
|  For an introduction type: /help intro

jshell> String regex = "^\\s*Runtime:\\s*[\'\"]?nodejs\\S*[\'\"]?"
regex ==> "^\\s*Runtime:\\s*['\"]?nodejs\\S*['\"]?"

jshell> "Runtime: nodejs12.x #".matches(regex)
$2 ==> false

jshell> "Runtime: nodejs12.x ".matches(regex)
$4 ==> false

jshell> "Runtime: nodejs12.x".matches(regex)
$4 ==> true
```

2022-09-28 11:30 UTC, ilia-kebets-sonarsource commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/YamlSensor.java
> +  public static final String NODEJS_RUNTIME_REGEX = "^\\s*Runtime:\\s*[\'\"]?nodejs\\S*[\'\"]?";
I changed the implementation, but kept the regex, since I was getting the S5852 flag if the regex ended with `.*`
@yassin-kammoun-sonarsource WDYT?

2022-09-28 11:39 UTC, yassin-kammoun-sonarsource commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/YamlSensor.java
> +  public static final String NODEJS_RUNTIME_REGEX = "^\\s*Runtime:\\s*[\'\"]?nodejs\\S*[\'\"]?";
👍

2022-09-28 11:41 UTC, ilia-kebets-sonarsource commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/YamlAnalysisTest.java
> +    assertThat(result.getLogsLines(log -> log.contains("Starting Node.js process"))).hasSize(0);
I'm getting `The main branch has no lines of code.` from SQ after running an analysis. It gets correctly ignored!

2022-09-28 11:46 UTC, ilia-kebets-sonarsource commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/YamlAnalysisTest.java
> +    assertThat(result.getLogsLines(log -> log.contains("Starting Node.js process"))).hasSize(0);
I can also see from the scanner logs that I'm not getting:

```
INFO: Sensor JavaScript inside YAML analysis [javascript]
INFO: 1 source file to be analyzed
INFO: 1/1 source file has been analyzed
INFO: Hit the cache for 0 out of 1
INFO: Miss the cache for 1 out of 1: ANALYSIS_MODE_INELIGIBLE [1/1]
INFO: Sensor JavaScript inside YAML analysis [javascript] (done) | time=4774ms
```

but

```
INFO: Sensor JavaScript inside YAML analysis [javascript]
INFO: No input files found for analysis
INFO: Hit the cache for 0 out of 0
INFO: Miss the cache for 0 out of 0
INFO: Sensor JavaScript inside YAML analysis [javascript] (done) | time=6ms
```

2022-09-28 11:56 UTC, yassin-kammoun-sonarsource approved these changes
Looks good to me. Nice job!

2022-09-28 11:56 UTC, yassin-kammoun-sonarsource commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/YamlSensor.java
> +        }
```suggestion
        // We check early the runtime to avoid making Node.js a mandatory dependency on projects that include YAML configuration files for AWS,
        // and we consider only those which define Node.js as the runtime, which potentially embed JavaScript code.
        Matcher lineMatch = regex.matcher(line);
        if (lineMatch.find()) {
          hasNodeJsRuntime = true;
        }
```

2022-09-28 11:56 UTC, yassin-kammoun-sonarsource commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/YamlAnalysisTest.java
> +    assertThat(result.getLogsLines(log -> log.contains("Starting Node.js process"))).hasSize(0);
Perfect! Thanks for double-checking.

2022-09-28 12:16 UTC, merged