Fix FP S4138 ('prefer-for-of'): Check if node does have an iterator to use for-of
SonarSource/SonarJS pull request #3423
Opened 2022-09-29 09:11 UTC by ilia-kebets-sonarsource

Fixes #3385

2022-09-30 16:15 UTC, ilia-kebets-sonarsource commented
I tried using `!` to affirm that the `rule.meta.messages` props exist, but the QG kicked me down, so I went with optional chaining that fails on coverage.

2022-10-03 07:06 UTC, yassin-kammoun-sonarsource requested changes
Let's close this PR without merging and open a PR in the RSPEC repository instead to update the rule description.

2022-10-03 07:06 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/linting/eslint/rules/decorators/prefer-for-of-decorator.ts
> +        ' In a browser environment, `NodeList` and other array-like collections should work by default. If you are using TypeScript and seeing a type error, make sure your configuration is correct.',
I don't think this kind of message should be part of the issue message. It should be moved in the rule description, that is, the RSPEC. Issue messages should be kept as short as possible as well as actionable.

2022-10-03 14:03 UTC, ilia-kebets-sonarsource commented
Closing this as we have modified the message in rspec: https://github.com/SonarSource/rspec/pull/1303

2022-10-03 14:03 UTC, closed without merging