Fix FP S1226 (`no-parameter-reassignment`): Allow inside if statements?
SonarSource/SonarJS pull request #3461
Opened 2022-10-07 12:44 UTC by victor-diez-sonarsource

Fixes #3364

2022-10-07 12:49 UTC, ilia-kebets-sonarsource requested changes
Can you add a test case and fix the checks, please?

2022-10-10 07:30 UTC, victor-diez-sonarsource commented
RSPEC update: https://github.com/SonarSource/rspec/pull/1322

2022-10-10 08:34 UTC, ilia-kebets-sonarsource commented on eslint-bridge/src/linting/eslint/rules/no-parameter-reassignment.ts
> +      ancestors[i + 1] === (ancestors[i] as estree.IfStatement).consequent
WDYT about defining a method:

```javascript
function isConsequentTo(ancestors, index) {
  return index < ancestors.length - 1 &&
  ancestors[index + 1] === (ancestors[index] as estree.IfStatement).consequent
}
```

2022-10-10 08:35 UTC, ilia-kebets-sonarsource approved these changes
LGTM, I just left a cosmetic proposal.

2022-10-10 09:49 UTC, merged