Add rule S6275: Using unencrypted EBS volumes is security-sensitive
SonarSource/SonarJS pull request #3483
Opened 2022-10-18 09:10 UTC by francoismora

Fixes #3418

2022-10-18 12:52 UTC, victor-diez-sonarsource requested changes

2022-10-18 14:27 UTC, francoismora commented on eslint-bridge/src/linting/eslint/rules/aws-opensearchservice-domain.ts
> +    function queryProperty(node: ObjectExpression, name: string): Result {
Code changed to use the new function.

2022-10-18 14:27 UTC, francoismora commented on eslint-bridge/src/linting/eslint/rules/aws-opensearchservice-domain.ts
> +      } else if (expression.type === 'SpreadElement') {
Check removed

2022-10-18 14:29 UTC, francoismora commented on eslint-bridge/src/linting/eslint/rules/aws-opensearchservice-domain.ts
> +        .map((object: ObjectExpression) => queryProperty(object, propertyName))
The `map()` method is used to simplify the logic by not requiring `if` statements.

2022-10-19 09:19 UTC, victor-diez-sonarsource approved these changes

2022-10-19 09:22 UTC, merged