Add Rule S6332: Using unencrypted EFS file systems is security-sensitive
SonarSource/SonarJS pull request #3485
Opened 2022-10-18 09:54 UTC by victor-diez-sonarsource

Fixes #3424

2022-10-18 15:03 UTC, francoismora requested changes

2022-10-18 15:24 UTC, victor-diez-sonarsource commented on eslint-bridge/src/linting/eslint/rules/aws-efs-unencrypted.ts
> +  if (props === undefined) {
Check rule description. We should only raise when encryption is explicitly set to false

2022-10-19 06:55 UTC, francoismora requested changes

2022-10-19 06:55 UTC, francoismora commented on eslint-bridge/tests/linting/eslint/rules/comment-based/aws-efs-unencrypted.js
> +new FileSystem(this, 'unencrypted-explicit', {vpc: new Vpc(this, 'VPC')});
The following case is missing:

```
new FileSystem(this, 'unencrypted-implicit', undefined);
```

2022-10-19 06:55 UTC, francoismora commented on eslint-bridge/tests/linting/eslint/rules/comment-based/aws-efs-unencrypted.js
> +new CfnFileSystem(this, 'unencrypted-explicit-cfn', {encrypted: false}); //Noncompliant {{Make sure that using unencrypted file systems is safe here.}}
The undefined case is also missing:
```
new CfnFileSystem(this, 'unencrypted-implicit-cfn', undefined);  // Noncompliant
```

2022-10-19 06:55 UTC, francoismora commented on eslint-bridge/src/linting/eslint/rules/aws-efs-unencrypted.ts
> +  if ((argument?.type === 'Identifier' && !isUndefined(argument)) || props === undefined) {
It looks like if `argument` is the literal `undefined` then `props` will be equal to `undefined` and the case will be ignored instead of being raised

2022-10-19 06:55 UTC, francoismora commented on eslint-bridge/src/linting/eslint/rules/helpers/ast.ts
> +        return undefined;
By returning undefined here, the function will not find the property enabled in the object literal:
```
{
   ...unknown, // returning undefined here
   enabled: true // enabled will not be picked up.
}
```

2022-10-19 08:00 UTC, francoismora approved these changes
LGTM

2022-10-19 08:16 UTC, merged