Fix FP S1128 (`unused-imports`): Vue.js imports used in templates
SonarSource/SonarJS pull request #3487
Opened 2022-10-18 12:53 UTC by ilia-kebets-sonarsource

Fixes #3484

2022-10-18 14:59 UTC, ilia-kebets-sonarsource commented
@yassin-kammoun-sonarsource I verified that putting back the code removed in that commit does indeed fix the FP: https://github.com/SonarSource/SonarJS/commit/03dc60ab105e0133e9d3b096038a38239a896e96

2022-10-19 07:24 UTC, yassin-kammoun-sonarsource requested changes
Lookgs good to me. However, could you update the definition of `languageFromFilePath` and take into account `.vue` files:

https://github.com/SonarSource/SonarJS/blob/ff94357392bc2b742ce4cdfe0a0d6d7ce2d836be/eslint-bridge/tests/tools/testers/comment-based/launcher.test.ts#L110-L117

You will need to pass the `fileContent` from `parseForESLint` and use this [regular expression](https://github.com/SonarSource/SonarJS/blob/d6b6ca841ef300235775bd611107bdf64e4117ab/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/JavaScriptFilePredicate.java#L32) to make the decision on the language of such a file.

There won't be a major impact, but by doing so, the comment-based testing framework will be closer to a `.vue` file analysis in production.

2022-10-19 07:24 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/tests/tools/testers/comment-based/helpers/comments.ts
> + */
```suggestion
```

2022-10-19 07:24 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/tests/tools/testers/comment-based/helpers/comments.ts
> + */
I don't think we need to duplicate this comment, especially because we can track back the change to the commit which introduced the change.

2022-10-19 07:24 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/tests/tools/testers/comment-based/helpers/file.ts
> +   * @param filePath used to know if it's Vue or not
```suggestion
   * @param filePath
```

2022-10-19 07:58 UTC, ilia-kebets-sonarsource commented on eslint-bridge/tests/tools/testers/comment-based/helpers/comments.ts
> + */
ack

2022-10-19 11:08 UTC, yassin-kammoun-sonarsource requested changes

2022-10-19 11:08 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/tests/tools/testers/comment-based/launcher.test.ts
> +  const hasScriptTagWithLangTs = /\\<script[.\\s]*lang=['\"]ts['\"][.\\s]*\\>/;
The regex doesn't seem to work. Because we are using a JavaScript regex literal here, the semantics is different from Java, and we can't copy-paste the regex because we don't need to escape characters.

Also, I realize now that the regex in the file predicate (as well as this one) does not support `<script setup...`. Let's fix the regex of `JavaScriptFilePredicate.java` in a different PR or have the change in this one but in a dedicated commit (which we should not squash when the time to merge comes).

Long story short, the regex should include `setup` and mark it as optional.

2022-10-19 16:01 UTC, ilia-kebets-sonarsource commented
@yassin-kammoun-sonarsource LMK if you're fine with the refactoring of the regex. If yes, I'll rebase this branch into 3 commits:
- Support VueJS test files in comment-based framework
- Fix FP S1128 (`unused-imports`): Vue.js imports used in templates on TS script
- Fix VueJS typescript filter

You can check the pre-last commit for another variant of the regex, but I prefer the one I settled on:
- the last: `/<script[^>]+lang=['"]ts['"][^>]*>/`
- the pre-last: `/<script[\s\S]*?lang=['"]ts['"][\s\S]*?>/`

2022-10-20 09:35 UTC, ilia-kebets-sonarsource commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/JavaScriptFilePredicate.java
> +  private static final String regex = "\\<script[^>]+lang=['\"]ts['\"][^>]*>";
@yassin-kammoun-sonarsource I have added 3 more test cases to illustrate my changes.

2022-10-20 13:22 UTC, merged