Improve S4423 (`weak-ssl`): Weak SSL/TLS protocols should not be used
SonarSource/SonarJS pull request #3493
Opened 2022-10-19 14:14 UTC by victor-diez-sonarsource

Fixes #3453

2022-10-20 14:29 UTC, yassin-kammoun-sonarsource requested changes

2022-10-20 14:29 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/linting/eslint/rules/weak-ssl.aws.ts
> +    }
S6330 and S6303 will likely need this logic to be consistent. Let's improve those once this is merged.

2022-10-20 14:29 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/tests/linting/eslint/rules/comment-based/weak-ssl.js
> +    securityPolicy: 'TLS_1_0' // NonCompliant
Let's assert the issue message as well as another one for the case when it's omitted.

2022-10-20 14:29 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/linting/eslint/rules/helpers/ast.ts
> +export function disallowedValue(
_Just thinking out loud..._

I am not a big fan of exporting this function in `ast.ts`. I am not convinced we will reuse it in the context of another sprint. At the same time, we are already duplicating enough code before coming up with a more refined rule template.

What do you think?

2022-10-20 14:34 UTC, victor-diez-sonarsource commented on its/ruling/src/test/java/org/sonar/javascript/it/JavaScriptRulingTest.java
> -      jsProject("amplify", "external/**", "test"),
oops

2022-10-20 14:34 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/linting/eslint/rules/weak-ssl.aws.ts
> +    }
👍

2022-10-20 14:39 UTC, victor-diez-sonarsource commented on eslint-bridge/src/linting/eslint/rules/helpers/ast.ts
> +export function disallowedValue(
I moved it here because I'm using it in 3 rules already. But I agree that we should reconsider where to put it once we are done.

2022-10-21 06:40 UTC, yassin-kammoun-sonarsource approved these changes

2022-10-21 07:20 UTC, merged