External tsconfig
SonarSource/SonarJS pull request #3551
Opened 2022-11-09 14:40 UTC by victor-diez-sonarsource

Fixes #3548

2022-11-11 10:31 UTC, vilchik-elena requested changes

2022-11-11 10:31 UTC, vilchik-elena commented on eslint-bridge/tests/services/program/program.test.ts
> +  it('missing external tsconfig should be different than found external tsconfig', () => {
that's a weird test. Why one tsconfig should be the same as another one?
I would have 2 tests asserting that for missing tsconfig we have empty options and `missingTsconfig` equal true. And for found one I would assert the values (not just that they are defined)

2022-11-11 10:31 UTC, vilchik-elena commented on its/plugin/projects/external-tsconfig-dependency-project/package-lock.json
> +{
do we need this file?

2022-11-11 10:31 UTC, vilchik-elena commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/ExternalTSConfigDependencyTest.java
> +      .setProperty("sonar.inclusions", "**/*.ts");
I don't think we need this one

2022-11-11 10:31 UTC, vilchik-elena commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBridgeServer.java
>      TsProgram(String error) {
you can call another constructor here

2022-11-11 10:31 UTC, vilchik-elena commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBridgeServer.java
>      TsProgram(String programId, List<String> files, List<String> projectReferences) {
you can call another constructor here

2022-11-11 10:31 UTC, vilchik-elena commented on sonar-javascript-plugin/src/test/resources/external-tsconfig/tsconfig.json
> +  "extends": "@tsconfig/node14/tsconfig.json",
why do we need all these files if you mock the response?

2022-11-11 10:31 UTC, vilchik-elena commented on eslint-bridge/src/services/program/program.ts
> +      console.log(`WARN Could not find extended tsconfig: ${file}`);
```suggestion
      console.log(`WARN Could not find extended tsconfig: ${file}; falling back to an empty configuration.`);
```

2022-11-11 12:33 UTC, victor-diez-sonarsource commented on eslint-bridge/tests/services/program/program.test.ts
> +    expect(() => createProgram(tsConfig)).toThrow();
because now createProgram does not return a Promise, we can just check it throws, instead of catching promise rejection

2022-11-11 12:35 UTC, victor-diez-sonarsource commented on sonar-javascript-plugin/src/test/resources/external-tsconfig/tsconfig.json
> +  "extends": "@tsconfig/node14/tsconfig.json",
I want to check it does not fail as it would before the change, when extended tsconfig which did not exist returned an error

2022-11-11 12:38 UTC, victor-diez-sonarsource commented on eslint-bridge/tests/services/program/program.test.ts
> +  it('missing external tsconfig should be different than found external tsconfig', () => {
because when empty config, typescript does not return empty options, just fills in some defaults. I just checked some instead of the whole list which may change as it depends on internal Typescript implementation. Also, some returned config does not  match fully what is in the tsconfig.json

2022-11-11 13:06 UTC, vilchik-elena commented on sonar-javascript-plugin/src/test/resources/external-tsconfig/tsconfig.json
> +  "extends": "@tsconfig/node14/tsconfig.json",
Ok, but at least we can remove package.json and package-lock

2022-11-11 13:11 UTC, vilchik-elena commented on eslint-bridge/tests/services/program/program.test.ts
> +  it('missing external tsconfig should be different than found external tsconfig', () => {
then assert that options are not equal
Also why not asserting values of `configMissing` and `configFound`

2022-11-17 08:35 UTC, vilchik-elena requested changes

2022-11-17 08:35 UTC, vilchik-elena commented on eslint-bridge/tests/services/program/program.test.ts
> +      projectReferences.map(p => p),
why is it noop now?

2022-11-17 08:35 UTC, vilchik-elena commented on eslint-bridge/tests/services/program/program.test.ts
> +    const tsConfig = path.join(fixtures, `tsconfig_missing.json`);
here and further you use backticks for now reason

2022-11-17 08:35 UTC, vilchik-elena commented on eslint-bridge/tests/services/program/program.test.ts
> +    expect(() => createProgramOptions(tsConfigMissing, configHost)).toThrow();
I don't like exposing host as parameter of `createProgramOptions` just to test here. I would copy the required logic from the main code to some test function.

2022-11-17 08:35 UTC, vilchik-elena commented on eslint-bridge/src/services/program/program.ts
> +    tsConfig = path.join(tsConfig, 'tsconfig.json');
we should not overwrite parameter value

2022-11-17 08:35 UTC, vilchik-elena commented on sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/TypeScriptSensorTest.java
> +  void should_analyze_by_program_on_missing_extended_tsconfig() throws Exception {
can we assert that an analysis warning is created?

2022-11-17 10:13 UTC, vilchik-elena approved these changes

2022-11-17 11:17 UTC, merged