Generate wildcard TSConfig for JavaScript in SonarLint
SonarSource/SonarJS pull request #3563
Opened 2022-11-16 16:41 UTC by francoismora

Fixes #3562

This PR generates temporary `tsconfig.json` files for every project for files analyzed with the JavaScript sensor. It also uses the SonarLint API `ModuleFileSystem` to determine if the project is not exceeding a configured limit by setting the max number of lines with `sonar.javascript.sonarlint.type.maxlines`.

2022-11-17 12:35 UTC, yassin-kammoun-sonarsource requested changes

2022-11-17 12:35 UTC, yassin-kammoun-sonarsource commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/TsConfigProvider.java
> +  static class SonarLintProvider implements Provider {
```suggestion
  static class SonarLintTsConfigProvider implements Provider {
```

2022-11-17 12:35 UTC, yassin-kammoun-sonarsource commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/TsConfigProvider.java
> +  static class AnalysedFileTsConfigProvider extends GeneratedTsConfigFileProvider {
Didn't we agree yesterday that we would drop that feature?

2022-11-17 12:35 UTC, yassin-kammoun-sonarsource commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/TsConfigProvider.java
> +        provider = new AnalysedFileTsConfigProvider();
Didn't we agree yesterday that we would drop that feature? Either we are able to generate a wildcard TSConfig or we return an empty list.

2022-11-17 12:35 UTC, yassin-kammoun-sonarsource commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/TsConfigProvider.java
> +  static class WildcardTsConfigProvider extends GeneratedTsConfigFileProvider {
Let's merge this with `SonarLintTsConfigProvider`. Although it's nicely designed, I think we are introducing too many abstractions for what it is worth. Let's keep in mind that most of the changes we are bringing here are likely to disappear once we delegate the TSConfig generation to ESLint bridge.

2022-11-17 12:35 UTC, yassin-kammoun-sonarsource commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/TsConfigProvider.java
> +
I think we can make this a static final property and avoid calling this method many times. Furthermore, we can probably remove the extra `compilerOptions` parameter from Provider-like constructors because we always use the default one when we generate a TSConfig (unless I am mistaken) and we don't even care about compiler options when we use a TSConfig provided by the user.

2022-11-17 12:35 UTC, yassin-kammoun-sonarsource commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/SonarLintJavaScriptProjectChecker.java
> +    return total;
Let's just compute the total number of lines for the log above to print consistent data. Probably doable in a one-line using the functional API.

2022-11-17 12:35 UTC, yassin-kammoun-sonarsource commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/SonarLintJavaScriptProjectChecker.java
> +    return total;
I guess you wanted to avoid overflows, but given the value of `Long.MAX_VALUE`, it's unlikely for a project to have this many lines of code, especially given the default value we define.

2022-11-17 12:35 UTC, yassin-kammoun-sonarsource commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/TsConfigProvider.java
> +    }
You will see below that I suggest to drop `AnalysedFileTsConfigProvider`. I am not entirely sure, but we probably won't need it anymore, and in my opinion, we shouldn't add this method if not both JavaScript and TypeScript sensors use it.

2022-11-17 13:31 UTC, francoismora commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/SonarLintTest.java
> +    var extension = "js";
Inlined

2022-11-17 13:32 UTC, francoismora commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/JavaScriptPlugin.java
> +    } else {
Thanks

2022-11-17 13:32 UTC, francoismora commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/JavaScriptPlugin.java
> +  }
Unit test added

2022-11-17 13:32 UTC, francoismora commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/SonarLintTest.java
> +  void should_analyze_with_typed_rules() throws IOException {
Renamed

2022-11-17 13:32 UTC, francoismora commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/JavaScriptEslintBasedSensor.java
> +
Inlined

2022-11-17 13:32 UTC, francoismora commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/SonarLintJavaScriptProjectChecker.java
> +
Reordered

2022-11-17 13:33 UTC, francoismora commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/SonarLintJavaScriptProjectChecker.java
> +  static final String MAX_LINES_PROPERTY = "sonar.javascript.sonarlint.type.maxlines";
Renamed

2022-11-17 13:33 UTC, francoismora commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/SonarLintJavaScriptProjectChecker.java
> +    return moduleFileSystem.files().filter(predicate).collect(toList());
Inlined

2022-11-17 13:33 UTC, francoismora commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/SonarLintJavaScriptProjectChecker.java
> +  private boolean shouldBuild = true;
Renamed to `shouldCheck`

2022-11-17 13:35 UTC, francoismora commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/SonarLintJavaScriptProjectChecker.java
> +    beyondLimit = numberOfLines >= maxLinesForTypeChecking;
The variable `numberOfLines` is capped to maxLinesForTypeChecking so this proposed change won't work.

2022-11-17 13:39 UTC, francoismora commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/SonarLintJavaScriptProjectChecker.java
> +        numberOfLines, maxLinesForTypeChecking);
The rationale is to avoid loading files and counting lines when the limit has been reached. This way the check computation time won't grow with the number of files but will be capped to the configured limit. The drawback is that we don't know the total size. But we could compute this value if the logging level is DEBUG. WDYT?

2022-11-17 13:39 UTC, francoismora commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/SonarLintJavaScriptProjectChecker.java
> +      // Avoid performance issues for large projects
Updated

2022-11-17 13:39 UTC, francoismora commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/SonarLintJavaScriptProjectChecker.java
> +  private static final long DEFAULT_MAX_LINES_FOR_INDEXING = 1_000_000L;
Renamed

2022-11-17 14:35 UTC, yassin-kammoun-sonarsource commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/JavaScriptProjectChecker.java
> +  void checkOnce(SensorContext context);
Thanks for the clarification.

2022-11-17 15:00 UTC, francoismora commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/JavaScriptProjectChecker.java
> +package org.sonar.plugins.javascript.eslint;
I can propose a separate PR for this. WDYT

2022-11-17 15:00 UTC, francoismora commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/TsConfigProvider.java
> +  static class SonarLintProvider implements Provider {
Renamed

2022-11-17 15:25 UTC, francoismora commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/TsConfigProvider.java
> +
Simplified

2022-11-17 15:38 UTC, francoismora commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/SonarLintJavaScriptProjectChecker.java
> +    beyondLimit = numberOfLines >= maxLinesForTypeChecking;
Refactored to compute the total number of lines when needed by DEBUG logs.

2022-11-17 15:39 UTC, francoismora commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/SonarLintJavaScriptProjectChecker.java
> +        numberOfLines, maxLinesForTypeChecking);
Refactored to compute the total number of lines when needed by DEBUG logs.

2022-11-17 15:39 UTC, francoismora commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/TsConfigProvider.java
> +  static class AnalysedFileTsConfigProvider extends GeneratedTsConfigFileProvider {
Feature removed from this PR

2022-11-17 15:40 UTC, francoismora commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/TsConfigProvider.java
> +  static class WildcardTsConfigProvider extends GeneratedTsConfigFileProvider {
Merged

2022-11-17 15:40 UTC, francoismora commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/SonarLintJavaScriptProjectChecker.java
> +    return total;
Refactored to compute the total number of lines when needed by DEBUG logs.

2022-11-17 15:41 UTC, francoismora commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/TsConfigProvider.java
> +    }
Feature removed from this PR

2022-11-18 07:58 UTC, yassin-kammoun-sonarsource commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/JavaScriptProjectChecker.java
> +package org.sonar.plugins.javascript.eslint;
Sure, let's do that in a separate PR.

2022-11-18 10:57 UTC, yassin-kammoun-sonarsource requested changes

2022-11-18 10:57 UTC, yassin-kammoun-sonarsource commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/TsConfigProvider.java
> +    }
In fact, I now realize that we could directly move it to the TsConfig class and remove the extra compilerOptions parameter.

2022-11-18 10:57 UTC, yassin-kammoun-sonarsource commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/TsConfigProvider.java
> +      var config = new TsConfig(List.of(root + "/**/*"), DEFAULT_COMPILER_OPTIONS);
```suggestion
      var config = new TsConfig(singletonList(root + "/**/*"), DEFAULT_COMPILER_OPTIONS);
```

2022-11-18 10:57 UTC, yassin-kammoun-sonarsource commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/TsConfigProvider.java
> +  abstract static class GeneratedTsConfigFileProvider implements Provider {
_TL;DR_

Now that I look at what we did for the generated TSConfig providers as it is already polished and finished, there are a few things that are bothering me:

1. We are coupling logic about generating TSConfig with logic about specific conditions for SonarLint in the case of the wildcard TSConfig. I have a feeling that this should be extracted to the relevant sensors and keep the providers flexible. I would prefer to keep TSConfig providers agnostic of the context on how they will be used.
2. For the wildcard TSConfig, we use `TsConfig#writeFileWith` to generate the actual file, while we use `DefaultTsConfigProvider#writeToJsonFile ` for the default TSConfig. We rely on two different abstraction paths to write a file, which is confusing me.

We've spent enough time on that, so I am not going to create more frictions on it, but for what it's worth, here is a suggestion for a clearer design in my opinion:

```java
abstract static class GeneratedTsConfigFileProvider implements Provider {

  protected TsConfigWriter writer;

  GeneratedTsConfigFileProvider(TsConfigWriter writer) {
    this.writer = writer;
  }

  interface TsConfigWriter {
    File write(TsConfig config) throws IOException;
  }

  static class TsConfig {
    List<String> files;
    List<String> include;
    Map<String, Object> compilerOptions = Map.of(
      "allowJs", true,
      "noImplicitAny", true);

    TsConfig(Iterable<InputFile> inputFiles) {
      this(inputFiles, null);
    }

    TsConfig(List<String> include) {
      this(null, include);
    }

    TsConfig(@Nullable Iterable<InputFile> inputFiles, @Nullable List<String> include) {
      if (inputFiles != null) {
        files = new ArrayList<>();
        inputFiles.forEach(f -> files.add(f.absolutePath()));
      } else {
        this.include = include;
      }
    }
  }

  static class FileListTsConfigFileProvider extends GeneratedTsConfigFileProvider {

    private final Function<FileSystem, FilePredicate> filePredicate;

    FileListTsConfigFileProvider(TsConfigWriter writer, Function<FileSystem, FilePredicate> filePredicate) {
      super(writer);
      this.filePredicate = filePredicate;
    }

    @Override
    public List<String> tsconfigs(SensorContext context) throws IOException {
      var inputFiles = context.fileSystem().inputFiles(filePredicate.apply(context.fileSystem()));
      var tsConfig = new TsConfig(inputFiles);
      var tsConfigFile = writer.write(tsConfig);
      LOG.debug("Using generated tsconfig.json file listing files {}", tsConfigFile.getAbsolutePath());
      return singletonList(tsConfigFile.getAbsolutePath());
    }
  }

  static class WildcardTsConfigFileProvider extends GeneratedTsConfigFileProvider {

    private static final Map<String, List<String>> tsConfigCache = new ConcurrentHashMap<>();

    WildcardTsConfigFileProvider(TsConfigWriter writer) {
      super(writer);
    }

    @Override
    public List<String> tsconfigs(SensorContext context) throws IOException {
      var root = getProjectRoot(context);
      if (tsConfigCache.containsKey(root)) {
        return tsConfigCache.get(root);
      } else {
        var tsConfig = new TsConfig(singletonList(root + "/**/*"));
        var tsConfigFile = writer.write(tsConfig);
        LOG.debug("Using generated tsconfig.json file using wildcard {}", tsConfigFile.getAbsolutePath());
        return tsConfigCache.put(root, singletonList(tsConfigFile.getAbsolutePath()));
      }
    }

    private static String getProjectRoot(SensorContext context) {
      var projectBaseDir = context.fileSystem().baseDir().getAbsolutePath();
      return "/".equals(File.separator) ? projectBaseDir : projectBaseDir.replace(File.separator, "/");
    }
  }
}
```

With this design, we would need to move the logic about SonarLint context, typing limit check, and so forth on the JavaScript sensor.

If you think this proposition is not worth it, feel free to ignore it. I won't take it badly :)

2022-11-18 11:07 UTC, yassin-kammoun-sonarsource commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/TsConfigProvider.java
> +  abstract static class GeneratedTsConfigFileProvider implements Provider {
Maybe not worth it with the generation delegation to the bridge, wdyt?

2022-11-18 12:37 UTC, francoismora commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/JavaScriptEslintBasedSensor.java
> +    JavaScriptProjectChecker.checkOnce(javaScriptProjectChecker, context);
Moved

2022-11-18 12:38 UTC, francoismora commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/JavaScriptEslintBasedSensor.java
> +        fileContent, contextUtils.ignoreHeaderComments(), tsConfigs, null,
Reverted

2022-11-18 12:38 UTC, francoismora commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/SonarLintJavaScriptProjectChecker.java
> +  }
Moved

2022-11-18 12:39 UTC, francoismora commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/SonarLintJavaScriptProjectChecker.java
> +    }
When testing in VSCode, I noticed that in some cases, the SonarLint API is throwing a runtime exception.

2022-11-18 12:43 UTC, francoismora commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/SonarLintJavaScriptProjectChecker.java
> +      } else if (LOG.isDebugEnabled()) {
The test on the log level allows paying the cost of computing the total number of lines only if the log message is going to be displayed.

2022-11-18 12:49 UTC, francoismora commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/SonarLintJavaScriptProjectChecker.java
> +          cappedNumberOfLines, maxLinesForTypeChecking);
The value is accurate as the code checks it's not capped before. Also, the value can still be useful in order to have an idea of the project size.

2022-11-18 12:49 UTC, yassin-kammoun-sonarsource commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/SonarLintJavaScriptProjectChecker.java
> +    }
That's a good precaution then :). Could you mention that in a comment so that we remember why we added it?

2022-11-18 12:52 UTC, yassin-kammoun-sonarsource commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/SonarLintJavaScriptProjectChecker.java
> +          cappedNumberOfLines, maxLinesForTypeChecking);
👍

2022-11-18 12:52 UTC, yassin-kammoun-sonarsource commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/SonarLintJavaScriptProjectChecker.java
> +      } else if (LOG.isDebugEnabled()) {
I see, thanks for the clarification.

2022-11-18 12:56 UTC, francoismora commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/TsConfigProvider.java
> +    }
Variable moved. FYI `Map.of()` doesn't respect ordering which makes unit tests fail randomly.

2022-11-18 12:56 UTC, francoismora commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/TsConfigProvider.java
> +      var config = new TsConfig(List.of(root + "/**/*"), DEFAULT_COMPILER_OPTIONS);
Changed

2022-11-18 13:11 UTC, francoismora commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/TsConfigProvider.java
> +  abstract static class GeneratedTsConfigFileProvider implements Provider {
I think this PR should only add type-checking for JavaScript files. We could then consider changes impacting the analysis of TypeScript files separately. This way of proceeding adds, I think, clarity to the work to improve the overall analyzer implementation by underlining the multiple steps and their individual effort.

2022-11-18 13:23 UTC, yassin-kammoun-sonarsource approved these changes
Nice job 👍

2022-11-18 14:07 UTC, merged