Count JS/TS files using java API to determine if project is beyond limit
SonarSource/SonarJS pull request #3606
Opened 2022-12-07 15:17 UTC by francoismora

The PR uses the Java API to count the analyzed project JS/TS files. This metric is used to determine if the default generation of a tsconfig.json file specifying the project files with a general wildcard expression will be fast enough for SonarLint. The use of the Java API is best suited for this use case as it counts the same files that the TypeScript compiler will parse.

2022-12-09 14:35 UTC, vilchik-elena requested changes
Overall everything is good, please fix some minor things

2022-12-09 14:47 UTC, francoismora commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/SonarLintProjectChecker.java
> +        LOG.debug("Project type checking for JavaScript files deactivated due to project size (maximum is {} files)", maxFilesForTypeChecking);
We can't because `beyondLimit` is `true` which means `cappedFileCount` is equal to `maxFilesForTypeChecking`. The goal is to stop counting files when we reached the configured maximum `DEFAULT_MAX_FILES_FOR_TYPE_CHECKING`.

2022-12-09 14:48 UTC, francoismora commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/SonarLintProjectChecker.java
> +        // We can't inform the user of the actual limit as the performance impact may be too high for large projects.
I will rephrase to:

> [...] of the actual number of files [...]

2022-12-09 15:00 UTC, vilchik-elena commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/SonarLintProjectChecker.java
> +        LOG.debug("Project type checking for JavaScript files deactivated due to project size (maximum is {} files)", maxFilesForTypeChecking);
then let's be more explicit about the condition: `Project type checking for JavaScript files deactivated as project has too many files`

2022-12-09 18:23 UTC, francoismora commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/SonarLintProjectChecker.java
> +    try (var files = Files.walk(context.fileSystem().baseDir().toPath(), FILE_WALK_MAX_DEPTH)) {
Changed

2022-12-09 18:24 UTC, francoismora commented on sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/SonarLintProjectCheckerTest.java
>    void should_detect_too_big_projects() throws IOException {
Changed

2022-12-09 18:24 UTC, francoismora commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/SonarLintProjectChecker.java
> +        LOG.debug("Project type checking for JavaScript files deactivated due to project size (maximum is {} files)", maxFilesForTypeChecking);
Changed

2022-12-09 18:24 UTC, francoismora commented on sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/SonarLintProjectCheckerTest.java
>      when(file.filename()).thenReturn(filename);
Removed

2022-12-12 08:55 UTC, vilchik-elena requested changes
Please extract the unit tests for file walker in a separate file

2022-12-12 09:31 UTC, francoismora commented
> Please extract the unit tests for file walker in a separate file

Thanks, I actually isolated the PathWalker class at the very end and forgot to move its tests as well.

2022-12-13 12:52 UTC, vilchik-elena approved these changes

2022-12-13 12:53 UTC, merged