WIP: first draft of using htmlparser2 based on eslint-plugin-html
SonarSource/SonarJS pull request #3674
Opened 2023-01-23 17:22 UTC by ilia-kebets-sonarsource

2023-02-03 06:20 UTC, ilia-kebets-sonarsource commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/AnalysisProcessor.java
> +      LOG.warn(issue.ruleId + issue.message + file.uri() + issue.line, e);
@victor-diez-sonarsource Why do we not throw anymore?

2023-02-03 13:54 UTC, yassin-kammoun-sonarsource requested changes

2023-02-03 13:54 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/tests/parsing/html/parser/parse.test.ts
> +    expect(embeddedJs).toEqual(
I remember we discussed during a weekly about conventions regarding variable naming with `Ts` and `TS`. I think we agreed on `TS`, and it probably makes sense to apply the same for `Js` vs. `JS`.

2023-02-03 13:54 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/tests/parsing/html/parser/parse.test.ts
> +    const filePath = path.join(__dirname, '..', 'fixtures', 'simple.html');
Not a big fan of having this `../fixtures` folder shared between the directories `parser` and `builder`. Originally, during the refactoring, I established this convention (Yes I know, I am a dictator) of having local fixtures per directory to avoid using test fixtures for multiple testing purposes and to be intentional when writing tests.

I am okay to keep it like but I am afraid we will start taking bad habits that we used to have before the refactoring.

2023-02-03 13:54 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/tests/parsing/html/parser/parse.test.ts
> +    const [embeddedJs] = embeddedJss;
Do we really need those cumbersome intermediate assertions?

2023-02-03 13:54 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/tests/parsing/html/parser/parse.test.ts
> +    const [embeddedJs] = embeddedJss;
```suggestion
    const [embeddedJs]= parseHTML(fileContent);
```

2023-02-03 13:54 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/tests/parsing/html/fixtures/simple.html
> +some HTML YOLO
Very funny but I would rather have something less YOLO and more HTML merged on master ^^

2023-02-03 13:54 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/tests/parsing/html/builder/build.test.ts
> +    const sourceCodes = buildSourceCodes(await yamlInput({ filePath }), 'html');
`yamlInput` ?

2023-02-03 13:54 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/tests/parsing/html/parser/parse.test.ts
> +
Can `htmlparser2` generate a parsing error? Is there a way to write a unit test for that?

2023-02-03 13:54 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/tests/parsing/html/parser/parse.test.ts
> +});
Unless I missed it, should we add a test case for an HTML file with multiple scripts, meaning multiple embedded JavaScript? Maybe we don't support it.

2023-02-03 13:54 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/services/analysis/analyzers/yaml/analyzer.ts
>   * @returns the YAML analysis output
The documentation is outdated now that we introduced the concept of embedded to distinguish YAML from HTML.

2023-02-03 13:54 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/services/analysis/analyzers/yaml/analyzer.ts
> +  input: YamlAnalysisInput,
`EmbeddedAnalysisInput`?

2023-02-03 13:54 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/services/analysis/analyzers/yaml/analyzer.ts
> +): YamlAnalysisOutput {
`EmbeddedAnalysisInput`?

2023-02-03 13:54 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/services/analysis/analyzers/yaml/analyzer.ts
> +  language: Language = 'yaml',
I would avoid the facility of not updating unit tests and remove the default value to be intentional and explicit about what kind of embedded JavaScript we intend to analyze.

2023-02-03 13:54 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/services/analysis/analyzers/yaml/analyzer.ts
>  import { SourceCode } from 'eslint';
I would now rename the current folder from `analyzers/yaml/analyzer.ts` to `analyzers/embedded/analyzer.ts`.

2023-02-03 13:54 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/services/analysis/analyzers/yaml/analyzer.ts
>    for (const extendedSourceCode of extendedSourceCodes) {
Let's clean up the file and replace every occurrence of YAML with Embedded.

2023-02-03 13:54 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/tests/parsing/html/builder/build.test.ts
> +  it('throw an error if the language is unknown', async () => {
As mentioned above, trust the type system and avoid throwing an exception for something that we control locally. Let's remove this unit test.

2023-02-03 13:54 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/routing/on-analyze-html.ts
> + * Handles TypeScript analysis requests
```suggestion
 * Handles HTML analysis requests
```

2023-02-03 13:54 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/parsing/jsts/language.ts
> +export type Language = 'js' | 'ts' | 'html';
Is this change a mistake? Is this `'html'` constant expected to be used somewhere? We didn't need to add a constant for YAML, I am just wondering why we would need one for HTML.

2023-02-03 13:54 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/parsing/embedded/parser/parse-html.ts
> +      if (!javaScriptTagNames.includes(name)) {
Couldn't we just inline the string literal `'script'` and have instead `name === 'script'` (or have `const ScriptTag = 'script'` instead)? I am just trying to understand the motivation of having this one-element constant array.

2023-02-03 13:54 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/parsing/embedded/parser/parse-html.ts
> +      if (attrs.src) {
Let's explain why we ignore script tags that define a `src` property.

2023-02-03 13:54 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/parsing/embedded/parser/parse-html.ts
> +  parser.parseComplete(code);
Do you know if it can throw a runtime error if there is a parsing failure? Can there be any parsing failure with this library?

2023-02-03 13:54 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/parsing/embedded/parser/parse-html.ts
> +export function parseHTML(code: string) {
We can maybe document a bit this function and briefly explain the overall approach of parsing JavaScript code inside HTML files.

2023-02-03 13:54 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/parsing/embedded/parser/parse-html.ts
> +export function parseHTML(code: string) {
Let's add the return type of the function for readibility.

2023-02-03 13:54 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/parsing/embedded/parser/embedded-js.ts
> + * @param lineStarts Offset at each line start for the whole file (not only embedded JS)
There are some YAML-specific references here and there in this file. Let's rather use the concept of Embedded as of now.

2023-02-03 13:54 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/parsing/embedded/builder/build.ts
> +  input: YamlAnalysisInput,
`YamlAnalysisInput`?

2023-02-03 13:54 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/parsing/embedded/builder/build.ts
> +export function buildSourceCodes(
The function documentation should no longer mention YAML but just regular embedded JavaScript code.

2023-02-03 13:54 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/parsing/embedded/builder/build.ts
> +  language: Language = 'yaml',
I would avoid relying on a default value and be instead intentional when calling this function about what type of file we are trying to extract embedded JavaScript code and build source code for it.

2023-02-03 14:18 UTC, ilia-kebets-sonarsource commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintRule.java
> +      .filter(rule -> ! blackListRuleKeys.contains(rule.key))
Yeah, I think it's more readable.

2023-02-03 14:18 UTC, ilia-kebets-sonarsource commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintRule.java
> +      .filter(rule -> ! blackListRuleKeys.contains(rule.key))
but I don't mind if you're opposed to it.

2023-02-03 14:19 UTC, ilia-kebets-sonarsource commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintRule.java
> +  public String getKey() {
should public methods be declared at the top?

2023-02-03 14:19 UTC, ilia-kebets-sonarsource commented on sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/TestUtils.java
> +  public static DefaultInputFile createInputFile(SensorContextTester sensorContext, String content, String relativePath, String language) {
@victor-diez-sonarsource can you check, pls?

2023-02-03 14:38 UTC, yassin-kammoun-sonarsource commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintRule.java
> +  public String getKey() {
I don't remember, but we agreed to just apply https://sonarsource.github.io/rspec/#/rspec/S1213.

2023-02-03 14:52 UTC, victor-diez-sonarsource commented on eslint-bridge/src/parsing/jsts/language.ts
> +export type Language = 'js' | 'ts' | 'html';
yes, leftover from eslint-html branch back in december

2023-02-03 14:56 UTC, yassin-kammoun-sonarsource commented on sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintRule.java
> +      .filter(rule -> ! blackListRuleKeys.contains(rule.key))
I am fine with keeping it as it is.

2023-02-03 15:07 UTC, victor-diez-sonarsource commented on eslint-bridge/src/services/analysis/analyzers/yaml/analyzer.ts
>  import { SourceCode } from 'eslint';
that's already the case. what do you mean?

2023-02-03 15:15 UTC, victor-diez-sonarsource commented on sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/TestUtils.java
> +  public static DefaultInputFile createInputFile(SensorContextTester sensorContext, String content, String relativePath, String language) {
I added that one to be able to pass the language explicitly, otherwise it's taken from file extension

2023-02-03 15:33 UTC, victor-diez-sonarsource commented on eslint-bridge/src/parsing/embedded/parser/parse-html.ts
> +  parser.parseComplete(code);
as agreed, the library does not provide error handler.  if it crashes it will be catch by express error handler

2023-02-06 14:44 UTC, yassin-kammoun-sonarsource approved these changes
Looks good to me. There are minor things left to address except for the more important one about the fixed version in the package.json file. We can merge once those are addressed, no need to request another review.

Great job guys!

2023-02-06 14:44 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/package.json
> +    "htmlparser2": "^8.0.1",
Still not fixed :)

2023-02-06 14:44 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/tests/parsing/html/builder/build.test.ts
> +  it('should build source code from an HTML file', async () => {
```suggestion
  it('should build source codes from an HTML file', async () => {
```

2023-02-06 14:44 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/tests/parsing/yaml/builder/patch.test.ts
> +import { JsTsAnalysisInput, EmbeddedAnalysisInput } from 'services/analysis';
We can rename the ancestor folder from `tests/parsing/yaml/...` to `tests/parsing/embedded/...`

2023-02-06 14:44 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/parsing/embedded/builder/patch.ts
> +import { EmbeddedJS } from 'parsing/embedded';
There are some YAML-references in a few comments below that we can get rid of.

2023-02-06 14:55 UTC, ilia-kebets-sonarsource commented on eslint-bridge/src/parsing/embedded/builder/build.ts
> +    embeddedJSs = parseAwsFromYaml(input.fileContent);
@yassin-kammoun-sonarsource It does indeed parse AWS YAML stuff only. We extract YAML inside AWS serverless functions.

2023-02-06 14:56 UTC, ilia-kebets-sonarsource commented on eslint-bridge/src/parsing/embedded/builder/build.ts
> +    embeddedJSs = parseAwsFromYaml(input.fileContent);
Therefore, I would leave it as `parseAwsFromYaml`

2023-02-06 14:57 UTC, yassin-kammoun-sonarsource commented on eslint-bridge/src/parsing/embedded/builder/build.ts
> +    embeddedJSs = parseAwsFromYaml(input.fileContent);
Right, I remember now. Thanks!

2023-02-07 08:42 UTC, ilia-kebets-sonarsource commented on eslint-bridge/tests/parsing/yaml/builder/patch.test.ts
> +import { JsTsAnalysisInput, EmbeddedAnalysisInput } from 'services/analysis';
moved both `test/parsing/yaml` and `tests/parsing/html` under `tests/parsing/embedded/{yaml, html}`

2023-02-07 09:35 UTC, merged