Refactor plugin structure
SonarSource/SonarJS pull request #3713
Opened 2023-02-17 09:14 UTC by saberduck

2023-02-27 13:47 UTC, francoismora approved these changes
LGTM

2023-02-27 13:47 UTC, francoismora commented on package.json
> +    "mvn-copy": "cd sonar-plugin && mkdirp sonar-javascript-plugin/target/classes && cp ../sonarjs-1.0.0.tgz sonar-javascript-plugin/target/classes",
SonarLint VisualStudio has the filename `eslint-bridge-1.0.0.tgz` [defined](https://github.com/SonarSource/sonarlint-visualstudio/blob/63a9400ef82f8e62298b8ab2eb433723dc17a8f8/build/DownloadSonarPlugin/DownloadAndExtractSonarJS.cs#L54) on their side too. So they should change it, too, after the PR.

2023-02-27 14:12 UTC, ilia-kebets-sonarsource requested changes
- The `npm new-rule` script has broken paths
- The paths in `docs/DEV.md` still reference `eslint-bridge/`

I've opened a [PR](https://github.com/SonarSource/SonarJS/pull/3733#event-8616183500) with changes where I fix stuff for typedoc.

Otherwise, LGTM, I like the fresh makeover!

2023-02-28 12:54 UTC, saberduck commented on package.json
> +    "mvn-copy": "cd sonar-plugin && mkdirp sonar-javascript-plugin/target/classes && cp ../sonarjs-1.0.0.tgz sonar-javascript-plugin/target/classes",
yes

2023-02-28 14:04 UTC, ilia-kebets-sonarsource approved these changes

2023-03-01 09:20 UTC, merged