Add rule S6551 (`no-base-to-string`): Objects and classes converted or coerced to strings should define a "toString()" method
SonarSource/SonarJS pull request #3825
Opened 2023-03-29 08:51 UTC by ilia-kebets-sonarsource

Fixes #3791

2023-03-30 11:38 UTC, yassin-kammoun-sonarsource commented
> @yassin-kammoun-sonarsource It does flag generic types actually like:
> 
> ```ts
> static toStrings<T>(array: T[]): string[] {
>         return this.map(array, function (item) {
>             if (item === undefined || item === null || !item.toString) {
>                 return null;
>             } else {
>                 return item.toString(); // noncompliant
>             }
>         });
>     }
> ```
> 
> The case that was avoided is:
> 
> ```ts
> function test<TWithNoConstraint>(arg: T) {
>           return \`arg = \${arg}\`;
>         }
> ```
> 
> Should I decorate it to avoid generics?
> 
> Also, there is another case that I'm unsure, it's for `something | string`. WDYT?

Yes, I think that we should decorate it and avoid generics. That's actually what I suggested in the evaluation of the rule.

2023-03-30 11:40 UTC, yassin-kammoun-sonarsource commented
> Also, there is another case that I'm unsure, it's for `something | string`. WDYT?

I am not too sure here. If `something` doesn't override `toString`, that's definitely an issue as far as I understand. If we are able to detect that, that would be cool, let's give it a try and see if this pattern occurs often in ruling.

2023-03-30 11:43 UTC, ilia-kebets-sonarsource commented
> > Also, there is another case that I'm unsure, it's for `something | string`. WDYT?
> 
> I am not too sure here. If `something` doesn't override `toString`, that's definitely an issue as far as I understand. If we are able to detect that, that would be cool, let's give it a try and see if this pattern occurs often in ruling.

This pattern does occur in the ruling tests, and it is indeed caught.

2023-03-30 11:48 UTC, yassin-kammoun-sonarsource commented
I would b

> > > Also, there is another case that I'm unsure, it's for `something | string`. WDYT?
> > 
> > 
> > I am not too sure here. If `something` doesn't override `toString`, that's definitely an issue as far as I understand. If we are able to detect that, that would be cool, let's give it a try and see if this pattern occurs often in ruling.
> 
> This pattern does occur in the ruling tests, and it is indeed caught.

My gut feeling is that we should be conservative and ignore these issues. I am afraid that it would be quite noisy in a JavaScript codebase. If a variable is assigned values of different types and we are not able to discriminate the constituent type of the union, I think we would raise many false positives.

What do you think ?

2023-03-30 14:40 UTC, ilia-kebets-sonarsource commented
@yassin-kammoun-sonarsource I've brought the changes!

2023-03-31 07:48 UTC, yassin-kammoun-sonarsource requested changes

2023-03-31 07:48 UTC, yassin-kammoun-sonarsource commented on sonar-plugin/javascript-checks/src/main/java/org/sonar/javascript/checks/NoBaseToStringCheck.java
> +@TypeScriptRule
Why is the rule not enabled for JavaScript ?

2023-03-31 07:48 UTC, yassin-kammoun-sonarsource commented on src/linting/eslint/rules/decorators/no-base-to-string-decorator.ts
> +import { TSESTree } from '@typescript-eslint/experimental-utils';
```suggestion
// https://sonarsource.github.io/rspec/#/rspec/S6551/javascript

import { TSESTree } from '@typescript-eslint/experimental-utils';
```

2023-03-31 07:48 UTC, yassin-kammoun-sonarsource commented on src/linting/eslint/rules/decorators/no-base-to-string-decorator.ts
> +      }
For your information, TypeScript ESLint rules are always sanitized before decoration. See:

https://github.com/SonarSource/SonarJS/blob/a146a0d4d4df335f101d52d0c1ce21ee733eddec/src/linting/eslint/linter/decoration/decorate.ts#L56-L75

Therefore, we can not only drop the comment but also the whole check about the availability of the type checker. If type information is missing, the (sanitized) rule will never raise any issues.

2023-03-31 07:48 UTC, yassin-kammoun-sonarsource commented on src/linting/eslint/rules/decorators/no-base-to-string-decorator.ts
> +  const type = checker.getTypeAtLocation(services.esTreeNodeToTSNodeMap.get(node));
We can reuse an existing helper function for that:

https://github.com/SonarSource/SonarJS/blob/a146a0d4d4df335f101d52d0c1ce21ee733eddec/src/linting/eslint/rules/helpers/type.ts#L87-L90

2023-03-31 07:48 UTC, yassin-kammoun-sonarsource commented on sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S6551.json
> +  ]
If we decide to enable the rule for JavaScript, we will need to add it here as well.

2023-04-03 08:41 UTC, yassin-kammoun-sonarsource approved these changes
LGTM!

2023-04-03 11:48 UTC, merged