Updates S2871 (no-alphabetical-sort) to include toSorted function.
SonarSource/SonarJS pull request #3873
Opened 2023-04-27 02:46 UTC by philnash

Fixes #3864

2023-05-04 09:36 UTC, ilia-kebets-sonarsource commented on tests/linting/eslint/rules/no-alphabetical-sort.test.ts
> +        a.toSorted(undefined);
Could you adapt these examples so they make sense with `toSorted()` not making the change _in place_?

```suggestion
        return a.toSorted(undefined);
```

2023-05-04 09:43 UTC, ilia-kebets-sonarsource requested changes
Great improvement!

As I mentioned in my other comment, could you adapt the unit tests so they make more sense?
And for rules like this one that does not raise any issue in the integration ruling tests, we add a file ourselves in [file-for-rules](https://github.com/SonarSource/SonarJS/tree/master/its/sources/file-for-rules). You can simply add a `S2871.js` file with one of the invalid unit test cases and run the JavaScriptRulingTest and update the expected values.

Could you also open a PR in RSPEC to update the rule description to include `Array.toSorted()`?

2023-05-05 04:42 UTC, philnash commented
Ok, I added a [S2871.js file](https://github.com/SonarSource/SonarJS/pull/3873/files#diff-c8753034a5c4644809f866a3c1dd77413c6f2b68438d97c4faba37f727f037f8) but nothing happened in the rulings for me. And I don't know why.

Am I running the tests wrong? Did I need to add anything else? I am quite confused.

2023-05-05 13:32 UTC, ilia-kebets-sonarsource commented
> Ok, I added a [S2871.js file](https://github.com/SonarSource/SonarJS/pull/3873/files#diff-c8753034a5c4644809f866a3c1dd77413c6f2b68438d97c4faba37f727f037f8) but nothing happened in the rulings for me. And I don't know why.
> 
> Am I running the tests wrong? Did I need to add anything else? I am quite confused.

You should follow [these steps and update the integration ruling tests](https://github.com/SonarSource/SonarJS/blob/master/docs/DEV.md#ruling-tests).
1. run the ruling tests for JS locally, which will fail because there are new issues raised:
```bash
cd its/ruling
mvn verify -Dtest=JavaScriptRulingTest -Dmaven.test.redirectTestOutputToFile=false
```
2. update the expected test results
```bash
# in its/ruling
cp -R target/actual/js/ src/test/expected/js
```

Let me know if this answers your question.

2023-05-05 13:33 UTC, ilia-kebets-sonarsource requested changes
see comment

2023-05-08 00:19 UTC, philnash commented
I don't know why, but last week I could not make the ruling test fail. First time I ran it today, fail. I copied across the updated rulings and this should be good now!

2023-05-08 06:48 UTC, ilia-kebets-sonarsource approved these changes
LGTM, don't forget to update the RSPEC repo.

2023-05-08 06:51 UTC, philnash commented
https://github.com/SonarSource/rspec/pull/1831

2023-05-09 08:37 UTC, merged