Update S4043 (`no-misleading-array-reverse`): Report on `splice` and suggest `toSpliced`
SonarSource/SonarJS pull request #3937
Opened 2023-05-22 14:17 UTC by yassin-kammoun-sonarsource

Fixes #3933

2023-05-23 15:27 UTC, ilia-kebets-sonarsource requested changes
See my proposal

2023-05-24 08:41 UTC, yassin-kammoun-sonarsource commented on src/linting/eslint/rules/no-misleading-array-reverse.ts
> -              const suggestedMethod = method === 'sort' ? 'toSorted' : 'toReversed';
I am not sure I want to open the Pandora's box of exceptions. If we add an exception for this particular use case, I am afraid we will start adding more. Furthermore, I think this snippet is a perfect example of unreadable code. This is why I would avoid doing anything here. Does it make sense?

2023-05-24 08:50 UTC, ilia-kebets-sonarsource commented on src/linting/eslint/rules/no-misleading-array-reverse.ts
> -              const suggestedMethod = method === 'sort' ? 'toSorted' : 'toReversed';
Agreed that the example is not the best code, but how would you do the following: remove an element from an array and perform some computation on it?

```javascript
const elem = array.splice(pos, 1);
process(elem)
```

Without the exception, we would be forced to do:

```javascript
const elem = array[pos]
array.splice(pos, 1);
process(elem)
```

The process would be like that when deleting >1 elements, which might indeed be nice to uniformize. I'll have a look on sourcegraph.

2023-05-24 09:09 UTC, yassin-kammoun-sonarsource commented on src/linting/eslint/rules/no-misleading-array-reverse.ts
> +  'splice',
👍

2023-05-24 12:33 UTC, ilia-kebets-sonarsource commented on src/linting/eslint/rules/no-misleading-array-reverse.ts
> -              const suggestedMethod = method === 'sort' ? 'toSorted' : 'toReversed';
OK, nevermind, most of the time, when 1 item is removed, it isn't used: https://sourcegraph.com/search?q=context:global+lang:JavaScript+/splice%5C%28%5Cd%2C%5Cs%3F1/&patternType=standard&sm=1&groupBy=repo

2023-05-24 12:33 UTC, ilia-kebets-sonarsource approved these changes
LGTM!

2023-05-24 12:39 UTC, merged