Disable ucfg rule for JS embedded in HTML files
SonarSource/SonarJS pull request #4074
Opened 2023-08-18 12:32 UTC by ilia-kebets-sonarsource

Fixes #4036

2023-08-18 12:41 UTC, yassin-kammoun-sonarsource requested changes
I think we need an integration test for this change.

2023-08-21 08:29 UTC, ilia-kebets-sonarsource commented
Dropping this, because we haven't found the source of the issue that was initially raised in community.

2024-03-27 11:03 UTC, yassin-kammoun-sonarsource approved these changes
Great job writing those integration tests.
I left some suggestions about a few assertions.
Looks good to me otherwise!

2024-03-27 11:03 UTC, yassin-kammoun-sonarsource commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/HtmlSecurityTest.java
> +    assertThat(stream.toList().isEmpty()).isTrue();
Can we get rid of `isTrue` and move `isEmpty`?

2024-03-27 11:03 UTC, yassin-kammoun-sonarsource commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/HtmlSecurityTest.java
> +      )
I think we can remove this because it was introduced for YAML language detection.

2024-03-27 11:03 UTC, yassin-kammoun-sonarsource commented on its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/YamlSecurityTest.java
> +    assertThat(stream.toList().size() == 1).isTrue();
To be verified, but I think there should be an assertion method `hasSize`.

2024-03-27 11:32 UTC, merged