Add rule S6827 (`jsx-a11y/anchor-has-content`): Anchors should contain accessible content
SonarSource/SonarJS pull request #4296
Opened 2023-10-18 14:05 UTC by ilia-kebets-sonarsource

Fixes #4279

2023-10-18 14:20 UTC, ilia-kebets-sonarsource commented on its/ruling/src/test/expected/jsts/sonar-web/javascript-S6827.json
> +{
all these issues except the last are FPs because the anchor has the `title` attribute.

2023-10-19 12:42 UTC, alexander-kamushkin-sonarsource requested changes

2023-10-19 12:42 UTC, alexander-kamushkin-sonarsource commented on packages/jsts/src/rules/S6827/index.ts
> +export { rule } from './rule';
I would suggest removing this and just renaming rule.ts to index.ts

2023-10-19 12:58 UTC, alexander-kamushkin-sonarsource approved these changes
LGTM

2023-10-19 15:17 UTC, merged