Ignore file size limits for CSS
SonarSource/SonarJS pull request #4316
Opened 2023-10-25 14:41 UTC by ilia-kebets-sonarsource

Fixes #4234

2023-10-25 14:42 UTC, ilia-kebets-sonarsource commented on sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/filter/JavaScriptExclusionsFileFilterTest.java
>          .withFailMessage("Wrong result for size " + size)
I don't understand why this case expects a fail message, since `filter.accept(...)` is also expected to return `true`

2023-10-25 14:46 UTC, ilia-kebets-sonarsource commented on sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/filter/JavaScriptExclusionsFileFilterTest.java
> +      assertThat(filter.accept(inputFile("name.css", syntheticJsFileContent(size)))).isTrue();
I reused `syntheticJsFileContent()`, because the file content doesn't matter here.

2023-10-25 16:02 UTC, saberduck commented on sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/filter/JavaScriptExclusionsFileFilterTest.java
>          .withFailMessage("Wrong result for size " + size)
I think that only provides message when assertions fails

2023-10-25 16:08 UTC, saberduck commented
I would keep assesors agnostic of the language of the file. 
I believe this logic should be in the filter itself and not in the assessor, ie here https://github.com/SonarSource/SonarJS/blob/ac74f3d875397f0b62e272352af4baf2b8ba7bcc/sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/filter/JavaScriptExclusionsFileFilter.java#L61

We should create different set of assesors for CSS and JS/TS files, and simply not include size assesor in the CSS files. Keep it mind that order of "assessing" matters -> we should do cheap exclusions based on file properties before touching the content of the file.

2023-10-25 16:09 UTC, saberduck requested changes
see comment above

2023-10-26 11:45 UTC, ilia-kebets-sonarsource commented
I was wondering if it is problematic that the filter scope is [only covering CssLanguage here](https://github.com/SonarSource/SonarJS/pull/4316/files#diff-28dde6e2d26aa37a519a3ee653f370200e5705d1dd012a3a92e1a0631d47e828R69) contrary to how the [CSSRuleSensor filters it](https://github.com/SonarSource/SonarJS/blob/f600f32768137b1433ee6df6c16df147eba2b213/sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/bridge/CssRuleSensor.java#L211-L226).

2023-10-26 14:08 UTC, saberduck commented
> I was wondering if it is problematic that the filter scope is [only covering CssLanguage here](https://github.com/SonarSource/SonarJS/pull/4316/files#diff-28dde6e2d26aa37a519a3ee653f370200e5705d1dd012a3a92e1a0631d47e828R69) contrary to how the [CSSRuleSensor filters it](https://github.com/SonarSource/SonarJS/blob/f600f32768137b1433ee6df6c16df147eba2b213/sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/bridge/CssRuleSensor.java#L211-L226).

IMO, it's okay like this. We don't need to filter `html` or other files. We can adjust if we discover there is an issue with such setup.

2023-10-26 14:09 UTC, saberduck approved these changes

2023-10-26 14:09 UTC, merged