BUILD-4131 use GitHub token from vault instead of sonartech api token
SonarSource/SonarJS pull request #4386
Opened 2023-11-14 14:29 UTC by sebastienvermeille

# BUILD-4131 use GitHub token from vault instead of sonartech api token

## Changes
* Adapt the  dogfood pipeline
  That way this secret can be rotated easily as it comes from Vault

2023-11-15 11:00 UTC, matemoln requested changes

2023-11-15 11:00 UTC, matemoln commented on .github/workflows/dogfood.yml
>      steps:
```suggestion
    permissions:
      id-token: write # required for SonarSource/vault-action-wrapper
    steps:
```

2023-11-15 15:45 UTC, matemoln approved these changes

2023-11-16 08:34 UTC, yassin-kammoun-sonarsource approved these changes

2023-11-16 08:59 UTC, merged