Add rule S6859 (`eslint-plugin-import/no-absolute-path`): Imports should not use absolute paths
SonarSource/SonarJS pull request #4439
Opened 2023-11-27 15:56 UTC by ilia-kebets-sonarsource

Fixes #4432

2023-11-27 16:51 UTC, ilia-kebets-sonarsource commented
@yassin-kammoun-sonarsource Could you please run `rule-api`?
We can merge this without squashing so we can highlight how we add a new plugin.

2023-11-28 08:27 UTC, yassin-kammoun-sonarsource approved these changes

2023-11-28 08:27 UTC, yassin-kammoun-sonarsource commented on package.json
> +    "eslint-plugin-import": "^2.29.0",
```suggestion
    "eslint-plugin-import": "2.29.0",
```

2023-11-28 08:27 UTC, yassin-kammoun-sonarsource commented on package.json
> +    "eslint-plugin-import": "^2.29.0",
Don't forget to update the `package-lock.json` file.

2023-11-28 11:30 UTC, yassin-kammoun-sonarsource requested changes

2023-11-28 11:30 UTC, yassin-kammoun-sonarsource commented on packages/jsts/src/linter/quickfixes/messages.ts
> +  ['no-absolute-path', 'Do not import modules using an absolute path'],
```suggestion
  ['no-absolute-path', 'Replace with a relative path'],
```

2023-11-28 14:57 UTC, yassin-kammoun-sonarsource approved these changes

2023-11-28 14:57 UTC, merged