Create rule S5973: Tests should be stable
SonarSource/SonarJS pull request #4443
Opened 2023-11-29 14:07 UTC by ilia-kebets-sonarsource

Fixes #4429

2023-11-29 17:21 UTC, ilia-kebets-sonarsource commented
As mentioned, there seems to be some kind of issue with the error message that I run into when executing the ruling test, which prevents the rule from creating the expected issues:
```
INFO: Loading /Users/ilia.kebets/Dev/Sonar/SonarJS/its/ruling/src/test/expected/jsts/file-for-rules
ERROR: Error: Failed to parse encoded issue message for rule stable-tests:
ERROR: "Make your tests stable so that they passes on the first try, or remove the flaky ones". Unexpected token 'M', "Make your "... is not valid JSON
ERROR:     at decodeSonarRuntime (/Users/ilia.kebets/Dev/Sonar/SonarJS/its/sources/jsts/custom/.scannerwork/.sonartmp/bridge-bundle/package/lib/jsts/src/linter/issues/decode.js:27:19)
ERROR:     at transformMessages (/Users/ilia.kebets/Dev/Sonar/SonarJS/its/sources/jsts/custom/.scannerwork/.sonartmp/bridge-bundle/package/lib/jsts/src/linter/issues/transform.js:40:75)
ERROR:     at LinterWrapper.lint (/Users/ilia.kebets/Dev/Sonar/SonarJS/its/sources/jsts/custom/.scannerwork/.sonartmp/bridge-bundle/package/lib/jsts/src/linter/wrapper.js:121:47)
ERROR:     at analyzeFile (/Users/ilia.kebets/Dev/Sonar/SonarJS/its/sources/jsts/custom/.scannerwork/.sonartmp/bridge-bundle/package/lib/jsts/src/analysis/analyzer.js:68:87)
ERROR:     at analysis (/Users/ilia.kebets/Dev/Sonar/SonarJS/its/sources/jsts/custom/.scannerwork/.sonartmp/bridge-bundle/package/lib/jsts/src/analysis/analyzer.js:48:28)
ERROR:     at measureDuration (/Users/ilia.kebets/Dev/Sonar/SonarJS/its/sources/jsts/custom/.scannerwork/.sonartmp/bridge-bundle/package/lib/jsts/src/monitoring/measure.js:31:20)
ERROR:     at analyzeJSTS (/Users/ilia.kebets/Dev/Sonar/SonarJS/its/sources/jsts/custom/.scannerwork/.sonartmp/bridge-bundle/package/lib/jsts/src/analysis/analyzer.js:49:89)
ERROR:     at MessagePort.<anonymous> (/Users/ilia.kebets/Dev/Sonar/SonarJS/its/sources/jsts/custom/.scannerwork/.sonartmp/bridge-bundle/package/lib/bridge/src/worker.js:79:36)
```

2023-11-30 07:54 UTC, yassin-kammoun-sonarsource commented on packages/jsts/src/rules/S5973/rule.ts
> +      },
The failure is likely due to the enabling of secondary location support.

2023-11-30 08:25 UTC, ilia-kebets-sonarsource commented on packages/jsts/src/rules/S5973/rule.ts
> +      },
thanks, and done!

2023-11-30 09:40 UTC, yassin-kammoun-sonarsource requested changes

2023-11-30 09:40 UTC, yassin-kammoun-sonarsource commented on packages/jsts/src/rules/S5973/rule.ts
> +      stable: 'Make your tests stable so that they pass on the first try, or remove the flaky ones',
```suggestion
      stable: 'Make your tests stable so that they pass on the first try, or remove the flaky ones.',
```

2023-11-30 09:40 UTC, yassin-kammoun-sonarsource commented on packages/jsts/src/rules/S5973/rule.ts
> +        if (memberExpressionName === 'jest.retryTimes') {
That won't work if jest is not imported explicitly but visible globally. I think we should either check that jest is a dependency in the package.json file or just assume that `jest.retryTimes` always refers to the actual jest' function.

2023-11-30 09:40 UTC, yassin-kammoun-sonarsource commented on packages/jsts/src/rules/S5973/rule.ts
> +       * and implicitely test cases.
```suggestion
       * and implicitly test cases.
```

2023-11-30 09:40 UTC, yassin-kammoun-sonarsource commented on packages/jsts/src/rules/S5973/rule.ts
> +    };
Let's add `Program:exit` to clear the stack as a precaution against memory leaks.

2023-11-30 09:40 UTC, yassin-kammoun-sonarsource commented on packages/jsts/src/rules/S5973/rule.ts
> +    callee.property.name === 'retries'
We can call the helper function `isIdentifier(callee.property, 'retries')`.

2023-11-30 09:40 UTC, yassin-kammoun-sonarsource commented on packages/jsts/src/rules/S5973/rule.ts
> + * @returns
I think the description is enough, not worth it to have these especially when left empty.

2023-12-04 10:38 UTC, ilia-kebets-sonarsource commented on packages/jsts/src/rules/S5973/rule.ts
> +    callee.property.name === 'retries'
done

2023-12-04 10:45 UTC, ilia-kebets-sonarsource commented on packages/jsts/src/rules/S5973/rule.ts
> +        if (memberExpressionName === 'jest.retryTimes') {
Do you mean that `getFQN()` won't return `jest.retryTimes` if it's imported globally, so you recommend to do:
1. check for `jest` in dependencies (and devDependencies) AND
2. try to match `jest.retryTimes()`

and also do the current check.

2023-12-05 07:29 UTC, yassin-kammoun-sonarsource commented on packages/jsts/src/rules/S5973/rule.ts
> + * @returns
Depends on how you interpret what "empty" means:

- `@param context` is left empty
- `@param node` is also empty
- `@returns` is empty

2023-12-05 10:47 UTC, yassin-kammoun-sonarsource requested changes

2023-12-05 10:47 UTC, yassin-kammoun-sonarsource commented on sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S5973.html
> +<h2>Why is this an issue?</h2>
Don't forget to update this.

2023-12-05 10:47 UTC, yassin-kammoun-sonarsource commented on sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S5973.json
> +{
And that.

2023-12-05 10:47 UTC, yassin-kammoun-sonarsource commented on packages/jsts/src/rules/S5973/cb.fixture.ts
> +import * as jest from 'jest';
Maybe it would be better two have two different fixture files: one for Jest and one for Mocha. Right now, we are mixing both in a single file.

2023-12-05 10:47 UTC, yassin-kammoun-sonarsource commented on packages/jsts/src/rules/S5973/cb.fixture.ts
> +import * as jest from 'jest';
We also need another fixture file checking the case where we assume that Jest is available globally and there is no explicit import statement.

2023-12-05 10:47 UTC, yassin-kammoun-sonarsource commented on packages/jsts/src/rules/S5973/rule.ts
> +        checkJestRetry(context, node);
Maybe this function should return a boolean value so that we don't unnecessarily execute the Mocha-specific logic that comes right after. Alternatively, we could just inline the function's body.

2023-12-05 10:47 UTC, yassin-kammoun-sonarsource commented on packages/jsts/src/rules/S5973/rule.ts
> +        describes.length = 0;
👍

2023-12-05 10:47 UTC, yassin-kammoun-sonarsource commented on packages/jsts/src/rules/S5973/rule.ts
> +}
I think you can use the helper function `isMethodInvocation`.

2023-12-05 10:53 UTC, ilia-kebets-sonarsource commented on packages/jsts/src/rules/S5973/rule.ts
> +}
done

2023-12-05 13:50 UTC, ilia-kebets-sonarsource commented on packages/jsts/src/rules/S5973/rule.ts
> +        if (memberExpressionName === 'jest.retryTimes') {
done.

2023-12-05 13:50 UTC, ilia-kebets-sonarsource commented on packages/jsts/src/rules/S5973/cb.fixture.ts
> +import * as jest from 'jest';
done

2023-12-05 13:50 UTC, ilia-kebets-sonarsource commented on packages/jsts/src/rules/S5973/rule.ts
> +        checkJestRetry(context, node);
done.

2023-12-06 08:40 UTC, merged