Skip embedded Node.js runtime deployment if 'sonar.nodejs.executable' is set
SonarSource/SonarJS pull request #4616
Opened 2024-03-25 11:26 UTC by ilia-kebets-sonarsource

Fixes #4400

2024-03-25 16:09 UTC, saberduck commented on sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/bridge/BridgeServerImpl.java
> +    embeddedNode.deploy(configuration);
could we move the condition check here? I don't like adding more sonar API dependencies in `EmbeddedNode`. I think `EmbeddedNode` shouldn't handle logic which is external to it.

2024-03-25 16:09 UTC, saberduck commented on sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/bridge/EmbeddedNode.java
> +import org.sonar.api.config.Configuration;
it would be better if this class doesn't depend on too many components from sonar API

2024-03-25 16:11 UTC, saberduck requested changes
I think it would be better to handle the condition in BridgeServer and do not push dependencies into EmbeddedNode

2024-03-26 06:53 UTC, ilia-kebets-sonarsource commented on sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/bridge/BridgeServerImplTest.java
> +    var nodeCommand = Arrays
I considered adding a method to BridgeServerImpl to retrieve the computed node path.

2024-03-26 06:54 UTC, ilia-kebets-sonarsource commented on sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/bridge/BridgeServerImplTest.java
> +      );
There is currently no getter for a bridgeServer's embeddedNode instance, I could add one so we can assert a file non existence.

2024-03-26 08:59 UTC, ilia-kebets-sonarsource commented on sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/bridge/BridgeServerImplTest.java
> +  }
Before this, my idea was to run bridgeServer.startLazily() twice. First to extract a node runtime that would be used by the second call to it.
This requires quite a lot of boilerplate code since the helper functions in BridgeServerImplTest.java have hardcoded  an unsupported platform for the BridgeServer EmbeddedNode instance.

2024-03-26 11:12 UTC, saberduck commented on sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/bridge/EmbeddedNode.java
> +
unneeded change?

2024-03-26 15:11 UTC, saberduck approved these changes

2024-03-26 15:31 UTC, merged

2024-03-26 15:47 UTC, saberduck commented
> Huh, surprising that the code review still requires me specifically to review even if there is someone else who accepted. I'm used to only need to have a single accept, without counting how many request changes were there before, sorry for the wait.

I think we could configure it, maybe add a point to the weekly meeting to discuss it