JS-161 Separate bridge from sonar-javascript-plugin
SonarSource/SonarJS pull request #4697
Opened 2024-05-20 22:12 UTC by saberduck

Some changes were made in `BridgeServer` to improve the overall code
- use of Java `record` which makes the fields `final` and private, they are available through accessor methods (thus change of field access to method invocation `()` )
- removed some deprecated code related to logging, mostly in tests
- use of String literals for language keys (`js,ts,yaml`) to avoid circular dependency between `bridge` and `sonar-javascript-plugin`
- some methods are forced to be `public`, because there is too much sharing between `bridge` and `sonar-javascript-plugin`, when we will migrate more logic to the Node.js part, we will be able to improve this

2024-05-23 07:17 UTC, saberduck commented on pom.xml
> +    <gson.version>2.11.0</gson.version>
to support Java 17 record

2024-05-23 08:35 UTC, saberduck commented on sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/analysis/cache/CacheStrategies.java
> -    if (!AnalysisMode.isRuntimeApiCompatible(context) || !context.canSkipUnchangedFiles()) {
we don't need to test backward compatibility with old SQ 9.4

2024-05-23 13:20 UTC, saberduck commented on sonar-plugin/bridge/src/main/java/org/sonar/plugins/javascript/bridge/JavaScriptFilePredicate.java
> +        fs.predicates().hasLanguage("yaml"),
String is used to avoid circular dependency. Extracting some `common` module just for this looks like overkill for now

2024-05-24 07:48 UTC, ilia-kebets-sonarsource commented on sonar-plugin/bridge/pom.xml
> +      <!-- TODO this should be replaced by new API module -->
do you mean javascript-checks?

2024-05-24 07:50 UTC, ilia-kebets-sonarsource commented on sonar-plugin/bridge/src/main/java/org/sonar/plugins/javascript/bridge/BridgeServerImpl.java
> +    return response(request(json, "analyze-js"), request.filePath());
is this change due to the upgrade of the `gson` lib?

2024-05-24 07:51 UTC, ilia-kebets-sonarsource commented on sonar-plugin/bridge/src/main/java/org/sonar/plugins/javascript/bridge/EslintRule.java
> +    if (!"js".equals(language) && !"ts".equals(language)) {
why remove the usage of constants here?

2024-05-24 07:51 UTC, ilia-kebets-sonarsource commented on sonar-plugin/bridge/src/main/java/org/sonar/plugins/javascript/bridge/JavaScriptFilePredicate.java
> +        fs.predicates().hasLanguage("yaml"),
ah, I guess it's the same above, for "js" and "ts"

2024-05-24 07:56 UTC, ilia-kebets-sonarsource commented on sonar-plugin/bridge/src/test/java/org/sonar/plugins/javascript/bridge/BridgeServerImplTest.java
> +    assertThat(bridgeServer.analyzeJavaScript(request).issues()).hasSize(1);
how come we are getting an issue now?

2024-05-24 07:57 UTC, ilia-kebets-sonarsource commented on sonar-plugin/bridge/src/test/java/org/sonar/plugins/javascript/bridge/BridgeServerImplTest.java
> +    assertThat(bridgeServer.analyzeTypeScript(request).issues()).hasSize(1);
same here

2024-05-24 07:57 UTC, ilia-kebets-sonarsource commented on sonar-plugin/bridge/src/test/java/org/sonar/plugins/javascript/bridge/BridgeServerImplTest.java
> +    assertThat(bridgeServer.analyzeYaml(request).issues()).hasSize(1);
and here

2024-05-24 07:57 UTC, ilia-kebets-sonarsource commented on sonar-plugin/bridge/src/test/java/org/sonar/plugins/javascript/bridge/BridgeServerImplTest.java
> +    assertThat(bridgeServer.analyzeTypeScript(request).issues()).hasSize(1);
and here

2024-05-24 07:57 UTC, ilia-kebets-sonarsource commented on sonar-plugin/bridge/src/test/java/org/sonar/plugins/javascript/bridge/BridgeServerImplTest.java
> +    assertThat(bridgeServer.analyzeCss(request).issues()).hasSize(1);
and here

2024-05-24 09:00 UTC, ilia-kebets-sonarsource commented on sonar-plugin/bridge/src/test/java/org/sonar/plugins/javascript/bridge/JavaScriptFilePredicateTest.java
> +    if (".js,.jsx,.cjs,.mjs,.vue".contains(fileExtension)) {
that's becoming a bit cumbersome, maybe it is worth it to extract this?

2024-05-24 10:58 UTC, ilia-kebets-sonarsource commented on sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/analysis/cache/CacheStrategies.java
> -    if (!AnalysisMode.isRuntimeApiCompatible(context) || !context.canSkipUnchangedFiles()) {
what was special about SQ 9.4?

2024-05-24 11:01 UTC, ilia-kebets-sonarsource commented on sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/analysis/cache/CpdSerializer.java
> +    var location = cpdToken.location();
it's the change from classes getters convention to record getters that introduces all these changes?

2024-05-24 11:02 UTC, ilia-kebets-sonarsource commented on sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/bridge/BridgeServer.java
using Records allows us to cut the length of this file in half, nice!

2024-05-24 11:15 UTC, ilia-kebets-sonarsource commented on sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/analysis/cache/CacheTestUtils.java
> +    when(cache.contains("jssecurity:ucfgs:JSON:1.0:moduleKey:" + filePath)).thenReturn(true);
that's the plugin version that serves as cache key that you mentioned?

2024-05-24 11:21 UTC, ilia-kebets-sonarsource requested changes
a few questions about:
- test results changing
- language constants being a bit ugly
- minor questions and remarks

Otherwise LGTM. Let me know if you wish togo through it together.

2024-05-24 12:53 UTC, saberduck commented on sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/analysis/cache/CacheStrategies.java
> -    if (!AnalysisMode.isRuntimeApiCompatible(context) || !context.canSkipUnchangedFiles()) {
it introduced cache

2024-05-24 12:53 UTC, saberduck commented on sonar-plugin/bridge/pom.xml
> +      <!-- TODO this should be replaced by new API module -->
no, the API module introduced in JS-162, it will contain the classes which are in `javascript-checks` because of some historical reasons

2024-05-24 12:55 UTC, saberduck commented on sonar-plugin/bridge/src/test/java/org/sonar/plugins/javascript/bridge/BridgeServerImplTest.java
> +    assertThat(bridgeServer.analyzeJavaScript(request).issues()).hasSize(1);
I changed the `startServer` script to return some issue, in order to have code coverage in `BridgeServer` 

see here https://github.com/SonarSource/SonarJS/pull/4697/files#diff-d348a0b26e6add7d9a6e42a713de34abcd9358b9fe5db19ddb816145573ffe8dR46

2024-05-24 12:58 UTC, saberduck commented on sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/analysis/cache/CpdSerializer.java
> +    var location = cpdToken.location();
mostly yes, also some deprecated code removal. Imo it's better than having `public` fields, as `getters` are immutable, which is cleaner

2024-05-24 12:59 UTC, saberduck commented on sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/analysis/cache/CacheTestUtils.java
> +    when(cache.contains("jssecurity:ucfgs:JSON:1.0:moduleKey:" + filePath)).thenReturn(true);
yes, previously the code relied on the fact that version in unit tests was `null`

2024-05-24 13:10 UTC, ilia-kebets-sonarsource commented on sonar-plugin/bridge/src/test/java/org/sonar/plugins/javascript/bridge/BridgeServerImplTest.java
> +    assertThat(bridgeServer.analyzeJavaScript(request).issues()).hasSize(1);
Thanks for the explanation

2024-05-24 13:11 UTC, ilia-kebets-sonarsource approved these changes
Thank you for the clarifications, LGTM!

2024-05-24 13:57 UTC, merged