JS-162 Create API module
SonarSource/SonarJS pull request #4704
Opened 2024-05-23 15:53 UTC by saberduck

- **wip**
- **fix test**
- **add run-node**
- **fix test**
- **fix build**
- **inline Constants.java**
- **remove obsolete checks**
- **use record**
- **clean up**
- **clean up Sonar warnings**
- **clean up Sonar warnings**
- **fix coverage**
- **fix coverage**
- **moare coverage**
- **moare coverage**
- **formatting**
- **fix after formatting**
- **improve coverage**
- **Create API module**

2024-05-23 16:06 UTC, saberduck commented on sonar-plugin/sonar-javascript-plugin/pom.xml
> +    <dependency>
reordered to follow alphabetical order

2024-05-24 13:44 UTC, ilia-kebets-sonarsource commented on sonar-plugin/api/pom.xml
> +      <artifactId>sonar-plugin-api</artifactId>
shouldn't it depend on bridge instead?

2024-05-24 13:45 UTC, ilia-kebets-sonarsource requested changes
see comment

2024-05-24 13:46 UTC, saberduck commented on sonar-plugin/api/pom.xml
> +      <artifactId>sonar-plugin-api</artifactId>
why? This means it depends on Sonar (scanner) API; it's to have access to `InputFile,` `@ScannerSide,` etc...

2024-05-24 13:52 UTC, ilia-kebets-sonarsource approved these changes
LGTM

2024-05-24 14:48 UTC, merged