Register babel presets and plugin from their actual modules
SonarSource/SonarJS pull request #4763
Opened 2024-08-12 10:23 UTC by ericmorand-sonarsource

Nothing to see here, just testing this pattern.

2024-08-12 12:56 UTC, saberduck commented on packages/jsts/src/parsers/options.ts
> +const babelReactPreset = require('@babel/preset-react').default;
could we use `import` instead of `require`? I am not sure if it's technically possible

2024-08-12 13:00 UTC, ericmorand-sonarsource commented on packages/jsts/src/parsers/options.ts
> +const babelReactPreset = require('@babel/preset-react').default;
It is, but since there is no available typing for those packages, it would probably involve adding some ts-ignore things or maintaining some declarations ourselves. I can try.

2024-08-12 13:08 UTC, ericmorand-sonarsource commented on packages/jsts/src/parsers/options.ts
> +const babelReactPreset = require('@babel/preset-react').default;
This pass the tests and emit the dependencies to the bundler, so it's technically all good:

```ts
// @ts-ignore
import {default as babelReactPreset} from "@babel/preset-react";
// @ts-ignore
import {default as babelFlowPreset} from "@babel/preset-flow";
// @ts-ignore
import {default as babelEnvPreset} from "@babel/preset-env";
// @ts-ignore
import {default as babelDecoratorProposalPlugin} from "@babel/plugin-proposal-decorators";
```

The `ts-ignore` directives are not looking great (`@babel/preset-env` got typings available, note) but if we can live with them or add some local declarations, we are all good.

2024-08-12 16:53 UTC, ilia-kebets-sonarsource commented on packages/jsts/src/parsers/options.ts
> +const babelReactPreset = require('@babel/preset-react').default;
@ericmorand-sonarsource If I'm not mistaken, we can add partial typings for our dependencies in [this folder](https://github.com/SonarSource/SonarJS/tree/master/typings).

2024-08-12 16:54 UTC, ilia-kebets-sonarsource requested changes
Add typings and use `import` as discussed https://github.com/SonarSource/SonarJS/pull/4763/files#r1714107832
I'm open to discuss if you would like to consider another solution.

2024-08-28 16:07 UTC, ilia-kebets-sonarsource approved these changes
you can use require instead.

2024-09-13 13:39 UTC, closed without merging