JS-312 Create rule S1607: Tests should not be skipped without providing a reason
SonarSource/SonarJS pull request #4797
Opened 2024-09-03 13:04 UTC by yassin-kammoun-sonarsource

[RSPEC](https://github.com/SonarSource/rspec/pull/4218) to review

2024-09-03 13:42 UTC, zglicz requested changes
Few small comments for you!

![awwyiss2](https://github.com/user-attachments/assets/a9b44455-1300-4fa2-83f3-898626527acf)

2024-09-03 13:42 UTC, zglicz commented on packages/jsts/src/rules/S1607/rule.ts
> +      return comments.some(comment => comment.loc!.end.line === node.loc!.start.line - 1);
Is a single character enough? Should there be a minimal length of explanation?

2024-09-03 13:42 UTC, zglicz commented on packages/jsts/src/rules/S1607/rule.ts
> +      case getPackageJsonsCount() > 0:
Why does this imply the nodejsListener?

2024-09-03 13:42 UTC, zglicz commented on packages/jsts/src/rules/S1607/rule.ts
> +    function jasmineListener(): Rule.RuleListener {
the jasmine, jest and mocha listeners follow the same convention. They only differ on the isIgnoredTest implementation. Could you merge them?

2024-09-03 14:06 UTC, yassin-kammoun-sonarsource commented on packages/jsts/src/rules/S1607/rule.ts
> +      return comments.some(comment => comment.loc!.end.line === node.loc!.start.line - 1);
What would you suggest as a minimal length?

2024-09-03 14:06 UTC, yassin-kammoun-sonarsource commented on packages/jsts/src/rules/S1607/rule.ts
> +      case getPackageJsonsCount() > 0:
I assume that a Node.js project includes at least one package.json file so that the Node-specific listener is worth triggering.

2024-09-03 14:09 UTC, yassin-kammoun-sonarsource commented on packages/jsts/src/rules/S1607/rule.ts
> +    function jasmineListener(): Rule.RuleListener {
I have mixed feelings about this because of past experiences. While it's true that the implementation is quite similar, I also feel that merging them may not be beneficial once we receive feedback from users and need to introduce framework-specific exceptions.

2024-09-04 08:48 UTC, zglicz commented on packages/jsts/src/rules/S1607/rule.ts
> +      return comments.some(comment => comment.loc!.end.line === node.loc!.start.line - 1);
I wouldn't consider a single word to be a good enough reason. I'd say 20 characters could be fair, so that it can be a semblance of a valid sentence.

2024-09-04 08:56 UTC, zglicz approved these changes
Thanks for answering the comments

2024-09-04 08:56 UTC, zglicz commented on packages/jsts/src/rules/S1607/rule.ts
> +    switch (true) {
oh, that's also a new one for me as well. Interesting.

2024-09-04 08:56 UTC, zglicz commented on packages/jsts/src/rules/S1607/rule.ts
> +      case getPackageJsonsCount() > 0:
I've only ever used jest, so I'm not sure how users normally setup the nodejs-tests. It's a foreign approximation for me.

2024-09-04 08:56 UTC, zglicz commented on packages/jsts/src/rules/S1607/rule.ts
> +    function jasmineListener(): Rule.RuleListener {
Hm, well ok. I would say that's a premature separation, but I lack the experience here. Just a small fear, that there might also be improvements that will need to land in all 3 places.

2024-09-04 09:50 UTC, yassin-kammoun-sonarsource commented on packages/jsts/src/rules/S1607/rule.ts
> +      return comments.some(comment => comment.loc!.end.line === node.loc!.start.line - 1);
That sounds fair, but I wonder how that would work on comments written That sounds fair, but I wonder how that would work with comments written in Asian languages such as Chinese or Japanese, which can be quite compact.

2024-09-04 10:14 UTC, ilia-kebets-sonarsource commented on sonar-plugin/javascript-checks/src/main/java/org/sonar/javascript/checks/NoSkippedTestsCheck.java
> +public class NoSkippedTestsCheck extends Check {
Do we need tests for checks of rules without parameters?

2024-09-04 11:03 UTC, yassin-kammoun-sonarsource commented on packages/jsts/src/rules/S1607/rule.ts
> +      return comments.some(comment => comment.loc!.end.line === node.loc!.start.line - 1);
I have been thinking, and I remember seeing quite a few times comments that just mention a Jira ticket number or a GitHub issue number.

2024-09-04 11:05 UTC, yassin-kammoun-sonarsource commented on sonar-plugin/javascript-checks/src/main/java/org/sonar/javascript/checks/NoSkippedTestsCheck.java
> +public class NoSkippedTestsCheck extends Check {
We never did that until now. Did something change recently?

2024-09-04 12:39 UTC, merged