JS-313 Create rule S2301: Public methods should not contain selector arguments
SonarSource/SonarJS pull request #4799
Opened 2024-09-04 09:17 UTC by ericmorand-sonarsource

Fixes JS-313

2024-09-10 10:27 UTC, zglicz reviewed
Asking a few questions to better understand :)

2024-09-10 10:27 UTC, zglicz commented on packages/jsts/src/rules/S2301/index.ts
> +            for (const booleanParameter of booleanParameters) {
I can't seem to understand how can this have more than 1 element? Shouldn't we just report above in line 90?

2024-09-10 10:27 UTC, zglicz commented on packages/jsts/src/rules/S2301/index.ts
> +        if (testNode !== undefined) {
should we prefer an early-return (and below in 78)? that wouldn't lead to this nested code? I re-call we wanted to add this explicit rule in this sprint

2024-09-10 10:27 UTC, zglicz commented on packages/jsts/src/rules/plugin.ts
> +  s2301: S2301,
why not provide a name to the rule? I _think_ this drives what we show here - https://github.com/SonarSource/SonarJS/blob/master/packages/jsts/src/rules/README.md

2024-09-10 10:27 UTC, zglicz commented on packages/jsts/src/rules/S2301/index.ts
> +        };
This could probably live in `helpers/ancestor.ts`

2024-09-10 10:27 UTC, zglicz commented on packages/jsts/src/rules/S2301/index.ts
> +          return testNode === node || isAChildOf(node, testNode);
does the second part of this logical check, makes this rule trigger on any usage of a boolean argument in the test condition? Is that not very strict? Doesn't that make all boolean parameters unusable? Are they only to be passed to other functions, I guess?

2024-09-10 10:50 UTC, ericmorand-sonarsource commented on packages/jsts/src/rules/S2301/index.ts
> +        if (testNode !== undefined) {
Good catch. Will fix.

2024-09-10 10:51 UTC, ericmorand-sonarsource commented on packages/jsts/src/rules/plugin.ts
> +  s2301: S2301,
True, I forgot to find a proper key for this rule. Let me make a proposal.

2024-09-10 10:52 UTC, ericmorand-sonarsource commented on packages/jsts/src/rules/S2301/index.ts
> +        };
I don't know, not sure what the policy is about helpers. I assumed it was only for tools that were used by multiple rules but this logic is very specific to this use case. Let's ask the squad during the daily.

2024-09-10 10:54 UTC, ericmorand-sonarsource commented on packages/jsts/src/rules/S2301/index.ts
> +          return testNode === node || isAChildOf(node, testNode);
I'm not sure yet if it is too broad to not. The idea is that every boolean parameter that creates a branch inside the body is suspect. That may be too noisy, which I'd like to check with the squad and the web guild during the verify step on Peach.

2024-09-10 10:55 UTC, ericmorand-sonarsource commented on packages/jsts/src/rules/S2301/index.ts
> +            for (const booleanParameter of booleanParameters) {
There may be more than one boolean parameter by function - like `getCat(onlyBrown: boolean, emitAsJSON: boolean)`. In this case, both should trigger the issue.

2024-09-10 11:55 UTC, ericmorand-sonarsource commented on packages/jsts/src/rules/S2301/index.ts
> +            for (const booleanParameter of booleanParameters) {
OK, I understand, good catch. I'll add a test to cover my example and fix the code following your feedback.

2024-09-10 12:00 UTC, yassin-kammoun-sonarsource requested changes
Another reviewer may have a different opinion, but from what I could see regarding the ruling outcome, we should adjust the approach and the scope because we are raising too many false positives. Currently, the rule flags any boolean parameter used in the condition of an `if`-statement. The way I understand the RSPEC, we are mainly interested in code patterns where the body of a function/method definition is an if-statement that dispatches the execution path of the definition based on a parameter:

```
function f(p1, p2, ... pn) {
  if (pX) {
    doSomething(...);
  } else {
    doSomethingElse(...);
  }
}
```

I would therefore advise to apply the following algorithm:
1. Visit function-like nodes whose body is an if-else construct.
2. Check that the condition is a test on the parameter
3. Check that both branches are call expressions
4. Raise an issue if 2) and 3) are true

2024-09-11 12:45 UTC, yassin-kammoun-sonarsource commented
@ericmorand-sonarsource We talked with the rest of the team, and we all agreed that the current approach is too broad. As mentioned earlier and discussed with the two of us yesterday, let's revisit the scope of the rule and stick to the noncompliant code pattern of the RSPEC. The ruling results show that the rule is already quite noisy. It would be a waste of time to merge the rule first and then look at the results on Peach, as the ruling results already provide evidence of the noise.

2024-09-11 12:46 UTC, yassin-kammoun-sonarsource requested changes
Let's implement a different approach based on the rule pattern of the RSPEC noncompliant code.

2024-09-12 15:41 UTC, ericmorand-sonarsource commented
The rule perimeter is now much narrower; it only triggers for:

* tests that are the only children of a function body _and_ have an alternate path (i.e., either if with else or conditional expressions)
* return statements that are the only children of a function body and have a conditional expression as expression

The ruling tests demonstrate that the rule now identifies only relevant issues.

2024-09-13 10:23 UTC, vdiez requested changes
I like a lot your implementation using the stack. Just some minor changes requested, let me know what you think

2024-09-13 10:23 UTC, vdiez commented on packages/jsts/src/rules/S2301/rule.ts
> +        const isAChildOf = (identifier: Node, node: Node): boolean => {
move this function definition out, no need to redefine it on each identifier

2024-09-13 10:23 UTC, vdiez commented on packages/jsts/src/rules/S2301/rule.ts
> +            isRequiredParserServices(context.parserServices)
this check should be moved at the top of the create method, if we don't have type information we can return an empty object without any selectors, as we will never raise any issue

2024-09-13 12:07 UTC, ericmorand-sonarsource commented on packages/jsts/src/rules/S2301/rule.ts
> +        const isAChildOf = (identifier: Node, node: Node): boolean => {
Good catch!

2024-09-13 12:11 UTC, ericmorand-sonarsource commented on packages/jsts/src/rules/S2301/rule.ts
> +  meta: generateMeta(rspecMeta as Rule.RuleMetaData, {}, true),
Out of curiosity, is it mandatory for ESLint to work correctly even if we never reference the message ID?

2024-09-13 13:53 UTC, vdiez commented on packages/jsts/src/rules/S2301/rule.ts
> +  meta: generateMeta(rspecMeta as Rule.RuleMetaData, {}, true),
no, it's not mandatory. both message or messageId can be used and the existence of a messageId in the meta does not require it to be used

2024-09-13 13:53 UTC, ericmorand-sonarsource commented on packages/jsts/src/rules/S2301/rule.ts
> +  meta: generateMeta(rspecMeta as Rule.RuleMetaData, {}, true),
Thanks for the clarification. :pray:

2024-09-13 13:55 UTC, vdiez approved these changes
LGTM! Just one final thing to be added in rspec

2024-09-13 13:55 UTC, vdiez commented on sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S2301.json
> +    "design"
one minor request: I just saw that we don't use the tag 
    "type-dependent"

Can you please update rspec to add it? It's used to generate the table in the README to add if the rule needs Typescript type-checking

2024-09-13 14:08 UTC, ericmorand-sonarsource commented on sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S2301.json
> +    "design"
Yes, nice catch, let me fix RSpec and update this PR.

2024-09-13 14:21 UTC, ericmorand-sonarsource commented on sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S2301.json
> +    "design"
@vdiez We should be good now.

2024-09-16 07:10 UTC, yassin-kammoun-sonarsource commented on packages/jsts/src/rules/S2301/meta.ts
> +    requiresTypeChecking: false,
This should be true since we use type information, right?

```suggestion
    requiresTypeChecking: true,
```

2024-09-16 07:15 UTC, ericmorand-sonarsource commented on packages/jsts/src/rules/S2301/meta.ts
> +    requiresTypeChecking: false,
Good catch Yassin, thanks.

2024-09-16 07:17 UTC, yassin-kammoun-sonarsource approved these changes

2024-09-16 07:44 UTC, merged