JS-65 Create rule S7063 (`no-top-level-side-effects`): Module loading should not have side effects
SonarSource/SonarJS pull request #4807
Opened 2024-09-09 11:29 UTC by zglicz

2024-09-09 14:48 UTC, zglicz commented on packages/jsts/src/rules/README.md
> +| [pluginRules-of-hooks](https://sonarsource.github.io/rspec/#/rspec/S6440/javascript)                    | React Hooks should be properly called
@vdiez - can you tell me how this is generated? Seems like `no-async-constructor` and `no-skipped-test` didn't manage to update this file. Also, this rule name is a bit messed up.

I also don't have my new rule in here as well, hence, I'd like to understand...

2024-09-09 16:57 UTC, vdiez commented on packages/jsts/src/rules/README.md
> +| [pluginRules-of-hooks](https://sonarsource.github.io/rspec/#/rspec/S6440/javascript)                    | React Hooks should be properly called
`npm run eslint-docs` from packages/jsts/src/rules/

I can show you tomorrow

2024-09-10 07:16 UTC, zglicz commented on packages/jsts/src/rules/README.md
> +| [pluginRules-of-hooks](https://sonarsource.github.io/rspec/#/rspec/S6440/javascript)                    | React Hooks should be properly called
No worries, I've updated it. This rule name is I guess on purpose, it just wasn't re-generated...

2024-09-10 09:49 UTC, zglicz commented on packages/jsts/src/rules/README.md
> +| [pluginRules-of-hooks](https://sonarsource.github.io/rspec/#/rspec/S6440/javascript)                    | React Hooks should be properly called
Addressing this in - https://github.com/SonarSource/SonarJS/pull/4808

2024-09-10 13:12 UTC, yassin-kammoun-sonarsource requested changes
Let's rename the PR's title based on the [commit guidelines](https://xtranet-sonarsource.atlassian.net/wiki/spaces/LANG/pages/2567241836/JS+Commit+Guidelines#Examples).

2024-09-10 13:12 UTC, yassin-kammoun-sonarsource commented on packages/jsts/src/rules/S7063/rule.ts
> +      message: 'Do not include conditional statements on module top level',
```suggestion
      message: 'Do not include conditional statements on module top level.',
```

2024-09-10 13:12 UTC, yassin-kammoun-sonarsource commented on packages/jsts/src/rules/S7063/unit.test.ts
> +ruleTester.run('"Array.reduce()" calls should include an initial value', rule, {
```suggestion
ruleTester.run('Module with exports should not include side effects, rule, {
```

2024-09-11 09:35 UTC, zglicz commented on packages/ruling/tests/tools/testProject.ts
> +].map(pattern => new Minimatch(pattern, { nocase: true, dot: true }));
@yassin-kammoun-sonarsource - this fixes the issue described in Slack, with multiple .dot folders not matching this - https://sonarsource.slack.com/archives/C03DLUN6GR3/p1726045054704339?thread_ts=1725888470.811169&cid=C03DLUN6GR3

2024-09-11 09:49 UTC, yassin-kammoun-sonarsource commented on packages/ruling/tests/tools/testProject.ts
> +].map(pattern => new Minimatch(pattern, { nocase: true, dot: true }));
Thanks for taking care of that!

Maybe we should extract this fix into a separate PR. Alternatively, we could have two distinct commits in this PR that we don't squash on merging:

1. One commit for the rule implementation.
2. One commit for the ruling fix.

As you prefer.

2024-09-11 10:25 UTC, yassin-kammoun-sonarsource reviewed
@zglicz Looks good overall, but I have one minor concern about the locations of the issues we raise.

We are currently raising issues on whole statements and expressions, which could affect the user experience. To illustrate my point, consider the following Peach issues raised by two different rules:

- [S4139](https://peach.aws-prd.sonarsource.com/project/issues?issues=c712ee26-2cc1-4634-b4cb-b05a1a885c1f&open=c712ee26-2cc1-4634-b4cb-b05a1a885c1f&id=armor-js%3Abtlejuice) raises on the `for`-keyword
- [S1535](https://peach.aws-prd.sonarsource.com/project/issues?issues=332e5c01-6816-44fd-b803-6cf8808710a7&open=332e5c01-6816-44fd-b803-6cf8808710a7&id=armor-js%3Apdfjs) raises at the whole `for`-loop.

I think we can agree that the first issue is less aggressive on the user's eye. Now things get worse when different rules raise issues on the same node (see [example](https://peach.aws-prd.sonarsource.com/code?id=armor-js%3Abtlejuice&selected=armor-js%3Abtlejuice%3Acore.js&line=278)). It's obviously unavoidable to have issues on overlapping code portions, but we can mitigate this to some extent.

This is just a FYI, as I don't have a strong opinion on the matter. I let you decide what you think is best, but if you want to "improve" this, we could adjust the locations where we raise issues:

- `for`-statement -> `if`-keyword
- `if`-statement -> `if`-keyword
- variable declaration -> `var`-keyword, `let`-keyword, `const`-keyword
- assignment -> `=`-operator
- call -> callee

For instance, [here](https://github.com/SonarSource/SonarJS/blob/4b817fda7cad74aa412f23733a5c1d450ed51c1f/packages/jsts/src/rules/S4139/rule.ts#L53) is how S4139 reports issues at the token level. It should be straightforward for conditionals, loops, and declarations as it's always the first token we are interested in.

Please let me know what are your thoughts so that I can approve the PR if you decide to keep the current implementation (which is perfectly fine).

2024-09-11 10:25 UTC, yassin-kammoun-sonarsource commented on packages/jsts/src/rules/S7063/unit.test.ts
> +      errors: 1,
Let's assert at least once the issue message and location instead of just asserting the number of expected issues.

2024-09-11 15:09 UTC, closed without merging