JS-261 Update easy deps
SonarSource/SonarJS pull request #4825
Opened 2024-09-17 14:29 UTC by zglicz

Use `ncu -i --format group` and for now, only bump the easy ones.

2024-09-18 08:52 UTC, zglicz commented on sonar-plugin/sonar-javascript-plugin/pom.xml
>                      <file>${project.build.directory}/${project.build.finalName}-win-x64.jar</file>
Updating the sizes, as the jar is just slightly above the limits, so it seems like only a slight increase.

`
[ERROR] Rule 0: org.apache.maven.enforcer.rules.files.RequireFilesSize failed with message:
[ERROR] /tmp/cirrus-ci-build/sonar-plugin/sonar-javascript-plugin/target/sonar-javascript-plugin-10.15.0-SNAPSHOT-multi.jar size (87528440) too large. Max. is 87500000/tmp/cirrus-ci-build/sonar-plugin/sonar-javascript-plugin/target/sonar-javascript-plugin-10.15.0-SNAPSHOT-multi.jar`
`[ERROR] Rule 1: org.apache.maven.enforcer.rules.files.RequireFilesSize failed with message:
[ERROR] /tmp/cirrus-ci-build/sonar-plugin/sonar-javascript-plugin/target/sonar-javascript-plugin-10.15.0-SNAPSHOT-linux-x64.jar size (50579040) too large. Max. is 50000000/tmp/cirrus-ci-build/sonar-plugin/sonar-javascript-plugin/target/sonar-javascript-plugin-10.15.0-SNAPSHOT-linux-x64.jar
[ERROR]`
`[ERROR] /tmp/cirrus-ci-build/sonar-plugin/sonar-javascript-plugin/target/sonar-javascript-plugin-10.15.0-SNAPSHOT.jar size (27659105) too large. Max. is 27500000/tmp/cirrus-ci-build/sonar-plugin/sonar-javascript-plugin/target/sonar-javascript-plugin-10.15.0-SNAPSHOT.jar`

2024-09-18 12:07 UTC, vdiez requested changes
Please sync versions with `packages/jsts/src/rules/package.json`

2024-09-18 14:02 UTC, vdiez approved these changes
just small comment

2024-09-18 14:02 UTC, vdiez commented on packages/jsts/src/rules/S5860/rule.ts
> +    backreference.ambiguous
shouldn't we use same helper here?

2024-09-19 10:28 UTC, zglicz reviewed
All of the ruling changes are accounted for.

2024-09-19 10:28 UTC, zglicz commented on its/ruling/src/test/expected/jsts/ant-design/javascript-S6790.json
> -37,
This stopped showing up due to an update in `eslint-react-plugin` in v7.36 - commit https://github.com/jsx-eslint/eslint-plugin-react/pull/3807

2024-09-19 10:28 UTC, zglicz commented on its/ruling/src/test/expected/jsts/console/typescript-S6790.json
> -56
Same explanation for this file as above

2024-09-19 10:28 UTC, zglicz commented on its/ruling/src/test/expected/jsts/desktop/typescript-S6819.json
> +],
This seems to be a false positive stemming from using React components and us not understanding it. This was first reported here - https://community.sonarsource.com/t/s6819-prefer-tag-over-role-is-misleading/107348/7 and we have a jira task to track these - https://github.com/SonarSource/SonarJS/issues/4647

I'm not sure why it just now starting showing up in the ruling, but I think it's fair.

2024-09-19 10:28 UTC, zglicz commented on its/ruling/src/test/expected/jsts/moose/typescript-S1082.json
> +],
This is a true-positive, that wasn't triggering before
![image](https://github.com/user-attachments/assets/d9ef75b1-0dba-46a4-b3c7-c3c2b25df57e)

2024-09-19 10:28 UTC, zglicz commented on its/ruling/src/test/expected/jsts/moose/typescript-S1082.json
> +],
True-positive

![image](https://github.com/user-attachments/assets/12faf48d-85a5-4c55-a6c7-9a176b60ef03)

2024-09-19 10:28 UTC, zglicz commented on its/ruling/src/test/expected/jsts/redux/javascript-S6790.json
> -26,
same explanation as above

2024-09-19 12:11 UTC, merged