JS-345 Migrate from CommonJS to ESModules
SonarSource/SonarJS pull request #4863
Opened 2024-10-08 08:59 UTC by vdiez

Fixes https://sonarsource.atlassian.net/browse/JS-345

2024-10-09 08:19 UTC, kebetsi commented
It looks weird how all the imports in TS code use the `.js` extension. How does this work? Do we already execute tests against compiled JS files?

2024-10-09 08:28 UTC, kebetsi commented
why aren't we using the packageJsons in project analysis?

2024-10-09 08:35 UTC, kebetsi commented
Is this the pattern to load some CJS code?
```js
import Module from 'node:module';
const require = Module.createRequire(import.meta.url);
require.resolve('@typescript-eslint/parser'),
```

2024-10-09 08:39 UTC, yassin-kammoun-sonarsource requested changes

2024-10-09 08:52 UTC, vdiez commented on package.json
> +    "esprima": "4.0.1",
i would say that's another ticket, here we are just adding a dependency that was missing in an already existing test

2024-10-09 08:52 UTC, vdiez commented on .cirrus/nodejs.Dockerfile
> -ARG NODE_VERSION=18
correct

2024-10-09 08:54 UTC, vdiez commented on packages/ruling/tests/filter/JavaScriptExclusionsFilter.ts
> +import { bundleAssessor } from './bundleAssessor.js';
that's how it is at the moment, further reads https://stackoverflow.com/a/77150985

2024-10-09 08:56 UTC, vdiez commented
> It looks weird how all the imports in TS code use the `.js` extension. How does this work? Do we already execute tests against compiled JS files?
> 
> It looks very verbose when replacing things like `../parameters` by `../parameters/index.js`

same answer as I did to Yassin, it's the way it is right now. https://stackoverflow.com/a/77150985

2024-10-09 08:57 UTC, vdiez commented
> why aren't we using the packageJsons in project analysis?

that was from another PR about better packagejsons lookup from eric, appears here due to rebase

2024-10-09 08:58 UTC, vdiez commented
> Is this the pattern to load some CJS code?
> 
> ```js
> import Module from 'node:module';
> const require = Module.createRequire(import.meta.url);
> require.resolve('@typescript-eslint/parser'),
> ```

correct, otherwise the alternative is dynamic import which is not always possible in top level

2024-10-09 09:05 UTC, kebetsi commented on packages/jsts/src/rules/external.ts
> +const reactPluginRules = pkg.rules;
Can't you do `import { rules: reactPluginRules } from 'eslint-plugin-react';` ?

2024-10-09 09:06 UTC, kebetsi commented on packages/jsts/src/rules/external.ts
> +const reactPluginRules = pkg.rules;
or `import { rules as reactPluginRules } from 'eslint-plugin-react'; `

2024-10-09 09:07 UTC, kebetsi commented on packages/jsts/src/rules/external.ts
> +const reactPluginRules = pkg.rules;
ah it's because the package is CJS, right?

2024-10-09 09:10 UTC, vdiez commented on packages/jsts/src/rules/external.ts
> +const reactPluginRules = pkg.rules;
yes, it does not recognize the exports properly. michal found this workaround

2024-10-09 09:12 UTC, kebetsi commented on pom.xml
> +  <version>10.17.0-SNAPSHOT</version>
you could have done this one in its own commit, but whatever.

2024-10-09 09:13 UTC, vdiez commented on pom.xml
> +  <version>10.17.0-SNAPSHOT</version>
this is already on master, part of the merge with master commit, you can ignore

2024-10-09 09:14 UTC, kebetsi commented on sonar-plugin/bridge/src/test/java/org/sonar/plugins/javascript/bridge/RulesBundlesTest.java
> -
why remove this test?

2024-10-09 09:15 UTC, vdiez commented on sonar-plugin/bridge/src/test/java/org/sonar/plugins/javascript/bridge/RulesBundlesTest.java
> -
RulesBundles should be used for rules bundles, not for bridge bundle, don't know why it was there at all this test. in any case, it does not work now, because rulesBundles has been changed to provide a path to a rules.js file, so no bin/server can be expected there

2024-10-09 09:15 UTC, kebetsi commented on tools/fetch-node/node-distros.mjs
> -export const NODE_VERSION = 'v20.9.0';
we should mention this in the changelog

2024-10-09 09:17 UTC, vdiez commented on tools/fetch-node/node-distros.mjs
> -export const NODE_VERSION = 'v20.9.0';
already in master, also part of the merge with master, you can ignore

2024-10-09 09:29 UTC, kebetsi commented on packages/bridge/tests/memory.test.ts
> -      ),
can't we assert this message anymore?

2024-10-09 09:30 UTC, kebetsi commented on packages/bridge/tests/memory.test.ts
> -      ),
I think you forgot to move it as it's asserted below

2024-10-09 09:31 UTC, kebetsi commented on packages/bridge/tests/router.test.ts
> -     */
Is it overkill to test this part now that we aren't using Jest anymore?

2024-10-09 09:34 UTC, kebetsi commented on packages/bridge/tests/router.test.ts
> +    assert((console.error as Mock<typeof console.error>).mock.calls.length > 0);
Is there no nicer API, like doesn't `mock.fn()` return something that we can use instead of `(console.error as Mock<typeof console.error>).mock`?

2024-10-09 09:45 UTC, kebetsi commented on packages/bridge/tests/server.test.ts
> -    expect.assertions(5);
why remove this one?

2024-10-09 09:52 UTC, kebetsi commented on packages/jsts/tests/linter/wrapper.test.ts
> +          `Visited 'sonar-context' literal from a custom rule ` +
where does this change come from?

2024-10-09 10:00 UTC, kebetsi commented on packages/jsts/tests/rules/index.test.ts
> +      );
there is no importSync?

2024-10-09 11:52 UTC, vdiez commented on packages/bridge/tests/router.test.ts
> +    assert((console.error as Mock<typeof console.error>).mock.calls.length > 0);
it actually returns the mock, but the types do not seem to behave as expected for TypeScript right now it seems. This is more about the node types, so probably there is something better once we update them.

2024-10-09 11:52 UTC, vdiez commented on packages/bridge/tests/server.test.ts
> -    expect.assertions(5);
because a number of assertions is not working anymore. I could use any number and it would always pass

2024-10-09 11:54 UTC, vdiez commented on packages/jsts/tests/linter/wrapper.test.ts
> +          `Visited 'sonar-context' literal from a custom rule ` +
before there were a `custom-rule.js` and a `custom-rule.ts`, the js version only contained a string. it was a very strange test. not we only use the typescript version, which is a custom rule, to parse the file containing the rule.

2024-10-09 11:54 UTC, vdiez commented on packages/jsts/tests/rules/index.test.ts
> +      );
No, AFAIK

2024-10-09 11:54 UTC, kebetsi commented on packages/jsts/tests/rules/index.test.ts
> +      );
Sad

2024-10-09 11:58 UTC, kebetsi commented on packages/bridge/tests/server.test.ts
> -    expect.assertions(5);
There are still a few usages of `expect.assertions()` (I haven't found how to share a search on a certain branch)

<img width="392" alt="Screenshot 2024-10-09 at 13 58 03" src="https://github.com/user-attachments/assets/cccac686-5c37-4b32-b58f-8ca4250b8f56">

2024-10-09 12:04 UTC, vdiez commented on packages/bridge/tests/server.test.ts
> -    expect.assertions(5);
ok, gonna remove those

2024-10-09 12:09 UTC, ericmorand-sonarsource commented
@vdiez , @yassin-kammoun-sonarsource , @kebetsi , about the `.js` extension, the explanation is in the TypeScript documentation:

https://www.typescriptlang.org/docs/handbook/modules/theory.html#module-specifiers-are-not-transformed

> While the module compiler option can transform imports and exports in input files to different module formats in output files, the module specifier (the string from which you import, or pass to require) is always emitted as-written.

With CommonJS, importing without an extension is allowed because of how the algorithm is specified (roughly: first, lookup for a file, then lookup for a directory that contains an index). With ESM, importing a directory is not supported and the extension is mandatory. Since TS doesn't transform the module specifier, the extension must be one of the final artifacts.

2024-10-09 12:17 UTC, vdiez commented on packages/bridge/tests/router.test.ts
> -     */
not sure what that comment actually meant, tbh. I don't see the relation with the test

2024-10-09 12:22 UTC, vdiez commented on packages/bridge/tests/server.test.ts
> -    expect.assertions(5);
done

2024-10-09 12:40 UTC, vdiez commented on packages/bridge/tests/memory.test.ts
> -      ),
added in latest commit, good catch

2024-10-09 12:45 UTC, kebetsi approved these changes
Amazing job @vdiez and @zglicz !

2024-10-11 12:27 UTC, yassin-kammoun-sonarsource approved these changes

2024-10-11 12:33 UTC, merged

2024-10-25 14:05 UTC, pumano commented
would love to get fresh release with it!

2024-10-28 08:37 UTC, vdiez commented
Hi @pumano,

for the moment we will still only publish CommonJS target in the eslint-plugin-sonarjs package. We plan to provide both targets soon.

Cheers