JS-359 Create rule S6418 (`hardcoded-secrets`): secrets should not be hardcoded
SonarSource/SonarJS pull request #4920
Opened 2024-11-21 07:50 UTC by kebetsi

2024-11-25 17:59 UTC, kebetsi commented on packages/jsts/src/rules/S6418/unit.test.ts
I need to delete this file, as I was using the comment-based test file.

2024-11-25 18:01 UTC, kebetsi commented on packages/jsts/src/rules/S6418/rule.ts
> +const DEFAULT_RANDOMNESS_SENSIBILITY = 3.0;
I'm not sure if we need default values here as well, or if they are somehow generated from the Java check classes to the meta.

2024-11-25 18:02 UTC, kebetsi commented on its/sources/jsts/custom/S6418.ts
I don't need that one anymore

2024-11-25 18:16 UTC, kebetsi commented on its/ruling/src/test/expected/jsts/Ghost/javascript-S6418.json
> +]
those are TPs:

```js
    this.post('/authentication/token', function () {
        return {
            access_token: '5JhTdKI7PpoZv4ROsFoERc6wCHALKFH5jxozwOOAErmUzWrFNARuH1q01TYTKeZkPW7FmV5MJ2fU00pg9sm4jtH3Z1LjCf8D6nNqLYCfFb2YEKyuvG7zHj4jZqSYVodN2YTCkcHv6k8oJ54QXzNTLIDMlCevkOebm5OjxGiJpafMxncm043q9u1QhdU9eee3zouGRMVVp8zkKVoo5zlGMi3zvS2XDpx7xsfk8hKHpUgd7EDDQxmMueifWv7hv6n',
            expires_in: 3600,
            refresh_token: 'XP13eDjwV5mxOcrq1jkIY9idhdvN3R1Br5vxYpYIub2P5Hdc8pdWMOGmwFyoUshiEB62JWHTl8H1kACJR18Z8aMXbnk5orG28br2kmVgtVZKqOSoiiWrQoeKTqrRV0t7ua8uY5HdDUaKpnYKyOdpagsSPn3WEj8op4vHctGL3svOWOjZhq6F2XeVPMR7YsbiwBE8fjT3VhTB3KRlBtWZd1rE0Qo2EtSplWyjGKv1liAEiL0ndQoLeeSOCH4rTP7',
            token_type: 'Bearer'
        };
    });
```

2024-11-25 18:17 UTC, kebetsi commented on sonar-plugin/sonar-javascript-plugin/pom.xml
> +                  <minsize>65000000</minsize>
I had to lower it when I compiled this last week.

2024-11-25 18:37 UTC, yassin-kammoun-sonarsource requested changes
Looks great overall, but there are a few things to address.

2024-11-25 18:37 UTC, yassin-kammoun-sonarsource commented on sonar-plugin/javascript-checks/src/main/java/org/sonar/javascript/checks/HardcodedSecretsCheck.java
> +      new HardcodedSecretsCheck.Config(secretWords, randomnessSensibility)
You don't really need to prefix the inner class with the outer class because the inner class is static (Java FTW).

```suggestion
      new Config(secretWords, randomnessSensibility)
```

2024-11-25 18:37 UTC, yassin-kammoun-sonarsource commented on packages/jsts/src/rules/S6418/rule.ts
> +const DEFAULT_RANDOMNESS_SENSIBILITY = 3.0;
Until recently, we wouldn't need them, but now that we expose most of rules in the ESLint plugin, I am not really sure. In any case, it doesn't hurt to have them here.

2024-11-25 18:37 UTC, yassin-kammoun-sonarsource commented on packages/jsts/src/rules/S6418/rule.ts
> +  const ValueSuspect = findValueSuspect(extractDefaultOperatorIfNeeded(node));
We can use camelCase instead of PascalCase here and below.

2024-11-25 18:37 UTC, yassin-kammoun-sonarsource commented on packages/jsts/src/rules/S6418/rule.ts
> +function findValueSuspect(node: TSESTree.Node | undefined | null): TSESTree.Node | undefined {
```suggestion

function findValueSuspect(node: TSESTree.Node | undefined | null): TSESTree.Node | undefined {
```

2024-11-25 18:37 UTC, yassin-kammoun-sonarsource commented on packages/jsts/src/rules/S6418/rule.ts
> +  return secretWords.split(',').map(word => new RegExp(`(${word})`, 'i'));
We should try-catch this statement because RegExp throws a syntax error if the pattern is malformed.

```
% node
Welcome to Node.js v22.11.0.
Type ".help" for more information.
> new RegExp("[a-z")
Uncaught SyntaxError: Invalid regular expression: /[a-z/: Unterminated character class
```

Let's add test case with a malformed regular expression.

2024-11-25 18:37 UTC, yassin-kammoun-sonarsource commented on packages/jsts/src/rules/S6418/rule.ts
> +  return secretWords.split(',').map(word => new RegExp(`(${word})`, 'i'));
Are all the other implementations also using regular expressions? It's not really safe :/

2024-11-25 18:37 UTC, yassin-kammoun-sonarsource commented on sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S6418.html
> +<pre>
You will need to update the RSPEC with JavaScript code snippets.

2024-11-25 18:37 UTC, yassin-kammoun-sonarsource commented on sonar-plugin/javascript-checks/src/test/java/org/sonar/javascript/checks/HardcodedPasswordCheckTest.java
> +    HardcodedPasswordCheck check = new HardcodedPasswordCheck();
We can add another Java test class for the new rule asserting the default configuration and a custom one.

2024-11-26 08:24 UTC, kebetsi commented on packages/jsts/src/rules/S6418/rule.ts
> +  return secretWords.split(',').map(word => new RegExp(`(${word})`, 'i'));
https://sonarsource.atlassian.net/browse/JS-426

2024-11-26 08:40 UTC, yassin-kammoun-sonarsource approved these changes
Great job!

2024-11-26 09:05 UTC, vdiez commented on packages/jsts/src/rules/S6418/rule.ts
> +        handleAssignmentExpression(context, node as TSESTree.AssignmentExpression);
why do you cast all nodes to TSESTree nodes? I see you had to change the helpers, but I don't understand the reasoning behind. Shouldn't it be enough to handle estree nodes directly?

2024-11-26 09:10 UTC, kebetsi commented on packages/jsts/src/rules/S6418/rule.ts
> +        handleAssignmentExpression(context, node as TSESTree.AssignmentExpression);
maybe it's not needed anymore, I was struggling with that because some helpers required TSESTree nodes.

2024-11-26 09:12 UTC, vdiez commented on packages/jsts/src/rules/S6418/rule.ts
> +        handleAssignmentExpression(context, node as TSESTree.AssignmentExpression);
I think it's better to cast only at the very end, meaning when you use a helper that requires TSEStree types. So you keep using estree types and no need to propagate your types to the helpers which do not use TSEStree

2024-11-26 09:24 UTC, kebetsi commented on packages/jsts/src/rules/S6418/rule.ts
> +        handleAssignmentExpression(context, node as TSESTree.AssignmentExpression);
I adapted the code to only use estree: https://github.com/SonarSource/SonarJS/pull/4920/commits/aa0fbe5dff44abbe9267e223639d3e492b8726ad

2024-11-26 09:29 UTC, vdiez commented on packages/jsts/src/rules/S6418/rule.ts
> +        handleAssignmentExpression(context, node as TSESTree.AssignmentExpression);
Thx! Can you also revert the changes on the helpers now?

2024-11-26 09:56 UTC, kebetsi commented on packages/jsts/src/rules/S6418/rule.ts
> +        handleAssignmentExpression(context, node as TSESTree.AssignmentExpression);
I removed all the changes in the helpers now

2024-11-26 15:23 UTC, merged