Add runtime telemetry
SonarSource/SonarJS pull request #5017
Opened 2024-12-16 10:25 UTC by zglicz

Adding runtime telemetry as per the *bonus* part of the MMF.
Refactoring the code a bit, so only querying the node server, if telemetry is actually enabled.

2024-12-16 15:24 UTC, saberduck commented on sonar-plugin/bridge/src/main/java/org/sonar/plugins/javascript/bridge/BridgeServer.java
> +  record TelemetryNodeResponse(List<Dependency> dependencies) {}
why `Node` in the name? Seems a bit redudant/not important?  (imagine we don't use Node anymore, would you want to rename this?)

2024-12-16 15:43 UTC, saberduck commented on sonar-plugin/bridge/src/main/java/org/sonar/plugins/javascript/bridge/BridgeServer.java
> +  NodeCommand command();
I don't think it's very nice to expose this in the interface directly. I would prefer this remain internal to the bridge module. Perhaps we could just collect the required data in `Telemetry` object and only expose that.

2024-12-16 15:45 UTC, saberduck requested changes
I think it would be better not to expose `NodeCommand` outside of the `bridge` module. We could instead just add more fields to the `Telemetry` record

2024-12-17 15:53 UTC, saberduck commented on sonar-plugin/bridge/src/main/java/org/sonar/plugins/javascript/bridge/BridgeServer.java
> +  record TelemetryData(List<Dependency> dependencies, Map<String, String> runtime) {}
I think it Java it would be nicer to have proper `record` for runtime info instead of generic `Map<String, String>`

2024-12-18 09:44 UTC, saberduck commented on sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/analysis/AnalysisWithProgram.java
> +      new PluginTelemetry(context, bridgeServer).reportTelemetry();
optional - I would only pass value from `bridgeServer.getTelemtry()` instead of passing the whole `bridgeServer`

2024-12-18 09:44 UTC, saberduck approved these changes

2024-12-18 10:23 UTC, zglicz commented on sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/analysis/AnalysisWithProgram.java
> +      new PluginTelemetry(context, bridgeServer).reportTelemetry();
This way, if telemetry is not available or not necessary to compute for some reason, we wouldn't be computing it.

2024-12-18 10:44 UTC, merged